### ISSUE TITLE
How to use dev-server with esbuild?

### ISSUE THREAD

**Issue by samevision** [modernweb-dev/web#1006]
Hello,

I wanted to try esbuild to speed up the compiling process. Unfortunately I am not sure about using the dev server.

My esbuild.config.js looks like this:
```
require('esbuild').build({
    entryPoints: ['./src/index.js'],
    bundle: true,
    minify: true,
    outfile: './dist/out.js',
    define: {
        'process.env.NODE_ENV': '"production"'
    }
}).catch(() => process.exit(1))
```

This works fine for bundling. To set up the dev server I use web-dev-server.config.mjs:
```
import { esbuildPlugin } from '@web/dev-server-esbuild'

export default {
  open: false,
  nodeResolve: true,
  watch: true,
  appIndex: './public/index.html',
  debug: false,
  rootDir: './src/',
  plugins: [
    esbuildPlugin({
      target: 'auto'
    })
  ]
}
```

How am I able to use my esbuild.config.js while starting the server?

Best

**Comment by LarsDenBakker** [comment]
Web dev server is based on es module workflows. The esbuild plugin uses the esbuild single file transform API, it doesn't do any bundling. This means most of the esbuild options don't apply. The plugin docs describe which options you can set.

**Comment by samevision** [comment]
Thanks for your response. That's why I am struggling with it. How am I able to use this dev-server to work on my project that will be compiled with esbuild?

**Comment by LarsDenBakker** [comment]
Option 1:
Use the esbuild plugin to transform single files with esbuild. Using the config you showed above. The dev server should be pointed to a HTML file that exists and any modules will be transformed by esbuild.

See https://github.com/modernweb-dev/example-projects/tree/master/preact-jsx for an example.

Option 2:
Bundle your app with esbuild, and point the dev server to the build output.

**Comment by samevision** [comment]
Option 2:
That is nothing else then http-server, am I right? So I can't make use of watch mode and I have to bundle my app after every single change. That's not really convenient.

Option 1:
That is what I am looking for. I am pointing with
`appIndex: './public/index.html'`
Unfortunately the server doesn't use it: "Not found." and I would have to go to http://localhost:8000/public/index.html.

To access the index.html via http://localhost:8000/ I have to set rootDir: './public/' as well but then I am not able to load my index.js which is in ./src.

**Comment by LarsDenBakker** [comment]
Option 2 can work with any static file server. Web dev server can add things like watch mode.

For option 1, the dev server works like a static server. If your file is located at `/public/index.html` you need to point the browser URL to `/public/`. If you set `open` to `true` it will open the browser on this URL for you.

**Comment by samevision** [comment]
Options 1 brings several problem with it.

1. Importing css: "Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec."
2. Import inside of worker: "Uncaught SyntaxError: Cannot use import statement outside a module"
3. Dynamic import: "Uncaught (in promise) TypeError: Failed to fetch dynamically imported module:"

**Comment by LarsDenBakker** [comment]
You need to enable to loader for each type of transformation you want to do. See the docs for the configuration options: https://modern-web.dev/docs/dev-server/plugins/esbuild/

Looking at the docs it seems like esbuild bundles the CSS to a separate file during bundling. Given that, I'm not sure if esbuild supports importing CSS in the single file transform API. But you can try turning on the loader like this and see what happens:

```js
export default {
  plugins: [
    esbuildPlugin({
      target: 'auto',
      loaders: { '.css', 'css' }
    })
  ]
}
```

I'm not able to say anything about the other issues without a minimal reproduction. However I'm not sure if they're issues with the dev server, or with esbuild.

**Comment by LarsDenBakker** [comment]
I made a separate issue for tracking CSS support. Will close this one in favor of that. Let me know if there are other questions.

https://github.com/modernweb-dev/web/issues/1154
