### ISSUE TITLE
Typescript Code coverage report doesn't show the source

### ISSUE THREAD

**Issue by davidgarsan** [modernweb-dev/web#1014]
The percentage of covered code by tests is show, but the sources are missing.
Instead, the file links of the report points to the compiled build dir (coverage/lcov-report/\_dist\_/App.js.html) with are missing, instead of mapping the original Typescript sources.

**Comment by LarsDenBakker** [comment]
Source maps should work with the test coverage, do you have an example of the config and CLI args you're using?

**Comment by LarsDenBakker** [comment]
Judging from the `_dist_` in the path, perhaps you're using snowpack? There is a tracking issue to support source maps in snowpack: https://github.com/snowpackjs/snowpack/issues/1213

**Comment by davidgarsan** [comment]
You're right @LarsDenBakker, apparently that's the issue. I'll check it there 👍

**Comment by LarsDenBakker** [comment]
Will close this one in favor of tracking this on the snowpack side.
