### ISSUE TITLE
[Bug] esbuildPlugin does not remove type references

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [modernweb-dev/web#1026]
esbuildPlugin will not remove some type references. Take a look at the following setup.

```ts
// test/bar.ts
export const x = 'something';
export type y = Record<string, string>;
```

```ts
// test/foo.ts
export { x, y } from './bar';
```

```ts
// test/dummy.spec.ts
import { expect } from '@open-wc/testing';
import { x } from './foo';

describe('dummy', () => {
  it('does something', () => {
    expect('something').to.equal(x);
  });
});
```

```ts
// web-test-runner.config.mjs
import { esbuildPlugin } from '@web/dev-server-esbuild';

export default {
  preserveSymlinks: true,
  plugins: [
    esbuildPlugin({ ts: true })
  ]
};
```

The type `y` is defined in test/foo.ts, re-exported in test/bar.ts and consumed in test/dummy.spec.ts. There is nothing wrong with this test, however it will throw a SyntaxError when it's run.

`web-test-runner \"test/**/*.spec.ts\" --node-resolve`

```
     SyntaxError: The requested module './bar.ts' does not provide an export named 'y' 
```

If esbuild bundles the entire project, it removes all references to `y` from the output. But esbuildPlugin makes esbuild transpile each file individually. When esbuild transpiles test/foo.ts it doesn't know that `y` is a type definnition and leaves the reference untouched.

```
$ npx esbuild --bundle --format=esm --external:* test/foo.ts
// test/foo.ts
import {x, y} from "./bar";
export {
  x,
  y
};
```

**Comment by LarsDenBakker** [comment]
This is an interesting case... but there is nothing we can really do about it. We use the single file transform API, and as you mention that doesn't do any type checking and only strips types. You could use typescript type imports, I assume these would be stripped properly.

**Comment by LarsDenBakker** [comment]
The issue here is actually with the reexport, this makes esbuild unable to distinguish whether it's a type or a value (it doesn't do any type analysis itself). 

I think either of these would work:

```js
import { x, y } from './bar';
export type { x, y };
```

```js
import type { x, y } from './bar';
export { x, y };
```

See more for context https://github.com/evanw/esbuild/issues/585
