### ISSUE TITLE
Unable to get Dev Server's ESBuild plugin to treat JS in node_modules as JSX

### ISSUE THREAD

**Issue by jameswomack** [modernweb-dev/web#1036]
<img width="810" alt="Screen Shot 2020-11-30 at 2 31 14 PM" src="https://user-images.githubusercontent.com/77849/100673675-b42cd200-3318-11eb-8d33-f43edac4061a.png">
<img width="354" alt="Screen Shot 2020-11-30 at 2 31 37 PM" src="https://user-images.githubusercontent.com/77849/100673712-c7d83880-3318-11eb-982f-7bbba8718317.png">

All JSX within my own source directory is being properly transpiled. This issue isn't present when using ESBuild's CLI directly.

**Comment by jameswomack** [comment]
It turns out this is due to how the plugin handles the target string

**Comment by LarsDenBakker** [comment]
Does the target prevent compiling jsx?
