### ISSUE TITLE
[test-runner-visual-regression] Support passing function to baseDir

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1040]
Currently it's not possible to organize the screenshots in subfolders:

```
screenshots/
|
|-- lumo/
|   |-- button/
|   |-- checkbox/
|
`-- material/
    |-- button/
    |-- checkbox/
```

In `hermione` this is handled using [screenshotsDir](https://github.com/gemini-testing/hermione#screenshotsdir) config option which allows to pass a function.

**Comment by LarsDenBakker** [comment]
Seems like a good idea, what should be the options of the function?

**Comment by web-padawan** [comment]
I think we could use the same options as those passed to functions allowing to change the file name.

**Comment by web-padawan** [comment]
> Currently it's not possible to organize the screenshots in subfolders:

I was wrong, this can be actually done with `getBaselineName` etc but the config could be cleaner.
This is how it currently looks in my case:

```js
visualRegressionPlugin({
  baseDir: 'test/visual/screenshots',
  getBaselineName: ({ browser, name }) => {
    const [theme, component, test] = name.split(':');
    return path.join(browser, 'baseline', theme, component, test);
  },
  getDiffName: ({ browser, name }) => {
    const [theme, component, test] = name.split(':');
    return path.join(browser, 'failed', theme, component, `${test}-diff`);
  },
  getFailedName: ({ browser, name }) => {
    const [theme, component, test] = name.split(':');
    return path.join(browser, 'failed', theme, component, test);
   }
})
```

**Comment by web-padawan** [comment]
Closing as the solution listed above covers the original use case.
