### ISSUE TITLE
[dev-server] How to load images using @rollup/plugin-image

### ISSUE THREAD

**Issue by brecke** [modernweb-dev/web#1064]
Hi there,

I'm starting this greenfield project with dev-server and rollup (for bundling). For now I'm trying to load an image inside a web component, for which I'm using `@rollup/plugin-image`. However, just by following the docs (https://modern-web.dev/docs/dev-server/plugins/rollup/) alone I'm unable to load the jpg image. Here's what I'm trying:

```js
import { fromRollup } from '@web/dev-server-rollup';
import image from '@rollup/plugin-image';
...

  plugins: [
    fromRollup(image)(),
    ...
  ]
```

And I'm running this with `"start:watch": "web-dev-server --node-resolve --watch"`

By the way, if I bundle it first it works. That means running `rollup -w -c rollup.config.js` and then `web-dev-server --watch --node-resolve --root-dir dist --app-index index.html --compatibility none`.

The docs state that this plugin has been tested to work, so I guess I'm doing something wrong. What would it be?

**Comment by LarsDenBakker** [comment]
If I remember correctly, the rollup img plugin will transform images to data urls so we need to tell the server to serve these files as JS. I also recommend using an "include" to limit the amount of work done by the plugin for speed:

```js
import { fromRollup } from '@web/dev-server-rollup';
import image from '@rollup/plugin-image';

export default {
  mimeTypes: {
    './images/**/*.png': 'js'
  },
  plugins: [
    fromRollup(image)({ include: ['./images/**/*.png'] }),
  ]
}

 
```

**Comment by brecke** [comment]
Hi @LarsDenBakker thanks for replying.

Unfortunately that doesn't work, I'm still getting the `Script from “http://localhost:8000/images/user.png” was blocked because of a disallowed MIME type (“image/png”)` error on console.

Just a note, the way I'm trying to display the image is:

```js
import logo from '../images/user.png';

...

  render() {
    return html`
      <div class="test-colours">
        <h1>My app</h1>
        <img height="200px" width="200px" src="${logo}" alt="Description" />
      </div>
    `;
  }
```

Maybe I'm missing something?

**Comment by LarsDenBakker** [comment]
Is the path of the glob correct? It should be relative to your current working directory.

**Comment by brecke** [comment]
Just tried it but got the same result. Is there an example of this somewhere I can check?

**Comment by LarsDenBakker** [comment]
I created this and that works: https://github.com/modernweb-dev/example-projects/tree/rollup-img/rollup-image

**Comment by brecke** [comment]
Indeed it does, thanks. It's working now 🎉
