### ISSUE TITLE
[dev-server-import-maps] support for non-local import (CDN URL)

### ISSUE THREAD

**Issue by iFwu** [modernweb-dev/web#1092]
I want to use a CDN URL like `https://esm.sh/react` in `@web/dev-server-import-maps` plugin. Currently, if I use `inject`, it will only resolve to local files.

**Comment by LarsDenBakker** [comment]
I don't understand what you mean, what's going wrong?

**Comment by iFwu** [comment]
@LarsDenBakker 

Example `web-test-runner.config.mjs` file:
```js
import { importMapsPlugin } from '@web/dev-server-import-maps';

export default {
  plugins: [
    importMapsPlugin({
      inject: {
        importMap: {
          imports: { react: 'https://esm.sh/react' },
        },
      },
    }),
  ],
};
```

And in my test file:
```js
import React from 'react'
```

The test runner will report:
```
404 network requests:
    - react?wds-import-map=0
```

Change my test file to `import React from 'https://esm.sh/react'` and the import works fine.

**Comment by LarsDenBakker** [comment]
This looks like a bug indeed, we need to make sure we handle URLs in import maps correctly.
