### ISSUE TITLE
Not support `rollup-plugin-inject-process-env` plugin

### ISSUE THREAD

**Issue by iFwu** [modernweb-dev/web#1093]
I use `rollup-plugin-inject-process-env` and it prevents dev-server from opening browsers.

**Comment by bennypowers** [comment]
That plugin is deprecated in favour of `@rollup/plugin-replace` do you have the same issue with that one?

**Comment by iFwu** [comment]
> That plugin is deprecated in favour of `@rollup/plugin-replace` do you have the same issue with that one?

That plugin works fine. However, I thought `@rollup/plugin-replace` doesn't fit for some cases since it uses string-based replacement. I prefer to have an AST level transform as `babel-plugin-transform-define` or `babel-plugin-dotenv-import` does. I see `esbuild` has an option `define` but it doesn't work(https://github.com/modernweb-dev/web/issues/1006).

**Comment by LarsDenBakker** [comment]
Could you share more details on what doesn't work?

**Comment by iFwu** [comment]
> Could you share more details on what doesn't work?

Configuration: 
```js
import rollupInject from 'rollup-plugin-inject-process-env'
import { esbuildPlugin } from '@web/dev-server-esbuild'
import { fromRollup } from '@web/dev-server-rollup'
import { config } from 'dotenv'

const inject = fromRollup(rollupInject)

config()

export default {
  plugins: [
    inject({
      NODE_ENV: process.env.NODE_ENV,
    }),
    esbuildPlugin({
      ts: true,
      target: 'es2020',
    }),
  ],
}

```

test runner report with error:
```
src/test-runner/basic.test.ts:
 ❌ Browser tests did not start after 20000ms You can increase this timeout with the testsStartTimeout option. Check the browser logs or open the browser in debug mode for more information. 

Error while transforming index.html: Could not resolve import "\uFFFDrollup-plugin-inject-process-env".
> 1 | import "\uFFFDrollup-plugin-inject-process-env";
    |        ^
  2 | (function() {
  3 |   (function() {
  4 |     var module = {};

Chromium: |██████████████████████████████| 1/1 test files | 0 passed, 0 failed
```

**Comment by LarsDenBakker** [comment]
The issue had to do with the way the HTML parser handles null bytes, a special characters used by some rollup plugins. Because `rollup-plugin-inject-process-env` injects an import with a null byte into every single file, they also got injected into the inline scripts of the test runner.

Should be fixed with https://github.com/modernweb-dev/web/pull/1144. I do recommend limiting where the plugin injects into, because it does make things slower.
