### ISSUE TITLE
Test Runner esbuildPlugin JSON imports not working

### ISSUE THREAD

**Issue by evanblack** [modernweb-dev/web#1098]
Getting the error message
```
SyntaxError: The requested module './data.json' does not provide an export named 'default'
```
Here is my config:

```
const { esbuildPlugin } = require('@web/dev-server-esbuild');

module.exports = {
	files: 'test/**/*.test.js',
	nodeResolve: true,
	watch: false,
	debug: true,
	plugins: [esbuildPlugin({ json: true, target: 'auto' })],
};
```
I've also tried the non-shorthand `loaders` option to no avail. My esbuild builds are working just fine and according to the esbuild docs the given error shouldn't happen.

> https://esbuild.github.io/content-types/#json

**Comment by evanblack** [comment]
After some digging it would seem that I need to add `format: 'esm'` [here](https://github.com/modernweb-dev/web/blob/28890a05be08f5b8ef9f8896f44ab8f990f09771/packages/dev-server-esbuild/src/EsbuildPlugin.ts#L183) for this to work in order for JSON files to be transformed to es modules instead of cjs. I can't seem to find an appropriate `target` setting for this to work. Would it make sense to have an additional config option somewhere or do we always want the format to be `esm` here?

**Comment by evanblack** [comment]
For now I've gotten around this for my use case by just writing a simple custom plugin:

**Comment by LarsDenBakker** [comment]
When I tested it the json plugin always output commonjs. Sounds like the ESM format is ready now, will take another look at how we handle this in our plugin to see if we can make it a more plug and play experience.

**Comment by LarsDenBakker** [comment]
Fixed in https://github.com/modernweb-dev/web/pull/1142, thanks for reporting!
