### ISSUE TITLE
Import resolution error with import maps

### ISSUE THREAD

**Issue by marvinhagemeister** [modernweb-dev/web#1109]
Over at Preact we finally have time to continue to work on replacing karma with web test runner. There is one error related to import maps that always pops up at least once during a run, despite all tests passing:

```bash
Error while transforming test/browser/customBuiltInElements.test.js: Could not resolve import "preact".
  13 | function _inheritsLoose(subClass, superClass) { subClass.prototype = Object.create(superClass.prototype); subClass.prototype.constructor = subClass; subClass.__proto__ = superClass; }
  14 | 
> 15 | import { createElement, render, Component } from 'preact';
     |                                                  ^
  16 | import { setupScratch, teardown } from '../_util/helpers';
  17 | import { expect } from 'chai';
  18 | var runSuite = typeof customElements == 'undefined' ? xdescribe : describe;
```

The imported path and source where it's imported from differs from run to run. When focusing the failing test in watch mode the error will keep showing up for further runs. But if one kills and restarts web test runner it will often happen in another file and not consistently the same one as before.

Steps to reproduce:

1. Clone `git clone git@github.com:preactjs/preact.git`
2. Run `npm i`
3. Switch to `wtr` branch:`git checkout wtr`
4. Optional: If you head a previous checkout you might need to reset it (we rebased it)
5. Run `yarn test:wtr`

**Comment by LarsDenBakker** [comment]
This happens because we added preload links to speed up test loading. These preload links didn't get properly tagged by the plugin to use an import map for resolving.

**Comment by marvinhagemeister** [comment]
Woa that was quick! Thank you so much :raised_hands:
