### ISSUE TITLE
Watch mode does not work in WSL2

### ISSUE THREAD

**Issue by motss** [modernweb-dev/web#1128]
## Description

Watch mode does not work at all in WSL2 with `wtr --watch`. However, it works fine on Powershell 7. Hitting Enter to re-run all tests will re-run tests with old changes instead of the new ones.

## Steps to reproduce

1. Create simple test and run tests with `wtr --watch` to re-run tests when files being watched changes.
2. Tests should re-run on file save when new changes detected
3. Hit Enter to re-run tests does not help either as it still run tests with old changes

## Expected behavior

Watch mode should work in WSL2.

## Actual behavior

Watch mode does not work at all in WSL2.

**Comment by LarsDenBakker** [comment]
This is likely related to Chokidar, the library we use for watching files, not being able to detect changes. What editor do you use in WSL? Some editors don't save files properly. Are the files stored on the unix subsystem, or on a windows disk?

**Comment by tbetous** [comment]
Hey :wave:

I had the same problem today. It didn't work because I used files that was stored in windows disk. Once moved all files in the unix subsystem it worked like a charm. 

BTW, thanks for your work! 😄
