### ISSUE TITLE
[dev-server] HTML5 video is empty on iOS

### ISSUE THREAD

**Issue by iantomarcello** [modernweb-dev/web#1164]
Hi there. Happy New Year.

## Description
When using `web-dev-server`, HTML5 `video` fails to load on iOS, while working fine on Android and Windows browsers. 

## Steps to reproduce
1.  Have simple `index.html` file with a `video` tag like so:
``` html
<video autoplay muted controls width="100%">
  <source src="example_video.mp4" type="video/mp4">
</video>
```
2. Run `wds --watch --open --app-index index.html`
3. Open the served site on an iOS device.

## Expected behavior
A video playing.

## Actual behavior 
An empty video element.

## Note
1. Using other local server like XAMPP or Browsersync works though; video is visible and plays as expected behavior on iOS. 
2. Unfortunately, I don't have a MacOS device, can't say if it works on it. 
3. Just a guess, this is related to #465 ?

**Comment by LarsDenBakker** [comment]
It's likely related, can you think if it works with https://github.com/koajs/koa-range ?

**Comment by iantomarcello** [comment]
Can't say I am familiar with Koa. 

Although some SO answers ([this](https://stackoverflow.com/questions/53952944/html5-video-problems-on-safari) and [this](https://stackoverflow.com/questions/50168709/html-video-not-playing-in-safari-browser)) do suggest using Range would solve the issue.

**Comment by LarsDenBakker** [comment]
You can add the koa middleware to the dev server: https://modern-web.dev/docs/dev-server/middleware/

**Comment by iantomarcello** [comment]
Wonderful!
Adding koa-range as a middleware solved the issue and got videos to load.

Thanks for your help!
