### ISSUE TITLE
[dev-server-storybook] [dev-server-hmr] Using hmr for mdjs stories causes errors

### ISSUE THREAD

**Issue by alangdm** [modernweb-dev/web#1177]
This error happened while trying to migrate from a project using `@open-wc/demoing-storybook`

## Expected behavior

Using `@web/dev-server-storybook` together with `@open-wc/dev-server-hmr` for mdjs files renders the mdjs properly and has hmr enabled

## Problem

I'm using almost the exact same config as the one from the `@open-wc` init project:

```js
// web-dev-server.config.mjs
import { hmrPlugin, presets } from '@open-wc/dev-server-hmr';

/** Use Hot Module replacement by adding --hmr to the start command */
const hmr = process.argv.includes('--hmr');

export default /** @type {import('@web/dev-server').DevServerConfig} */ ({
  nodeResolve: true,
  open: '/',
  watch: !hmr,

  plugins: [
    hmr && hmrPlugin({ exclude: ['**/*/node_modules/**/*'], presets: [presets.litElement] }),
  ],

});
```

```js
// .storybook/server.mjs
import { storybookPlugin } from '@web/dev-server-storybook';
import baseConfig from '../web-dev-server.config.mjs';

export default /** @type {import('@web/dev-server').DevServerConfig} */ ({
  ...baseConfig,
  open: '/',
  plugins: [...baseConfig.plugins, storybookPlugin({ type: 'web-components' }),],
});
```

And with mdjs files like this:

````md
```js script
export default {
  title: 'Getting started/Installation',
};
```

# Installation guide
...
````

I get the following error when running `npm run storybook`

```
Error while transforming packages/README.md: Unexpected token (7:0)

   5 | ```
   6 | 
>  7 | # Installation guide
```

I tried changing `server.mjs`'s plugins order to see if that was the cause like this:

```js
  plugins: [storybookPlugin({ type: 'web-components' }), ...baseConfig.plugins,],
```

But that resulted in the components not being upgraded due to the following error:

```
Uncaught TypeError: Cannot read property 'currentProxy' of undefined
    at new WebComponentHmr (runtime.js:95)
    at new UpdatingElement (updating-element.ts:514)
    at new LitElement (lit-element.ts:98)
    at new <anonymous> (SlotMixin.js:24)
    at new <anonymous> (DisabledMixin.js:24)
    at new <anonymous> (DisabledWithTabIndexMixin.js:29)
    at new LionButton (LionButton.js:164)
    at new SomeButton (SomeButton.js:18)
    at TemplateInstance._clone (template-instance.ts:95)
```

## Affected Versions
@open-wc/dev-server-hmr v0.1.0
@web/dev-server v0.1.3
@web/dev-server-storybook v0.3.2

**Comment by LarsDenBakker** [comment]
The storybook plugin should indeed come before the HMR plugin. I adjusted the generator to correct this.

I'm not able to reproduce the error you're seeing though. Can you show the MD file, storybook config and server config you're using?

**Comment by alangdm** [comment]
The MD file, storybook, and server config are basically what I added above, there's not many changes there

And I tried with the new generator and that seems to work, which stroke me as a bit odd

So, I delved a bit deeper and it seems the root of the problem is this:

- The project I'm working on has a lot of components that extend `@lion/*` components
- When inspecting the wcHmrRuntime, it seems that only the components that inherit `LitElement` directly are getting registered using the [`register` function](https://github.com/open-wc/open-wc/blob/master/packages/dev-server-hmr/src/wcHmrRuntime.js#L130)
- This means that all the other components aren't added to `keysForClasses` so in [this code block](https://github.com/open-wc/open-wc/blob/master/packages/dev-server-hmr/src/wcHmrRuntime.js#L92-L95) both `key` and `p` are `undefined` for every component that doesn't extend LitElement directly

I haven't been able to find where the register function is called in the first place but maybe the problem is on that side

**Comment by alangdm** [comment]
Update:
I tried importing `LitElement` from `@lion/core` rather than from `lit-element` and that made the error go away but now it seems that none of the components are being registered in the hmr runtime since changes done to the code only get reflected if I refresh the browser window

**Comment by daKmoR** [comment]
@alangdm on top of adding the litElement preset you will probably also need to add an additional baseClass 🤔

```js
  baseClasses: [
    // anything that extends a class called MyElement imported from 'my-element'
    { name: 'LitElement', import: '@lion/core' },
```

PS: just an idea - untested

**Comment by alangdm** [comment]
> @alangdm on top of adding the litElement preset you will probably also need to add an additional baseClass 🤔
> 
> ```js
>   baseClasses: [
>     // anything that extends a class called MyElement imported from 'my-element'
>     { name: 'LitElement', import: '@lion/core' },
> ```
> 
> See [docs](https://open-wc.org/docs/development/hot-module-replacement/#detecting-web-components)
> 
> PS: just an idea - untested

This seems to be part of the answer, just that, in order to get it working I had to manually add all the lion classes I was extending, not only `@lion/core`

Currently the config looks something like this:

```js
hmrPlugin({
        include: ['**/*/packages/**/*'],
        exclude: ['**/*/node_modules/**/*'],
        presets: [presets.litElement],
        baseClasses: [
          { name: 'LitElement', import: '@lion/core' },
          { name: 'LionButton', import: '@lion/button' },
          { name: 'LionCheckbox', import: '@lion/checkbox-group' },
          { name: 'LionCheckboxGroup', import: '@lion/checkbox-group' },
          // ... others
        ],
      }),
```

Is there a way of getting the plugin to recognize that all this classes extend `@lion/core` in the end?
I tried adding a '**/*/node_modules/@lion/**/*' to the includes but that didn't seem to do much

**Comment by LarsDenBakker** [comment]
We need some indication that a class is a webcomponent for HMR to work. We can only check per file, we can't check across files. Right now we can check whether a component extends a class, uses customElemnts.define or uses a specific decorator.

For the case of lion we can also add a way to check if a certain mixin (ScopedElements) is used.

**Comment by LarsDenBakker** [comment]
The code shouldn't throw an error if it can't detect a class properly, so that's something we need to look into as well.

**Comment by alangdm** [comment]
I've tried diving a bit deeper into the root of this problem and I think I've found it and maybe solved it so I tried making a PR for it https://github.com/open-wc/open-wc/pull/2051

**Comment by LarsDenBakker** [comment]
Good catch!
