### ISSUE TITLE
[dev-server-storybook] Various story elements are not rendered as expected

### ISSUE THREAD

**Issue by alangdm** [modernweb-dev/web#1178]
Hi there, I've been trying to migrate from `@open-wc/demoing-storybook` to `@web/dev-server-storybook` and I found a couple of cases where things are not rendered the same way as before:

## 1. Styling and features are missing in mdjs/mdx files

`demoing-storybook` used to add some nice default styles and functionality to elements such as headers and code blocks like this:
![Screen Shot 2021-01-06 at 14 00 04](https://user-images.githubusercontent.com/6799159/103731107-ba088800-5027-11eb-9ce2-4358e39e2867.png)

However, the current default doesn't seem to include either of them
![Screen Shot 2021-01-06 at 14 32 07](https://user-images.githubusercontent.com/6799159/103732982-fccc5f00-502b-11eb-90eb-d6dcf2d9b881.png)

Am I missing some configuration or are these just no longer supported?

## 2. Code blocks are rendered as `[object Object]` on first render in mdjs/mdx files

This is only on first render and seems to go away if you either change stories or change between the canvas/docs tabs, judging from the behavior, this might also happen with some other blocks

(The screenshot below shows how the same sample from above renders the first time)

![Screen Shot 2021-01-06 at 14 33 47](https://user-images.githubusercontent.com/6799159/103733091-42892780-502c-11eb-8ad9-977368591327.png)

## 3. Preview stories'  are set as 'no code available' on mdjs/js files but not on mdx files

I tried creating the same story on the three formats but the 'show code' button only showed for mdx files (both using the open-wc starter kit and migrating a project with existing mdjs stories)

**Comment by LarsDenBakker** [comment]
https://github.com/modernweb-dev/web/pull/1191 Fixes issue 1. and 2.. Looking into 3.

**Comment by LarsDenBakker** [comment]
Number 3 is a change between storybook v5 and v6. It works for MDX stories, but not for JS stories. I'm tracking this separately in https://github.com/modernweb-dev/web/issues/1178 as a new feature. Thanks for reporting!

**Comment by alangdm** [comment]
Awesome, thanks a lot for working on this so fast 🎉
