### ISSUE TITLE
Does not work with Rollup plugin node-resolve

### ISSUE THREAD

**Issue by CxRes** [modernweb-dev/web#1190]
I am using this plugin after node resolve plugin, however a node package in the html entry file is not being resolved.

Instead of resolving `@package/repo` as `node_modules/@package/repo/main`  it is resolved as `./@package/repo` despite @rollup/plugin-node-resolve being included before @web/rollup-plugin-html.

**Comment by daKmoR** [comment]
which plugins are you talking about? 🤔

in which order are they added? can you share your plugins array?
how does your html file look like?

**Comment by CxRes** [comment]
@daKmoR Like I said above (but as code):

Plugin: @web/rollup-plugin-html

plugins array:
```
import nodeResolve from '@rollup/plugin-node-resolve'
import html from '@web/rollup-plugin-html'

rollupOptions: {
  plugins: [
    input: './index.html',
    output: { dir: 'dist' },
    nodeResolve(),
    html(),
  ]
}
```

index.html (operative part):
```
<div><img src="@repo/program/image.gif"></div>
```

Error (I am paraphrasing the console output from what I can recall):
```
Unable to resolve D:/dev/program/src/@repo/program/image.gif
```

If it were using node resolve, it should have also searched `D:/dev/program/node_modules`

**Comment by LarsDenBakker** [comment]
The rollup plugin hooks act only on js module and module imports, it's not possible to pass an image path like that to rollup. Besides that, references to resorces in HTML does not have a concept of bare imports.

For example these are equivalent:

```html
<script type="module" src="foo"></script>
<script type="module" src="./foo"></script>
```

It's only in a module import where the bare import has special meaning:

```html
<script type="module>
  import 'foo';
</script>
```

**Comment by CxRes** [comment]
@LarsDenBakker Thanks for that good explanation. I think I was left confused with import maps which, as you explain, do not work raw URLs..
