### ISSUE TITLE
[dev-server] Group testing does not wait for shadowRoot content

### ISSUE THREAD

**Issue by lmadueno10** [modernweb-dev/web#1195]
I'm trying to access the innerHTML of the wc "navbar-nv2" that is inside the shadowRoot of the wc "listproducts-nv2" however there are two different behaviors for the same test:

1. When I run all the tests I receive an error message "Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

2. But when I run the test individually it actually returns the content of shadowRoot to me and I can verify it in the console.

Although I am waiting for the fixture and for the component inside the shadowRoot using waitUntil. This is a bug that according to the documentation should wait using fixture/waitUntil.

![webcomponent](https://user-images.githubusercontent.com/64743098/104133433-8c864c00-5351-11eb-9b2c-ae8ac4edb748.PNG)
![testing](https://user-images.githubusercontent.com/64743098/104133374-3b765800-5351-11eb-9367-297399662b97.PNG)

**Comment by LarsDenBakker** [comment]
Your issue is labeled as dev server, but the screenshots are showing karma for which we don't do anything in modern web.

It's hard to say anything without more information, but it sounds like an issue in your tests or component code.

**Comment by lmadueno10** [comment]
Thank you very much for your answer Lars, I understand your observation, basically I want to test a component that includes several components inside, when I run the independent test it doesn't present any major problem, however when I run all the tests it generates an error and returns the shadowRoot blank. 

![webcomponentev2](https://user-images.githubusercontent.com/64743098/104140538-c53d1a00-537f-11eb-8a45-77c9ae07d02a.PNG)
![component](https://user-images.githubusercontent.com/64743098/104140579-0c2b0f80-5380-11eb-8935-c49889ddaf82.PNG)

**Comment by LarsDenBakker** [comment]
Which of our packages do you think there is an error?

**Comment by web-padawan** [comment]
Closing as invalid.
