### ISSUE TITLE
[test-runner] manual test invocation doesn't work for HTML test

### ISSUE THREAD

**Issue by rhashimoto** [modernweb-dev/web#1201]
I am attempting to create an HTML test as instructed [here](https://modern-web.dev/docs/test-runner/writing-tests/html-tests/).

If I invoke the test runner with `yarn web-test-runner --puppeteer` the HTML test seems to work properly. However, if I use `yarn web-test-runner --manual` and click on the HTML test link then the browser complains with:

> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
> TypeError: Failed to fetch dynamically imported module: http://localhost:8000/sample.test.html?wtr-manual-session=true

I believe that the manual invocation is attempting to load the HTML test as if it were a Javascript file.

I created a simple project to reproduce the issue [here](https://github.com/rhashimoto/web-test-runner-manual-html).

**Comment by LarsDenBakker** [comment]
Thanks for reporting. Indeed we're missing support for HTML tests when doing manual testing.
