### ISSUE TITLE
[test-runner] filterBrowserLogs not working after upgrading to 0.12.0

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1203]
Hi, seems like WTR option `filterBrowserLogs` stopped working for me after upgrading to 0.12.0

I have the following configuration to ignore some of the `console.warn` logs:

```js
filterBrowserLogs: (log) => log.type === 'error'
``` 

After upgrading to 0.12.0 it no longer hides warnings: 
https://github.com/web-padawan/components-monorepo/runs/1673168315

Previous run (0.11.x) - no warnings
https://github.com/web-padawan/components-monorepo/runs/1670255389

**Comment by LarsDenBakker** [comment]
Looks like we flipped the return value of the function, so it was working the other way around. Fixed it now.
