### ISSUE TITLE
Coverage seeks for files locally while they are served via localhost

### ISSUE THREAD

**Issue by ambrt** [modernweb-dev/web#1212]
I run web-test-runner with --coverage --watch.
Test goes according to spec.

Problem is when i want to have coverage.
The reporter is seeking source file in local path:
`Error: ENOENT: no such file or directory, open '/home/user/Desktop/Dev/Svelte/shell-snowpack/snow-code/src/Comp.svelte.js.map` 

I can confirm that this file is served via `localhost:8000/src/Comp.svelte.js.map`
(These are generated dynamically)

How can i point Istanbul to seek for those file on localhost instead of on physical drive?

**Comment by LarsDenBakker** [comment]
We run istanbul after we run the tests, so we need to check if it's possible to fetch those files from the server again.

**Comment by LarsDenBakker** [comment]
I found a way to do this, working on implementing this.

**Comment by LarsDenBakker** [comment]
This is now fixed in https://github.com/modernweb-dev/web/pull/1221
