### ISSUE TITLE
[test-runner-cli] inconsistent/unleaclear behaviour when using a custom config

### ISSUE THREAD

**Issue by Pieterv24** [modernweb-dev/web#123]
Im making this issue cause I've made a few observations when using custom config files, as opposed to the `web-test-runner.config`.
I would like to bring these to the attention and discus what (if anything) should be done about it.

### issues with node version and dynamic imports
I've made the observation that in the lts version of node(v12). when you try to use the following config.
```js
export default {
    concurrency: 10
}
```
the config file is not loaded into the config.
This is is believe do to the no availibility of esm in v12 so it uses cjs, however this throws an error while reading esm syntax it seems.

this is however not communicated with the user, so instead of an error, the config just gets set to {} and all config made by the user is voided.

My proposal for this is to either improve documentation about this, or expand error handling in this regard.

### issues with mjs, cjs and js extensions
when using a .js file with esm syntax in combination with node v14.
You get the error `unknown symbol 'export'`
This error disappears when the extension is changed to .mjs

This requirement/quirk seems inconsistent to me, I would propose clearer documentation about this, or a change in the way esm or cjs gets selected for reading the config file.

**Comment by LarsDenBakker** [comment]
The goal of the configuration reading is to follow node's handling of es modules and common js modules:

On versions of node that don't support es modules (v10 and earlier versions of v12), everything is loaded as commonjs. 

On versions of node that do support es modules, `.cjs` files will be loaded as a common js module and `.mjs` files will be loaded as es modules. `.js` files will be loaded based on the `type` field in the package json. If there is no type, it is loaded as commonjs. If there is `type="module"` it is loaded as an es module.

I'm not 100% sure of the behavior of modules in v12, and I think they changed the default behavior somewhere along the way. I would expect it to throw in your scenario. Which versions of v12 are you on?

**Comment by Pieterv24** [comment]
Thanks for the clarification,
I posted the issue due to me having issues getting this to work without knowing why It didn't work until I started digging in the code.

I was using node `v12.16.2`

**Comment by LarsDenBakker** [comment]
On closer inspection, it looks like we're swallowing all errors in some cases. Will update it to have clearer error messages.
