### ISSUE TITLE
"0 failed" should not be red

### ISSUE THREAD

**Issue by hmans** [modernweb-dev/web#1234]
This is mostly about ergonomics. It'd be a simple change, but I wanted to check in on how the maintainers feel about this before submitting a PR.

Currently, when there are zero test failures, test-runner will report it like this:

![image](https://user-images.githubusercontent.com/1061/105971935-5c49e780-608b-11eb-85fd-6ccf92a4ea06.png)

Red is a signal color that indicates failure. When there are 0 failures, two things happen:

- The text being red will startle users like myself who understand "red" as a color signaling failure (seriously, it can't be just me?)
- I now have to check if the number is "0". Yes, I know that if there had been actual failures, the output would look very different, but they're called signal colors for a reason. :)~

This is why I suggest to change the test output code so it only uses the red color when there have actually been failures. Without failures, the "0 failures" string should simply use the default color.

The change would be made [here](https://github.com/modernweb-dev/web/blob/d07c4c20ce58ceca43e39db0867843ceaa883f25/packages/test-runner/src/reporter/getTestProgress.ts#L39-L41), and I'm happy to submit a PR if this change is wanted.

**Comment by LarsDenBakker** [comment]
Makes sense, if you can make the change that would be great :)

**Comment by hmans** [comment]
Alright, I'm on it!

**Comment by LarsDenBakker** [comment]
Added in https://github.com/modernweb-dev/web/pull/1235
