### ISSUE TITLE
lit-element @customElement decorator fails to load the webcomponent during test

### ISSUE THREAD

**Issue by hegsie** [modernweb-dev/web#1250]
Your Example project lit-element-ts-tsc if you remove the top level my-element.ts class and instead use the @customElement decorator on the actual class the test can't load the web component (shadowRoot is missing after the load).

**Comment by LarsDenBakker** [comment]
We need more information help you find what's wrong. Why do you think it's an issue with the test runner? What kind of error do you see?  Did you check the browser logs?

**Comment by hegsie** [comment]
I've forked the repo and updated to use the decorator, and once we do you can see the shadowRoot never gets loaded  https://github.com/hegsie/example-projects/tree/master/lit-element-ts-tsc

**Comment by LarsDenBakker** [comment]
In that example the component is never defined anywhere.

**Comment by hegsie** [comment]
The @CustomElement decorator defines the component, you can see the definition below...

`const standardCustomElement =
    (tagName: string, descriptor: ClassDescriptor) => {
      const {kind, elements} = descriptor;
      return {
        kind,
        elements,
        // This callback is called once the class is otherwise fully defined
        finisher(clazz: Constructor<HTMLElement>) {
          window.customElements.define(tagName, clazz);
        }
      };
    };`

but for some reason the decorator doesn't work in the unit testing, it works fine during actual use in a chrome browser.

**Comment by LarsDenBakker** [comment]
I know about the decorators, but it's not applied in the project: https://github.com/hegsie/example-projects/blob/master/lit-element-ts-tsc/src/MyElement.ts

**Comment by hegsie** [comment]
Apologies, I committed the incorrect version its updated now.

**Comment by LarsDenBakker** [comment]
The issue here is in TSC, it doesn't detect that the customElement decorator has a side effect. Since you only import the type from the module, TSC removes the import after stripping types and the element doesn't get registered. You can fix this by splitting the type import and the side effect import:

```ts
import type { MyElement } from '../src/MyElement';
import '../src/MyElement';
```

**Comment by hegsie** [comment]
Great thankyou for explaining, do you think this is a problem with TSC or just a feature?

**Comment by LarsDenBakker** [comment]
I think it's a "feature" in TSC.

**Comment by hegsie** [comment]
Thanks for the help @LarsDenBakker
