### ISSUE TITLE
[web-test-runner]: `SyntaxError: The requested module lodash does not provide an export named 'once'`

### ISSUE THREAD

**Issue by dsadhanala** [modernweb-dev/web#1266]
I'm running into below error while running `web-test-runner` in a monorepo, using rushjs and pnpm. This is causing module import failed during test run.
I have attached stack trace screenshot from the browser, below for your reference, let me know if you need any additional information.

Can you please help me find the root cause of this failure?

```
🚧 Browser logs:
      SyntaxError: The requested module '/__wds-outside-root__/2/common/temp/node_modules/.pnpm/lodash@4.17.20/node_modules/lodash/lodash.js' does not provide an export named 'once'

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information.
```

![image](https://user-images.githubusercontent.com/5795823/107107473-0b05ca80-67e6-11eb-8d06-e64c4f4a0a12.png)

```JS
import { esbuildPlugin } from '@web/dev-server-esbuild';
export default {
    plugins: [esbuildPlugin({ ts: true })],
    nodeResolve: true,
};
```

**Comment by LarsDenBakker** [comment]
The error is correct, `lodash/lodash.js` does not contain any es module exports: https://unpkg.com/browse/lodash@4.17.20/lodash.js it's a commonjs module which is specific to node js.

You can use the `lodash-es` package which does work in the browser: https://unpkg.com/browse/lodash-es@4.17.20/once.js

I recommend importing `lodash-es/once.js` so that you don't pull in all of lodash.

**Comment by dsadhanala** [comment]
Thanks for looking into this, I'll double check our modules, I thought that lodash might be included in WTR or it's dependencies. It sounds like WTR not using it, so might be one of our 3p package might be pulling in. Sorry for the false alarm. Once I validate from my side, I'll close this.

Thanks again for your time!

**Comment by dsadhanala** [comment]
I'm keep hitting issues caused by core-js imports as they are CJS modules, some reason es-build having trouble transpiling these modules. So closing this for now, as I'm look into other alternatives.
