### ISSUE TITLE
[RFC] [Test Runner] "sendKeys" command for Playwright

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#1289]
A `sendKeys` plugin for `@web/test-runner` _could_ be so simple as:
```
import type { Page } from 'playwright';

export function sendKeysPlugin() {
    return {
        name: 'send-keys-command',
        async executeCommand({
            command,
            payload = {},
            session,
        }: {
            payload: { type?: string; press?: string };
            command: string;
            session: {
                id: string;
                browser: { type: string; getPage: (id: string) => Page };
            };
        }) {
            if (command === 'send-keys') {
                // handle specific behavior for playwright
                if (session.browser.type === 'playwright') {
                    if (payload.type) {
                        const page = session.browser.getPage(session.id);
                        await page.keyboard.type(payload.type);
                        return true;
                    } else if (payload.press) {
                        const page = session.browser.getPage(session.id);
                        await page.keyboard.press(payload.press);
                        return true;
                    }
                }
                // you might not be able to support all browser launchers
                throw new Error(
                    `Sending keys is not supported for browser type ${session.browser.type}.`
                );
            }
            return false;
        },
    };
}
```

Here a single approximates the [`Keyboard` class](https://playwright.dev/docs/api/class-keyboard) and suggests the ability to more fully cover it the remaining `down`, `insertText`, and `up` interfaces by expanding the `payload` to optionally accept properties describing the values to send those methods. A "complete" rendering of this interface would also allow for an `options` bag as accepted by the `press` and `type` methods.

Initial questions regarding that are:
1. If we cover all of the `Keyboard` interface, should we rename the plugin `keyboardPlugin` to make the relationship between it and the Playwright API more clear?
2. Does the `payload` relationship to the interface on `Keyboard` make sense, or if there are better path to supporting the various capabilities there?
3. Is there context where individual `keyboardPressPlugin`, `keyboardInsertTextPlugin`, etc. would be more productive than this full `Keyboard` class implementation?
4. Is Playwright coverage alone enough? Or is it better to have Puppeteer in the same plugin? Should they each have a purpose built plugin of their own?

**Puppeteer**
The Puppeteer API also surfaces a [`Keyboard` class](https://pptr.dev/#?product=Puppeteer&version=v5.1.0&show=api-class-keyboard) with a _similar_ API:
- keyboard.down(key[, options]) // matched with addition of options bag
- keyboard.press(key[, options]) // matched
- keyboard.sendCharacter(char) // send `keypress` and `input` events that I'm not even sure what the real use parallel to which would be and is one more event (`keypress`) than the `insertText` API for Playwright.
- keyboard.type(text[, options]) // matched
- keyboard.up(key) // matched 

## Code format
We structure a lot of our tools in CJS + esm, would we want to persist that here or has the community (Node@12) gotten to a place where we could go esm only on this? 

## Code location
After we get closer on the structure of the plugin, it'll be useful to spend a little thought on where the code should live. If this is the _only_ plugin we ever vend, it makes sense to live in this repo. If we end up vending a LOT of plugin, then it's possible that these should live elsewhere, which may be a problem for another time? 

**dir**
Possible directories for the plugin:

`packages/test-runner-plugin-keyboard`
`packages/test-runner-plugin-keyboard-playwright`
`packages/test-runner-plugin-keyboard-puppeteer`
`packages/something-else`

In the case we want to separate the plugins in somewhat but don't want another repo, would could expand into an additional workspace beyond `packages`, e.g.:

`plugins/test-runner-plugin-keyboard`
`plugins/test-runner-plugin-keyboard-playwright`
`plugins/test-runner-plugin-keyboard-puppeteer`
`plugins/something-else`

**Package name**
How will we want to vend this (and other) plugin(s)?

`@web/test-runner-plugin-keyboard`
`@web/test-runner-plugin-keyboard-playwright`
`@web/test-runner-plugin-keyboard-puppeteer`

Does it matter much that the name is quite long?

**Comment by LarsDenBakker** [comment]
What about making this part of the commands package? We already exports a few plugins from it, and this seems generic enough for that as well.

**Comment by Westbrook** [comment]
Definitely makes sense. Would that increase the need to support more tools than Playwright?

If so, Would that and Puppeteer be enough?

That as a location feel like enough to get a more formal PR together for discussion against the actual API, etc.
