### ISSUE TITLE
[dev-server-storybook] Can't use @storybook/addon-essentials

### ISSUE THREAD

**Issue by reutopiaer** [modernweb-dev/web#1309]
Error: [@web/dev-server-storybook] Official storybook addons are not es modules, and cannot be loaded from this storybook 
implementation.

``` js
// .storybook/main.js
module.exports = {
  addons: ['@storybook/addon-essentials'],
  stories: ['../**/out-tsc/stories/*.stories.{js,md,mdx}'],
};
```
I know is addon-essentials's problem，but what can I do if I want use stroybook addons with dev-server?
Can someone help me? Thanks in advance！

**Comment by LarsDenBakker** [comment]
The essentials addon is already added by default. Other addons cannot be loaded, until storybook itself supports loading in the browser without transformation this will always be the case unfortunately.
