### ISSUE TITLE
[web-dev-server] node-resolve does not work with internal imports (while rollup works)

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#1321]
You can find a repo with the code here: https://github.com/daKmoR/bug-node-resolve-internal

Having in my `package.json`

```js
"scripts": {
  "start": "web-dev-server --node-resolve --open"
},
"imports": {
  "#internal": "./internal.js"
},
```

Usage

```js
import { foo } from "#internal";

console.log(foo);
```

### Expected Behavior

Be able to import `#internal`.

### Actual Behavior

Throws Error

```
Error while transforming app.js: Could not resolve import "#internal".

> 1 | import { foo } from '#internal';
    |                     ^
```

## NOTE:

This works fine when using rollup directly and it produces the following output:

```js
"use strict";

const foo = "foo";

console.log(foo);
```

**Comment by MathieuPuech** [comment]
https://github.com/modernweb-dev/web/blob/eb99f931c5ce455173759f4f4821fbf707b9169f/packages/dev-server-rollup/src/rollupAdapter.ts#L140
resolvableImport should be #internal but it is an empty string. in importSuffix you have #internal
