### ISSUE TITLE
const { createPolyfillsLoader } = require('@web/polyfills-loader'); doesn't provide function

### ISSUE THREAD

**Issue by ghost** [modernweb-dev/web#1324]
According to the documentation this:
const { createPolyfillsLoader } = require('@web/polyfills-loader');
Should give the function createPolyfillsLoader .
But it seems missing:
TypeError: createPolyfillsLoader is not a function

**Comment by cranphin** [comment]
Note that if this was an intentional choice (to not expose createPolyfillsLoader ), I would actually very much like createPolyfillsLoader to be available :)

**Comment by LarsDenBakker** [comment]
It's not exported currently, but we can accept a PR that adds it.
