### ISSUE TITLE
Test runner does not accept exclude options properly

### ISSUE THREAD

**Issue by GeorgeTailor** [modernweb-dev/web#1342]
Hello all,

there are a couple of issue with web-test-runner. My config is as follows:
```
coverageConfig: {
	report: true,
	reportDir: 'test-coverage',
	threshold: {
		statements: 20,
		branches: 20,
		functions: 20,
		lines: 20,
	},
	exclude: [
		'**/*/_snowpack/**/*',
		'**/*.test.tsx'
	],
}
```

First issue is that the exclude pattern is strange and you have to blindly try out different pattern to get it right.
`'**/*/_snowpack/**/*',` works for some reason, while `'**/*.test.tsx'` does not. Test files are included in the coverage.

Other issue relate to css being imported in js, but I guess it would be better to open a separate issue for that.

**Comment by GeorgeTailor** [comment]
The issue is probably related to sourcemap generation,
adding `'**/*.test.js' to the exclude array solves it. But still, there's a lot of guessing to be done, as it is not documented anywhere and the behaviour is less than predictable.

**Comment by LarsDenBakker** [comment]
There is indeed an intuitive mismatch between what you input in snowpack, and what the browser sees. It's unfortunate that snowpack rewrites the paths in my opinion, we could add some snowpack specific docs perhaps...
