### ISSUE TITLE
Test runner coverage includes files like *.css.proxy.js

### ISSUE THREAD

**Issue by GeorgeTailor** [modernweb-dev/web#1343]
For some reason web-test-runner places files like `myComponent.css.proxy.js` in the final coverage report. But when trying to open that file I get the following error:
```
Unable to lookup source: */frontend/_dist_/common/IconCommon.css.proxy.js (ENOENT: no such file or directory, open '*/frontend/_dist_/common/IconCommon.css.proxy.js')
```
One way to "fix" it is to add it to exclude options, but why such files are in the coverage report in the first place?

**Comment by Westbrook** [comment]
Can you share the config with which you are running you tests? It _seems_ like you might be attempting to leverage hot module reloading in your test suite, which is likely not what you meant here. And, if that isn't the case, your config may help to point to whatever else might be going on here.

**Comment by GeorgeTailor** [comment]
sure, `web-test-runner.config.js`:
```
process.env.NODE_ENV = 'test';
module.exports = {
	plugins: [require('@snowpack/web-test-runner-plugin')()],
	coverage: true,
	coverageConfig: {
		report: true,
		reportDir: 'test-coverage',
		threshold: {
			statements: 20,
			branches: 20,
			functions: 20,
			lines: 20,
		},
		exclude: [
			'**/*/_snowpack/**/*',
			'**/*.test.js',
		],
	},
};
```
and in `package.json`:
```
"test": "web-test-runner ./src/**/*.test.tsx --coverage --port 1234"
```

while hot module replacement is commented out in `index.tsx`:
```
// if (import.meta.hot) {
//   import.meta.hot.accept();
// }
```

**Comment by Westbrook** [comment]
Interesting.

Do you have `"sourceMap": true,` on in your `tsconfig.json`?

There's very little that WTR is doing in you config, which makes me wonder if this is part of how Snowpack's plugin is supposed to work. However, I've never used it to say.

**Comment by GeorgeTailor** [comment]
nope, `"sourceMap": true"` is not present in our `tsconfig.json`.
However, this option is supplied in `snowpack.config.js`. But even when I disable it, the result is the same in terms of including that `*.css.proxy.js`, but disabling that option also breaks the file view. It cannot be found. Example attached 
<img width="626" alt="Screenshot 2021-03-12 at 13 46 22" src="https://user-images.githubusercontent.com/6958936/110942041-8274cf80-8339-11eb-9bdd-a3c437ffc2fc.png">

**Comment by Westbrook** [comment]
Sorry, I was asking to make sure it was set to `true`. Wanted to confirm that it wasn't giving you this `.proxy.css` file because there wasn't actual source map data to get you to the original file.

With this information, I'm not sure what else to do from the outside. It feels a bit like this is actually an issue of the `@snowpack/web-test-runner-plugin`, which we do not vend. You may want to bring this question up on their issues/discussion boards. If you are able to provide a minimal repro case, we can investigate further.
