### ISSUE TITLE
[test-runner] Allow config options for istanbul reporters in coverageConfig

### ISSUE THREAD

**Issue by krshnpatel** [modernweb-dev/web#1350]
Currently, I'm not able to set [config options](https://github.com/istanbuljs/nyc/blob/91ae8b8764cef361fe6add31ae0802dc221fb577/index.js#L458-L461) for istanbul reporters in the `reporters` property of `coverageConfig`. It would be great if we can add a config option like `skipEmpty: false`.

```js
// web-test-runner.config.mjs
export default {
  coverageConfig: {
    report: true,
    reportDir: 'coverage',
    reporters: [
      { name: 'html', skipEmpty: false } // desired config option
    ],
  }
};
```

**Comment by jbuckner** [comment]
I'm also interested in this. GitLab only supports the Cobertura XML format so I'd like to be able to output that.

**Comment by jbuckner** [comment]
So apparently the option already exists, it's just not documented. Here's the [pull request](https://github.com/modernweb-dev/web/pull/1200) from January that added it.

**Comment by krshnpatel** [comment]
> So apparently the option already exists, it's just not documented. Here's the [pull request](https://github.com/modernweb-dev/web/pull/1200) from January that added it.

I believe that PR adds the option to use different types of reporters (i.e. 'text', 'html') but I want to be able to configure those reporters so I can set `skipEmpty` or `skipFull` as config options.

Currently, you can only do this:
```js
coverageConfig: {
    report: true,
    reportDir: 'coverage',
    reporters: [ 'html', 'text' ], // <--- only accepts array of strings with no config options
}
```

I'm looking for this:
```js
coverageConfig: {
    report: true,
    reportDir: 'coverage',
    reporters: [
      { name: 'html', skipEmpty: false, skipFull: true }, // <--- allows config options per reporter
      { name: 'text', skipEmpty: true },
    ],
}
```

**Comment by jbuckner** [comment]
Ahh my misunderstanding!

**Comment by krshnpatel** [comment]
I added these options to my forked project but didn't find it useful in terms of what I wanted to achieve. Closing this issue.
