### ISSUE TITLE
[dev-server] [bug] node resolve issue

### ISSUE THREAD

**Issue by AliMD** [modernweb-dev/web#1355]
There seems to be an issue with file extensions after the update to v0.1.x

Code Example:

```javascript
import { html } from 'lit-html';
import { ifDefined } from 'lit/directives/if-defined';
import { repeat } from 'lit-html/directives/repeat';
```

Output `@web/dev-server` `v0.0.29` :

```javascript
import { html } from './../../lit-html/lit-html.js';
import { ifDefined } from './../../lit/directives/if-defined.js';
import { repeat } from './../../lit-html/directives/repeat.js';
```

Output `@web/dev-server` `v0.1.0` ~ `v0.1.8` :

```javascript
import { html } from './../../lit-html/lit-html.js';
import { ifDefined } from './../../lit/directives/if-defined';
import { repeat } from './../../lit-html/directives/repeat';
```

I don't understand why `... from 'lit-html'` transpiled to `... lit-html/lit-html.js` but `directives/if-defined` not !

I think its about `"@rollup/plugin-node-resolve": "^11.0.0"`, could ypu please back to `~10.0.0`

**Comment by LarsDenBakker** [comment]
Are you using the prerelease of lit-html? It likely uses an export map, so the classic node resolution does not apply. Either you need to use file extensions, or ask to add file extension support in the export map of lit-html. See https://nodejs.org/api/packages.html#packages_package_entry_points

**Comment by AliMD** [comment]
@LarsDenBakker Thank you
But why its works with `"@rollup/plugin-node-resolve": "^10.0.0"` ?
Im sorry to ask this question here but What is the best practice for these situation? its not better to work like `v0.0.29`?

**Comment by daKmoR** [comment]
earlier versions of `@rollup/plugin-node-resolve` did not respect package entry points so you could import anything from any package.

Package entry points are a very important step to keep packages maintainable as it allows to refactor code without a breaking change.

You can read some more at the blog post here: https://lion-web.netlify.app/blog/controlling-exports/

lit-next does not set specific entry points for its directives.. it's a directory/star entry point
```json
    "./directives/": {
      "development": "./development/directives/",
      "default": "./directives/"
    },
```

so with
```js
import { ifDefined } from 'lit/directives/if-defined';
```

the following happens
1. `lit/directives/` becomes `/url/to/node_modules/lit/directives/`
2. it adds the remaining parts => `/url/to/node_modules/lit/directives/if-defined`
3. the browser tries to load the URL => does not exist

If you use
```js
import { ifDefined } from 'lit/directives/if-defined';
```

the following happens
1. `lit/directives/` becomes `/url/to/node_modules/lit/directives/`
2. it adds the remaining parts => `/url/to/node_modules/lit/directives/if-defined.js`
3. the browser tries to load the URL => does exist

## conclusion

with package entry points lit-html can now enforce how it wants to be imported and it currently enforces you to use 

```js
import { ifDefined } from 'lit/directives/if-defined.js';
```

I personally would prefer imports like
```js
import { ifDefined } from 'lit/directives/if-defined';
```

This however would mean that `lit-html` will need to add the following entry into its export map in the package.json

```json
    "./directives/if-defined": {
      "development": "./development/directives/if-defined.js",
      "default": "./directives/if-defined.js"
    },
```

**Comment by AliMD** [comment]
@daKmoR Thank you very much 😘
