### ISSUE TITLE
[dev-server] Page loading freezes Chrome

### ISSUE THREAD

**Issue by lpellegr** [modernweb-dev/web#1364]
I am trying to move from _es-dev-server_ version 1 to _web-dev-server_.

Using _web-dev-server_ version 0.1.10 and opening an open-wc application with _Chome_ 89.0.4389.90, page loading freezes and _Chrome_ asks whether to wait or close the page after some seconds. There are no errors or warnings in the console. What is weird is that if I open the Network tab before loading the main app page, I can see that a lot of scripts remain with a pending status:

![Screenshot from 2021-03-17 00-54-51](https://user-images.githubusercontent.com/128898/111394847-d37b1f80-86bb-11eb-8c38-287a2c4fcabc.png)

The same flow using Firefox works perfectly. This lets me think that what I experience is maybe a Chrome bug. Maybe you already encountered such a problem? an idea if this is a misconfiguration from me about web-dev-server?

The command line used to run the server is the following:

```
yarn sass-render src/**/*.scss -q && concurrently --kill-others --names sass-render,tsc,web-dev-server "yarn sass-render 'src/**/*.scss' -qw" "yarn tsc:watch" "wds --config web-dev-server.mjs"
```
and the definition for _web-dev-server.mjs_:

```
export default /** @type {import('@web/dev-server').DevServerConfig} */ ({
    appIndex: 'index.html',
    nodeResolve: true,
    open: '/',
    port: 8080,
    watch: true,
});
```

**Comment by LarsDenBakker** [comment]
It's hard to say what can be the cause based on this. It sounds like an issue in chrome perhaps, but it's odd that this doesn't happen when using es-dev-server. What kind of configuration/flags were you using with es-dev-server? Is it possible to test this without sass and TSC and just the dev server?

**Comment by lpellegr** [comment]
Unfortunately, I cannot reproduce on a minimal example. 

The issue started when upgrading from es-dev-server version 1. 

The configuration used is the one shared in the issue description. Nothing more.

I tried bypassing the service worker, unsing incognito mode, disabling cache, nothing helps with Chrome. 

If I copy as cURL command the request used for a pending resource and try to execute the command in a shell, the resource is returned with no problems.

Testing the same thing on Epiphany browser (Gnome Web) that is based on Webkit make even crash the webkit process "WebkitWebProcess crashed".

It looks like the issue is affecting all Webkit based browsers. However, the issue happens only when loading ES modules directly in development mode. When the app is bundled, the issue disappear. Also the problem does not happen on Firefox.

Based on this experience, I looks like a Chrome bug but it's hard to say if this is due because of an unexpected answer from @web/dev-server.

**Comment by lpellegr** [comment]
Running dev server without tsc watch and sass as follows `./node_modules/@web/dev-server/dist/bin.js --node-resolve --watch --open` changes nothing.

**Comment by lpellegr** [comment]
@LarsDenBakker Running dev server in debug, it seems that resources that remain in pending state in Chrome are served from plugin transform cache. Do you know what is this cache? is there a way to disable it?

> [web-dev-server] Receiving request: /node_modules/lodash-es/_unicodeSize.js
> [web-dev-server] Serving cache key "/node_modules/lodash-es/_unicodeSize.js" from plugin transform cache

**Comment by lpellegr** [comment]
Is there a limit on the number of parallel requests dev-server accepts?

**Comment by LarsDenBakker** [comment]
No that I know of, koa should handle this properly since it's also used for production servers. 

Is it possible to create a project that uses the same dependencies, so that it can be debugged easily?

**Comment by lpellegr** [comment]
Unfortunately, the project includes several private dependencies. I tried to reproduce on a minimal project but without success until now. I suspect the issue happens when many requests are made due to a large project. In the present case, the project where the issue happens triggers 1099 requests on Chrome before freezing. All are mainly requests to js files.

**Comment by rbjarnason** [comment]
I also have the same problem on Chrome - loads a bunch of files then just hangs -works on Firefox. 

![Screenshot from 2021-05-09 03-40-48](https://user-images.githubusercontent.com/43699/117559863-7034ba80-b078-11eb-8fcc-c818f395fa97.png)

**Comment by rbjarnason** [comment]
Happens in two of our open-source apps here is a simpler one: https://github.com/CitizensFoundation/community-scorecard

**Comment by lpellegr** [comment]
@rbjarnason Thanks for sharing this. I was trying to run your project to see if I find similarities with my private project. However, I am getting errors when running `yarn start`. Could you please share the commands and node version you are using to launch the app?

**Comment by rbjarnason** [comment]
This is project is still in development - will be launched in July. But to start the API server you need to:
* Create an empty Postgres database
* Copy /api/config/config.json.dist into /api/config/config.json
* Edit  /api/config/config.json with Postgres user and db name. 
* Run yarn install
* Run yarn start and the script will create the database and seed it with some test content

Then in /cs-web-app/ you can do _npm i_ and _npm run start_ to replicate our problem.

**Comment by rbjarnason** [comment]
@lpellegr @LarsDenBakker I tried removing lodash-es from the code and commenting out the functions and now it loads in Chrome, quickly. I will investigate further.

**Comment by lpellegr** [comment]
@rbjarnason Thanks a lot for your finding. I confirm the issue was also caused by `lodash-es` on my side. Removing the dependency resolves the issue.

I still cannot reproduce in a minimal open-wc example using lodash-es functions only. Also, this does not explain why the issue is affecting Chrome only and not Firefox. All that to say we don't know what the exact problem is nor whether modernweb-dev server is related to this issue. However, since we have a workaround, I am closing the issue.

**Comment by jonmann20** [comment]
I'm also experiencing browser tab crashes.  Seems to happen after several quick saves in a row that the browser hangs.  I also updated from es-dev-server to web-dev-server.

**Comment by jonmann20** [comment]
Still having issues with the browser hanging.  In particular it was happening almost every refresh when using websockets (graphql-ws).  I've had to turn off `--watch` for now to make things usable again.

Maybe adding an option to ignore certain watched files would help?  (I'm assuming `node_modules` are already ignored)

**Comment by jimsimon** [comment]
I'm also experiencing this, though it's happening without watch mode enabled. We're also using `graphql-ws`. 

@jonmann20 Did you ever figure out what was going on?

**Comment by jonmann20** [comment]
> I'm also experiencing this, though it's happening without watch mode enabled. We're also using `graphql-ws`. 
> 
> @jonmann20 Did you ever figure out what was going on?

nope

**Comment by cristinecula** [comment]
I had the exact same [browser hang issue](https://github.com/modernweb-dev/web/issues/2616), but it seems to have been resolved in the latest chrome version (v123).
