### ISSUE TITLE
[dev-server] No CORS options

### ISSUE THREAD

**Issue by ykant** [modernweb-dev/web#1367]

**Comment by LarsDenBakker** [comment]
You can set CORS headers yourself using a middleware. You can write one yourself, or use https://www.npmjs.com/package/@koa/cors

**Comment by tstewart-klaudhaus** [comment]
The old es-dev-server project that this package superceded had a CORS option:

https://github.com/open-wc/es-dev-server#server-configuration

This made it simple to support the common dev situation of doing local development / testing of an app with a remote API without having to make a config module. The lack of it makes this package less ergonomic than its predecessor. It would be great to add it back in.

**Comment by LarsDenBakker** [comment]
We can pack the server with a lot of functionality by default, but this creates more work for us to maintain and locks us to a specific implementation. It's easy to drop in plugins and middleware, and this allows easily moving between different implementations.
