### ISSUE TITLE
SyntaxError: The requested module '@web/rollup-plugin-html' does not provide an export named 'default'

### ISSUE THREAD

**Issue by MikeVaz** [modernweb-dev/web#1415]
Probably an issue with docs when you follow instruction to 

`import html from '@web/rollup-plugin-html';`

It will break with an error message

```sh
SyntaxError: The requested module '@web/rollup-plugin-html' does not provide an export named 'default'
```

**Comment by btassone** [comment]
any solution? same error

**Comment by btassone** [comment]
Sigh... 

`import * as html from '@web/rollup-plugin-html';`

Worked for me. I love how I find my solutions every time AFTER posting. lmao.

**Comment by MikeVaz** [comment]
```js
import { rollupPluginHTML as html } from "@web/rollup-plugin-html";
```
