### ISSUE TITLE
Feature request: [web-test-runner] Set page url before test

### ISSUE THREAD

**Issue by hornta** [modernweb-dev/web#1420]
I have a component that looks on the current url and checks if a certain search parameter exist in the url and then uses it to perform an initial search. I've tried to set the url with location.search = ... men that interupts the test :-(

**Comment by LarsDenBakker** [comment]
You can use `window.history.pushState` or `replaceState` to change the URL without reloading the page.

**Comment by hornta** [comment]
@LarsDenBakker Thanks, that works. Too bad I have to restore the url after each test. Would be nice if that could be built into the test framework and we have some command for setting the url like the viewport or something.
