### ISSUE TITLE
faketimer

### ISSUE THREAD

**Issue by darkship** [modernweb-dev/web#1425]
Hi,

I have a hard time to make `sinon.useFakeTimers ` work in a `@web/test-runner` project. 

When I run `npm run test` with a faketimer, it just get stuck and it times out. No test success. 
With `--watch `, it seems to be stuck again but if you open the browser console, the test succeeded and it will time out again.

Demo repo : https://github.com/darkship/web-test-runner-faketimer

**Comment by LarsDenBakker** [comment]
Are you releasing the fake timers correctly? Some of the browser code is likely depending on timers, if they're not released the tests will hang forever.

**Comment by darkship** [comment]
Hi @LarsDenBakker ,
That was it.
Now I'm confused, I released the faketimer and removed the release afterwards -_-
