### ISSUE TITLE
[web-test-runner] plugin_node_resolve_1.nodeResolve on node 14 + .mjs config

### ISSUE THREAD

**Issue by btopro** [modernweb-dev/web#1443]
running node 14 and using `rollup.config.mjs` I was getting the following error: `plugin_node_resolve_1.nodeResolve`

In searching I was able to find that versions of https://www.npmjs.com/package/@rollup/plugin-node-resolve newer versions should resolve this config loading issue. In adding 13.0.0 to my package.json and running again it now correctly accepts the command. This seems an interrelated issues potentially as 

https://github.com/modernweb-dev/web/blob/master/packages/dev-server-storybook/package.json#L62
dev-server-storybook is pointed to 11.x.x.

Making this 13 (assuming that still works) should resolve this issue for those of us starting to use `.mjs` based configuration routines.

**Comment by Westbrook** [comment]
Very interesting. Could we interest you in making a PR with this change to `dev-server-storybook`?

**Comment by btopro** [comment]
to up this version? As long as it doesn't break anything else, absolutely. It was a very odd series of events so wasn't sure if this was really a bug or a series of unfortunate configurations.
