### ISSUE TITLE
Let me import a test setup file like Jest with setupFilesAfterEnv

### ISSUE THREAD

**Issue by hornta** [modernweb-dev/web#1486]
I feel like test-runner is missing the equivalent of Jests [setupFilesAfterEnv](https://jestjs.io/docs/configuration#setupfilesafterenv-array). I'm going to use https://mswjs.io/ and for that I need this framework to always be loaded.

**Comment by LarsDenBakker** [comment]
This is possible by importing those files in the HTML of the test page (you can set the test HTML from the config). But I think it makes sense to include an option of module to import as well.
