### ISSUE TITLE
[test-runner] Coverage not reported correctly and not failing when thresholds aren't met

### ISSUE THREAD

**Issue by jorenbroekema** [modernweb-dev/web#152]
Looks like coverage is not reported properly at the bottom of the terminal when running. 

![image](https://user-images.githubusercontent.com/36734656/86539553-bde31280-befd-11ea-8f1e-42156876389d.png)

Furthermore, when the coverage  thresholds aren't met, my test-runner is still succeeding. The average coverage is correct.

```sh
wtr test/components/*.test.js --puppeteer --coverage
```

Using:
- test-runner v0.5.20
- test-runner-puppeteer v0.4.4 
- node v14.4.0

web-test-runner.config.mjs:
```js
export default {
  coverageConfig: {
    report: true,
    reportDir: 'test-coverage',
    thresholds: {
      statements: 70,
      branches: 60,
      functions: 80,
      lines: 70,
    },
  },
};
```

I've tried playing with the thresholds, but nothing seems to make a difference, even if I put them all to 100.
My test-coverage folder gets created properly, and the results look correct (statements, branches, functions, lines, it's all there)

**Comment by jorenbroekema** [comment]
Reopening since my tests are still not failing when coverage thresholds are not met:

web-test-runner.config.js:
```js
module.exports = {
  nodeResolve: true,
  coverageConfig: {
    report: true,
    reportDir: 'test-coverage',
    thresholds: {
      statements: 90,
      branches: 90,
      functions: 90,
      lines: 90,
    },
  },
};
```

Result:
![image](https://user-images.githubusercontent.com/36734656/87468135-532a8900-c619-11ea-8884-f24321a74a70.png)

**Comment by LarsDenBakker** [comment]
@jorenbroekema it should be `threshold` not `thresholds`.

I'm going to improve the final message because even though it's exiting with status 1 it's celebrating that all tests pass :P
