### ISSUE TITLE
[@web/dev-server-esbuild] Cannot read property 'is' of undefined

### ISSUE THREAD

**Issue by JamesIves** [modernweb-dev/web#1526]
## Description

When running the esbuildPlugin with Rollup I end up with the following error. I've also tried switching the output format and I still get the same error.  I'm not sure if this is a misunderstanding of how this plugin is supposed to work, of this is an actual bug or not. 

```
[rollup] rollup v2.52.1
[rollup] bundles src/shared/index.ts → dist/tokens.js...
[rollup] [!] (plugin esbuild) TypeError: Cannot read property 'is' of undefined
[rollup] src/shared/index.ts
[rollup] TypeError: Cannot read property 'is' of undefined
[rollup]     at Object.transform (/Users/Documents/Dev/project/node_modules/@web/dev-server-esbuild/src/EsbuildPlugin.ts:100:26)
[rollup]     at /Users/Documents/Dev/project/node_modules/rollup/dist/shared/rollup.js:19990:25
```

## Reproduce

The following configuration can be used to reproduce this error.

#### `rollup.config.js`

```javascript
import { esbuildPlugin } from '@web/dev-server-esbuild';

const distFolder = 'dist';

export default [
	{
		input: ['src/shared/index.ts'],
		output: {
			file: `${distFolder}/tokens.js`,
			format: 'es',
			sourcemap: true
		},
		plugins: [
,
                      esbuildPlugin({ ts: true, mode: 'auto' }),
		]
	},
]
```

#### `src/shared/index.ts`

```javascript
console.log('hello')
```

## Versions

`"rollup": "2.52.1",`
`"@web/dev-server-esbuild": "^0.2.12",`

**Comment by LarsDenBakker** [comment]
`@web/dev-server-esbuild` is a plugin for `@web/dev-server`, not for rollup. :)

**Comment by JamesIves** [comment]
Ah that's my bad, I assumed this would work as dev-server uses rollup plugins. I assumed wrong!

**Comment by LarsDenBakker** [comment]
The other way around it does work, but for this plugin we use things that are only available in the dev server such as checking request headers to determine the compile target.
