### ISSUE TITLE
[test-runner] Implement cobertura report

### ISSUE THREAD

**Issue by movrack** [modernweb-dev/web#1548]
Hello,

Since my company use azure devops, we can get coverage report from build pipeline via cobertura reports.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops

>For example: $(System.DefaultWorkingDirectory)/MyApp/**/site/cobertura/coverage.xml

I tried to look in web/test-runner code or documentation but I didnt' found anything related to that.

How should I do to get thoses reports ? Is it possible ?

**Comment by Westbrook** [comment]
You can leverage https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/cobertura/index.js via a config along the lines of:
```
export default {
    ...baseConfig,
    coverageConfig: {
        ...baseConfig.coverageConfig,
        reporters: ['cobertura'],
    },
};
```
You can learn about the various Istanbul reporters here: https://istanbul.js.org/docs/advanced/alternative-reporters/

**Comment by movrack** [comment]
Great, good to know.
Didn't find any document related to that on the https://modern-web.dev/ website.
