### ISSUE TITLE
Can WTR test NodeJS files?

### ISSUE THREAD

**Issue by a-laughlin** [modernweb-dev/web#1555]
Since our E2E and UI tests both use WTR, curious if we can run our node unit tests with it for tooling consistency.  It wouldn't need to start up a browser in that case.  Just run mocha directly in the same node environment the config is in.

**Comment by LarsDenBakker** [comment]
Right now it cant, and since there are already great node test runners out there I dont see why we should. For example you can use the mocha cli or ava.

**Comment by a-laughlin** [comment]
Good to know.  Thank you for confirming Lars!
