### ISSUE TITLE
[browser-logs] Error while deserializing browser logs for functions inside objects

### ISSUE THREAD

**Issue by jorenbroekema** [modernweb-dev/web#1557]
In any test, you can write:

```js
const foo = { 'my-element': locale => 'bar' };
console.log(foo);
```

Which will result in `null` as output and the following error thrown by `@web/browser-logs`

![image](https://user-images.githubusercontent.com/36734656/126286446-137ce580-a8ea-44ee-8649-693d0acc0dc2.png)

```js
const foo = { 'my-element': 'bar' };
console.log(foo);
```

The above code works like expected, so I think it has something to do with functions inside objects.

**Comment by WickyNilliams** [comment]
I just got the same error when logging:

```ts
console.log(e.composedPath())
```

Testing a little more, logging a function on its own is fine, as this _does not_ cause errors:

```ts
console.log(() => 1)
```

So it does seem to be related specifically to functions inside objects as @jorenbroekema pointed out
