### ISSUE TITLE
[dev-server-rollup] Update @rollup/plugin-node-resolve to v13

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1575]
The version has been downgraded by #1569 to make the failing test pass.
See #1568 for the example of a test failing with v13.

We need to investigate the failing test and then upgrade the plugin back. This should address these issues:
- https://github.com/modernweb-dev/web/issues/1376#issuecomment-886153882
- https://github.com/modernweb-dev/web/issues/1443

**Comment by abdonrd** [comment]
I see the CI also failing with v8:

https://github.com/open-wc/open-wc/pull/2182

**Comment by web-padawan** [comment]
The failures in the open-wc seem to be unrelated and those PRs are outdated so I will close them.

Here is the change in v13 that apparently caused the test to break: https://github.com/rollup/plugins/pull/799

**Comment by abdonrd** [comment]
Op! I confused the two repositories! 😅 haha
