### ISSUE TITLE
[rollup-plugin-html] String matching for detecting html tag is taking in other patterns

### ISSUE THREAD

**Issue by ravinsharma7** [modernweb-dev/web#1589]
I have a project with PHP files that are the majority are just HTML syntax, but some portions have PHP tag embedded in them.

The rollup HTML plugin is detecting those PHP tags as HTML and the output from rollup becomes unusable. Is there a way to ignore the PHP tags? Or have the plugin parse just HTML tags without taking in the PHP tags. The PHP tags start with either `<?=`, or `<?php`, and end with "?>"

Would like some suggestions on how to make it work in this situation.

Example
```
<component-clinic-status-modal
    open="<?= (isset($modal["toggle"]) && $modal["toggle"]==="open") ? "true" : "false" ?>"
   redirect_url="<?= isset($modal["redirect_url"]) ? $modal["redirect_url"] : "" ?>"
   title="<?= isset($modal["title"]) ? $modal["title"] : "" ?>"
   description="<?= isset($modal["description"]) ? $modal["description"] : "" ?>"
   btntext="<?= isset($modal["btntext"]) ? $modal["btntext"] : "" ?>">
</component-clinic-status-modal>
```

Thank you for your help.

**Comment by bennypowers** [comment]
It seems unlikely we'll be able to support this, as we use parse5 to scan your html file, and parse5 does not support php. You might consider post-processing the file to replace the attributes with your PHP expressions.
