### ISSUE TITLE
Mocha timeout settings

### ISSUE THREAD

**Issue by davemooreuws** [modernweb-dev/web#163]
I am having an issue when using playwright. It seems I cannot change the mocha timeout settings from its default of 2000ms.
I don't see this in the documentation

**Comment by LarsDenBakker** [comment]
We don't want a way yet to change global mocha settings, but you can set it per test or describe:

```js
describe('my test', function () {
  this.timeout(3000);
  it('works', function () {
    this.timeout(3000);
  });
});
```

**Comment by davemooreuws** [comment]
> We don't want a way yet to change global mocha settings, but you can set it per test or describe:
> 
> ```js
> describe('my test', function () {
>   this.timeout(3000);
>   it('works', function () {
>     this.timeout(3000);
>   });
> });
> ```

Thank you. This will work for now.

**Comment by LarsDenBakker** [comment]
I just realized a typo, we do want a way to set this. We just dont have it at the moment :)

**Comment by Westbrook** [comment]
In your config you can leverage the following settings to ensure this across your entire suite:
```
testFramework: {
        config: {
                timeout: 3000,
        },
},
```
