### ISSUE TITLE
Broken link on Open Collective Website for this project

### ISSUE THREAD

**Issue by misterhtmlcss** [modernweb-dev/web#1632]
Website: https://opencollective.com/modern-web
Broken Link: https://modern-web.dev/learn/test-runner/getting-started/
Suggested correction: https://modern-web.dev/guides/test-runner/getting-started/

Image to help you find the link I'm referring to on Open Collective.
<img width="655" alt="Screen Shot 2021-08-18 at 9 56 56 AM" src="https://user-images.githubusercontent.com/13112566/129932260-218267a9-68b3-4283-91b1-b9f1d71787a8.png">

As per @bennypowers I've added this as an Issue here.

**Comment by bennypowers** [comment]
should be fixed now. thanks for the report
