### ISSUE TITLE
Bump minimal node version to compatible with pure ES modules

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1647]
Part of #1642 

## Problem

Currently the supported engines look like this:

https://github.com/modernweb-dev/web/blob/7f9044157466e73093c4707b16e4198260b499ce/packages/dev-server/package.json#L27-L29

## Proposed solution

Update engines to match the list that enables using [pure ESM packages](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm).

```json
"engines": {
  "node": "^12.20.0 || ^14.13.1 || >=16.0.0"
},
```

This covers `@web/dev-server`, `@web/test-runner` and other packages currently at `0.x`.
We need to do this before releasing `1.0.0`, maybe by entering `1.0.0-pre.1` first.

**Comment by koddsson** [comment]
I believe this is done!
