### ISSUE TITLE
E2E test using test-runner

### ISSUE THREAD

**Issue by davidNHK** [modernweb-dev/web#1670]
Hi team, I see this beautiful project recently 

But can I known it is possible do E2E test on test-runner?

Thing like stub the network request, visit specific path and triggers actions ……

After I take a look to example project ,  I can't see example there

**Comment by LarsDenBakker** [comment]
Wtr is created to run tests ib the browser. There are libraries that allow stubbing network such as mswjs and sinon. But for true e2e it is best to use playwright or puppeteer directly.

**Comment by davidNHK** [comment]
So, it excepted i have another set of test-runner and configuration to doing e2e test, right ?

**Comment by LarsDenBakker** [comment]
Yes, although you can use web dev server to reuse the config parts from wtr related to serving files.

**Comment by davidNHK** [comment]
Thanks for reply!

It would be great if can make it working with e2e test as well !

so e2e test and unit test can use same framework to achieve .

I close this for now.
