### ISSUE TITLE
[test-runner-mocha] Update mocha to v9, add es-2018 entrypoints

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1674]
## Motivation

The new major version of `mocha` provides an ES2018 entrypoint `mocha-2018.js`
This file is much smaller compared to the `mocha.js` which is transpiled to ES5.

I have tried to bundle it with `build:production` script and got following results:

ES5 autorun.js - 347295 bytes
ES5 standalone.js - 347143 bytes
ES2018 autorun.js - 268477 bytes
ES2018 standalone.js - 268325 bytes

So it would save around 77 KB (~22%)

## Proposed solution

1. Update `mocha` to v9 - see #1498 
2. Add two new entrypoints `autorun-es2018.js` and `standalone-es2018.js`

## Example

See the branch: https://github.com/vaadin/web-components/compare/mocha-9
I confirmed that `mocha` 9 works in out tests in Chrome, Firefox and WebKit.

**Comment by koddsson** [comment]
We're on Mocha 10 now! 🎉
