### ISSUE TITLE
[dev-server-esbuild] transform options

### ISSUE THREAD

**Issue by rodneysantos** [modernweb-dev/web#1676]
Hello,

I'm trying to use the [`banner`](https://esbuild.github.io/api/#banner) option of transform but noticed that it is not exposed.
May I know why we are limiting the options being passed to `esbuild.transform`?

```typescript
// @web/dev-server-esbuild/src/EsbuildPlugin.ts - L160
const { code: transformedCode, warnings } = await transform(code, {
  sourcefile: filePath,
  sourcemap: 'inline',
  loader,
  target,
  // don't set any format for JS-like formats, otherwise esbuild reformats the code unnecesarily
  format: ['js', 'jsx', 'ts', 'tsx'].includes(loader) ? undefined : 'esm',
  jsxFactory: this.esbuildConfig.jsxFactory,
  jsxFragment: this.esbuildConfig.jsxFragment,
  define: this.esbuildConfig.define,
  banner: '' // <-- not available
});
```

Would it be possible to allow users to set which transform options they want to pass to esbuild.transform?

**Comment by web-padawan** [comment]
I don't think there is any particular reason except the fact we haven't seen a need for this. Feel free to submit a PR 👍
