### ISSUE TITLE
Feature suggestion - Test context and migration documents

### ISSUE THREAD

**Issue by davidNHK** [modernweb-dev/web#1679]
Hi Team,
I wanna migrating my side projects from `jest` to `web-test-runner` recently. 

[My Project here](https://github.com/davidNHK/spotify-music-player)

The most benefit obviously is i can see what test actually running on the browser that definitely make my life simple.
But i facing issue while i try to do that.

1. No ways to extract current running context. like `expect.getState()` do on `jest` so i can know what is current test file running. 
2. Ways to mocking specific modules like `jest.mock` ?  so that i can mocking out some of dependency on my App.
3. How to support Assertion library like `expect` ? Because if deal with testing-library, it already ship with expect extensions. can i simply reuse that ?

Thanks

**Comment by davidNHK** [comment]
And if have document about `jest` migration, it would definitely better than now

**Comment by bennypowers** [comment]
1. `import.meta.url`
2. mocking modules isn't really a test runner concern, but a test framework thing, are you using mocha/sinon? tape compiled to esm? etc? follow the guidelines for your test framework
3. `import { expect } from 'chai'` or some such. We usually recommend `@open-wc/testing` for web components.

**Comment by davidNHK** [comment]
Thanks for suggesting! It helpful 

For 3. I mean I would like use 

https://www.npmjs.com/package/expect

To my assertion library 

And reason behind that is I want reuse https://github.com/testing-library/jest-dom for assert screen elements 

Any ideas for that?

**Comment by bennypowers** [comment]
web test runner doesn't have any opinions about which testing framework or assertion library you use. As long as you can run your assertion library in a browser, you should be fine. 

if you want to do visual diff testing you might want to use playwright's test runner, or use the commands api from web test runner

https://modern-web.dev/docs/test-runner/commands/

**Comment by davidNHK** [comment]
For who want migration as well, 

end up i did my following to make thing working.

1. For current test info , you can access `this.currentTest` - ref: [stackoverflow](https://stackoverflow.com/questions/18304280/how-can-i-retrieve-the-current-tests-name-within-a-mocha-test)
2. Mocking - I skipped this part because i have only mocked module, just detect running on test by NODE_ENV / APP_MODE and run your test specific logic
3. User `jest.expect`, it require you patch the package. see [issue](https://github.com/facebook/jest/issues/11065)

issue above also include how to make global setup work.

And probably you would need 

- replace `it.each` from jest
- replace `exepct.getState().currentTestPath` with `import.meta.url` , it would request you change interface as well coz `import.meta.url` always return current file path like `${__dirname}/${__fileName}`
- replace some module that not supported esm module ? especially module that using `fs` / `dynamic require` 

I close this ticket for now.
