### ISSUE TITLE
@web/test-runner watch + mode glob pattern ?

### ISSUE THREAD

**Issue by sijakret** [modernweb-dev/web#1689]
Hi All!

Am I missing something or does `--watch` first execute all tests before you can actually pick one via the interactive UI?
If you have a lot of tests this is kind of a problem.

Why not allow the `--watch` option to take glob pattern right of the bat?
That would enable focusing on a specific file or a set of files right off the bat.

Note: I am pretty much looking for what karma supports via `--grep` https://github.com/karma-runner/karma-mocha/issues/6

PS: very cool project! :)

**Comment by bennypowers** [comment]
Try the `--files` switch

https://modern-web.dev/docs/test-runner/cli-and-configuration/

**Comment by sijakret** [comment]
It does not look like this plays together with `groups` in the config. It seems like whatever matches `files` gets stacked on top of the groups. what would be more helpful would be a way to only execute a subset of the tests in groups.

The interactive `--watch` mode is actually really close it's just that it executes all the tests on launch already.
