### ISSUE TITLE
coverage includes all lines (comments, import statements, etc..)

### ISSUE THREAD

**Issue by sijakret** [modernweb-dev/web#1715]
Hi there,

First of all: I love the modern web tooling it is so fast and straight forward!

When using the coverage reporting in web-test-runner the results I am getting seem to include lines without relevant statements (i.e. imports, comments, etc..).

Below are results from a typical karma stack for reference and the coverage results from web-test-runner are of comparatively low value here unfortunately. Do I have another problem here or is this behavior intended?

_(please excuse the cropped views but i think it get's the point across.)_

karma + babel + istanbul reporter
(ignores imports, comments, exported function definitions.. which is very common and desirable)
![image](https://user-images.githubusercontent.com/16835620/136632553-8e92b651-d827-4775-a833-6a48490f3d1a.png)
web test runner + chromium v8 + v8-to-istanbul
![image](https://user-images.githubusercontent.com/16835620/136632624-f65b4e1f-6f72-4661-943d-4d51fad6d39f.png)

any tips on how to ignore the irrelevant lines ?

edit: v8 report does not seem to distinguish between statements and lines.
edit2: maybe this is just a reporter misconfiguration?
![image](https://user-images.githubusercontent.com/16835620/136632996-b3033741-7b23-4fe9-ad9d-29851c201861.png)

initially raised this here: https://github.com/istanbuljs/v8-to-istanbul/issues/56 not sure where it really belongs

**Comment by web-padawan** [comment]
Thanks for the issue. I think the reason for it is that `v8-to-istanbul` reports all the lines executed in the browser.

**Comment by sijakret** [comment]
Ok, imho the istanbul-instrumented coverage is significantly more useful than the v8 coverage.

This is how I am doing it now using the standard js-space istanbul instrumentation:

```js
// ..
import { fromRollup } from '@web/dev-server-rollup';
import rollupIstanbulPlugin from 'rollup-plugin-istanbul';

/**
 * unit test config
 */
export default {
  // ..
  nodeResolve: true,
  coverage: true,
  plugins: [
    fromRollup(rollupIstanbulPlugin)({
      // be sure to add your sources here!
      include: ['**/src/**']
    }),
    // ..
  ],
  coverageConfig: {
    report: true,
    reportDir: 'coverage-report',
    // nativeInstrumentation: false, // <- if uncomment this line, report is empty!
  }
}
```

Note: If I set `nativeInstrumentation: true` the generated report is empty (it is still generated though..)

Overall this setup works very well.
In my case, the instrumented code is not too heavy so I much prefer the more meaningful report here.

Since I assume most people are using this tooling in conjunction with es module stacks, shouldn't what I am doing using `rollup-plugin-istanbul` be the documented alternativen to the v8 coverage? 
If you agree I can create a PR to update [the corresponding section in the docs](https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#coverage-browser-support)

**Comment by sijakret** [comment]
In my case I did not see a significant slowdown. But there is not much too much code that is being instrumented. it is likely not faster than the native(?) v8 coverage tracking.

My guess is the babel plugin from the current example in the Docs and the rollup plugin both use https://www.npmjs.com/package/istanbul-lib-instrument to instrument the code so likely there's not a big difference between them.

The other day I couldn't get the babel plugin to work though and overall the rollup plugin seems more focused and thus adequate for the task.

**Comment by sijakret** [comment]
Happy with `rollup-plugin-istanbul` at this point. So from my perspective this can be closed.
It is not as fast as the v8 coverage but has much more meaningful results for us.

**Comment by ChristianUlbrich** [comment]
In our project the native V8 coverage instrumentations seems to struggle; whatever crazy combination of include/exclude patterns I try, our 800+ TS transpiled integration tests with sourcemaps will let the tests run 10x times longer. Hm, maybe using `pnpm` in a monorepo and transpile code before testing with `tsc` and sourcemaps is not sth. that is so common.

Anyhow, thanks to you @sijakret, the following works for us™:

```javascript
// ...
coverage: true,
coverageConfig: {
  include: ['src/**/*.js'],
  exclude: ['src/**/*.scss', 'src/**/*.spec.js'],
  reportDir: './reports/coverage/integration',
  reporters: ['lcov', 'cobertura'],
},
plugins: [
   fromRollup(rollupIstanbulPlugin)({
      include: ['src/**/*.js'],
 })]
``` 
**N.B.** I have to set **both** `include`, otherwise I end up with stuff from the complete monorepo (node_modules, ...). And I can second your observation, setting `nativeInstrumentation: false` won't generate the html report. :(

Oddly enough, this is way faster than the native instrumentation. (50s vs. 700s+)
