### ISSUE TITLE
[test-runner-commands] Add a command for triggering the `:hover` state

### ISSUE THREAD

**Issue by vursen** [modernweb-dev/web#1758]
## Motivation

The standard Web API doesn't make it possible to enable the `:hover` state for an element programmatically. Although you can synthesize mouse events on the element with JavaScript, it still won't cause the element to get the `:hover` state. It would be useful if there was a command provided by the test runner for such a purpose based on the browser's internal API.

### Puppeteer

The `page.hover(selector)`  method can be used to hover over an element by a CSS selector:

https://pptr.dev/#?product=Puppeteer&version=v10.4.0&show=api-pagehoverselector

### Playwright

The `page.hover(selector[, options])` method can be used to hover over an element by a CSS selector:

https://playwright.dev/docs/api/class-page#page-hover

### WebDriver

The `browser.elementHover(elementId)` method can be used to hover over an element in Chromium with the caveat that the element can be only selected by id:

https://webdriver.io/docs/api/chromium/#elementhover

## Command API proposal

Introduce an asynchronous `hover` command that would trigger the `:hover` state for an element by id, or by a CSS selector if there is a way to make that work for WebDriver.

```js
import { hover } from '@web/test-runner-commands';

describe('element', () => {
  it('should be blue by default', () => {
    expect(element.getComputedStyle().color).to.equal('blue');
  });
  
  it('should become red on hover', async () => {
    await hover('#element');
    
    expect(element.getComputedStyle().color).to.equal('red');
  });
});
```

**Comment by web-padawan** [comment]
> The browser.elementHover(elementId) method can be used to hover over an element in Chromium with the caveat that the element can be only selected by id:

Let's check if this API works when using Sauce Labs launcher. I suspect it might be only working for local Chrome.

**Comment by vursen** [comment]
Well, it seems to be possible to hover over an element by a selector in the WebDriver, not only by id. The approach is basically described in https://github.com/webdriverio/webdriverio/issues/4322#issuecomment-518990244: instead of using the `elementHover` method, use the `performAction` method to actually move the pointer over the element that will lead to triggering the `:hover` state.

Here is an example:

```ts
function hover(selector: string) {
  const { x, y } = await this.driver.$(selector).getLocation();
  return this.driver.performActions([
    {
      type: "pointer",
      id: "finger1",
      parameters: {
        pointerType: "mouse"
      },
      actions: [
        {
          type: "pointerMove",
          duration: 0,
          x: x + 1,
          y: y + 1
        }
      ]
    }
  ]);
}
```

**Comment by vursen** [comment]
Closing this issue. If you want to trigger `:hover` for an element, please use [the `sendMouse` command](https://modern-web.dev/docs/test-runner/commands/#send-mouse).
