### ISSUE TITLE
Question; from where is comming the file '__web-dev-server__web-socket.js'

### ISSUE THREAD

**Issue by movrack** [modernweb-dev/web#1809]
Hello,

I have an issue to run storybook build.
I got and error:

`(node:5816) UnhandledPromiseRejectionWarning: Error:(node:5816) UnhandledPromiseRejectionWarning: Error: Could not load C:\workspaces\project\__web-dev-server__web-socket.js (imported by node_modules\@web\test-runner-commands\browser\commands.mjs): ENOENT: no such file or directory, open 'C:\workspaces\project\__web-dev-server__web-socket.js'`

So I am curious from where is comming /__web-dev-server__web-socket.js in 
https://github.com/modernweb-dev/web/blob/36a06160f2d44de6b76df1f3afa9d5982b5dad59/packages/test-runner-commands/browser/commands.mjs#L20
Is it a file generated?

**Comment by thepassle** [comment]
You are, one way or another, importing @open-wc/testing via your stories. This is a consequence of @open-wc/testing having a monolithic index.js which eventually leads down to the file referenced in the error message, which imports a virtual module (as benny pointed out). Rollup is not able to find the virtual module and errors.

**Comment by movrack** [comment]
So I have to remove @open-wc/testing ?

**Comment by movrack** [comment]
Thanks for the chat @thepassle ; issue is fixed.

**Comment by brettpostin** [comment]
What was the solution here?
