### ISSUE TITLE
[test-runner-puppeteer] Update puppeteer dependency to avoid high severity security bug in node-fetch

### ISSUE THREAD

**Issue by melink14** [modernweb-dev/web#1858]
https://github.com/advisories/GHSA-r683-j2x4-v87g

Puppeteer released 13.1.2 but current version is 10. 
https://github.com/puppeteer/puppeteer/pull/7924

Not sure if there was a specific reason the version was kept out of date but hopefully it's not too hard to upgrade!

**Comment by web-padawan** [comment]
Thanks for the issue. I merged the PR to update `puppeteer-core` and `puppeteer` to 13.1.2.
Please upgrade `@web/test-runner` version to `0.13.26` to get the latest fix.
