### ISSUE TITLE
Test failure while executing command from webtestrunner plugin with the package Playwright Lighthouse using playwright chromium launcher

### ISSUE THREAD

**Issue by shishirm18** [modernweb-dev/web#1898]
Our aim is to create a PlugIn for WebTestRunner using the package Playwright Lighthouse.
https://www.npmjs.com/package/playwright-lighthouse

**Description:**
We were using the open-wc web-test-runner test for visual regression testing, we thought of adding performance testing using plugin's. 
We were able to write the plugin that will in-turn calls the playAudit of playwright lighthouse package.
**PlayAudit in-turn calls page.reload(), this makes the test to fail.**
We are only doing it with **playwright chromium launcher**.

**Steps to Reproduce:**
->  We prepared a plugIn that calls the playAudit of Playwright Lighthouse package.

```
async function measureLighthouseScore(session, payload) {
  if(session.browser.type == "playwright")
  {
    const browser = session.browser;
    const page = browser.getPage(session.id);
    //This is where the page gets reloaded
    await playAudit({
              page:page,
              thresholds: {
                  performance: 50,
              },
             port: 9222
    });
  };
  return new Promise(r => r('reported'));
}
```

**Expected:**
-> Lighthouse performance audit test scores are successful.

**Actual result:**
-> ❌ Tests were interrupted because the page was reloaded. This can happen when clicking a link, submitting a form or interacting with window.location.
![image](https://user-images.githubusercontent.com/100864799/157602153-43cf1cd5-efb0-492f-b8f3-72cec438b073.png)

**Comment by LarsDenBakker** [comment]
This is expected, reloading the page causes the test run to be interrupted.
