### ISSUE TITLE
[test-runner] Be able to configure retry attempts for failed tests

### ISSUE THREAD

**Issue by jordimarimon** [modernweb-dev/web#1918]
Hi,

Sorry in advance if this topic has already been discussed. I haven't found any issue talking about it.

I'm using playwirght as the browser launcher.

In the CI environment, sometimes I get some small amount of tests (5%) failing because of timeouts exceeded. I'm never able to reproduce this failed tests in local machines. And also if I execute multiple times the tests in CI, they will eventually pass (normally executing them twice is enough). 

It's in Firefox where I get the errors of timeouts (in Webkit and Chromium I never get this errors).

The errors I received in Firefox are of this type:

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (failed on Firefox)
```

These errors only happen in tests where I'am testing keyboard accessibility but they appear to be randomly, sometimes it fails, sometimes it doesn't and it only happens in the CI environment in Firefox.

It would be nice to be able to configure the amount of retries for failed tests so the tests pass after executing them multiple times.

**Comment by LarsDenBakker** [comment]
The retry is something that should be implemented by the test framework in the browser. For example when using mocha, does it provide an option for that?

**Comment by jordimarimon** [comment]
Thanks for the reply! You're absolutely right, this should be provided by the test framework.

And mocha does provide support for it: https://mochajs.org/#retry-tests

I will close the issue. Thanks!
