### ISSUE TITLE
[test-runner-saucelabs] saucelabs version is very old

### ISSUE THREAD

**Issue by justinfagnani** [modernweb-dev/web#1964]
https://github.com/modernweb-dev/web/pull/1750 pinned the `saucelabs` dependency to `~6.1.0`. The current version is `7.2.0`. Sauce Labs support has strongly recommended that we upgrade.

cc @web-padawan who made #1750. Was there a plan to unpin at some point?

**Comment by web-padawan** [comment]
Submitted #1966 to see if the original issue is now fixed.

**Comment by justinfagnani** [comment]
Thanks @web-padawan! Looks like it's passing the Sauce test there

**Comment by web-padawan** [comment]
Fixed by #1966 and released in `0.8.0`.
