### ISSUE TITLE
[test-runner-cli] Errors when using Playwrite

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#199]
I'm attempting to port tests that previously relied on Karma to run into WTR. Changed primarily include ensuring the presence of `.js` file information and the removal of snapshot testing. Locally the test run and pass, but when running tests in CI I get the following error:
```
yarn run v1.21.1
$ yarn test:build && yarn test:wtr
$ tsc --build test/tsconfig-test.json
$ web-test-runner packages/*/test/**/*.test.js --node-resolve --playwright --browsers chromium firefox
Error while running tests:
TypeError: Cannot read property 'message' of undefined
    at ProgressController.run (/home/circleci/project/node_modules/playwright/lib/progress.js:85:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:727) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.getTestProgressReport (/home/circleci/project/node_modules/@web/test-runner-cli/dist/messages/getTestProgress.js:73:73)
    at TestRunnerCli.logTestProgress (/home/circleci/project/node_modules/@web/test-runner-cli/dist/TestRunnerCli.js:254:43)
    at TestRunnerCli.start (/home/circleci/project/node_modules/@web/test-runner-cli/dist/TestRunnerCli.js:53:14)
    at Object.startTestRunner (/home/circleci/project/node_modules/@web/test-runner-cli/dist/startTestRunner.js:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This was build from: https://github.com/adobe/spectrum-web-components/tree/westbrook/wtr
The build can be found at: https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/3177/workflows/72db9a8f-d554-4e60-bdf8-48473f66aa76

**Comment by LarsDenBakker** [comment]
It looks like an error in playwright, does it work correctly with puppeteer? Or with just chromium?

**Comment by Westbrook** [comment]
Looks like it has to do with the inclusion of `firefox` as `chromium` only and `--puppeteer` both run.

**Comment by Westbrook** [comment]
What do we need to do to get the Playwright team also using WTR to test Playwright? They we can make feature requests of them!

**Comment by Westbrook** [comment]
I'm not able to run tests in both FF and WebKit on CI, so I don't think there is anything else that needs to be done after the addition of https://modern-web.dev/docs/test-runner/testing-in-a-ci/
