### ISSUE TITLE
[test-runner] look into typescript developer experience

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#20]
We should into the DX of authoring tests in TS:

- TSC + WTR setup
- Compile TS in EDS (perhaps using sucrase?)
- Source mapped stack traces
- Source mapped click to test file

**Comment by bennypowers** [comment]
ok so tsc should probably stay out-of-band
but when using typescript, watch should not trip on .ts file changes, only on .js

**Comment by bennypowers** [comment]
Other than that, if test files have sourcemaps (including inline), then the logs should point to the TS files, not the js files

**Comment by LarsDenBakker** [comment]
I personally don't like running tsc out of band, but it is the most reliable option. I added an experimental plugin for esbuild so that you can transform on the fly. I added recommendations in the docs for both, people can choose what to do.

The source maps are tracked here https://github.com/modernweb-dev/web/issues/20
