### ISSUE TITLE
[test-runner-cli] "Total" vs "Browser" test count

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#200]
The count for the "Total" tests are currently manages in a `new Set<'${testFile}${test.name}'>()` while the count for the "Browser" test are managed with a number meaning that where `${testFile}${test.name}` to come up duplicated the number of tests could end up not matching up. It's not necessarily a "bug" but it's surprising enough that we should likely count the two in the same manner.

It _might_ also be helpful to tell people this happened, in the case that we choose to use the smaller number to report completed tests.

Separately, other tools count "Total" tests as `aBrowserTests + bBrowserTests + nBrowserTests`, not sure if the way this is tracked here should be revisited.

**Comment by LarsDenBakker** [comment]
We shouldn't definitely make sure that we count the same way between total and per browser. I guess we could sum all the tests from all the different browsers, is that what karma does? It would make things easier at least :)

**Comment by LarsDenBakker** [comment]
I'm leaning towards summing the tests, so if you have 3 browsers with 100 tests then the total shows 300 tests. @thepassle @Westbrook @jorenbroekema @bennypowers @daKmoR @manolakis any opinions?

**Comment by thepassle** [comment]
I think the sum of all tests makes sense 👍

**Comment by manolakis** [comment]
I agree. To me make sense to count the test separately. Imagine that one test pass in Chrome and Firefox but fails in Safari. If we don't count them separately how we mark the test? Failed, partially passed? I prefer to say that 2 passed and 1 failed.

**Comment by daKmoR** [comment]
That is how karma does it and it confused me in the beginning quite a lot... e.g. I had my test file open and there where clearly only 4 Tests how could 12 Tests fail/pass??

## Scenario
- 4 tests
- Chromium: 3 pass, 1 fail
- Firefox: 4 pass

What should be the total outcome?

1) Sum it individually
```
Total:    |██████████████████████████████| 1/1 test files | 7 passed, 1 failed

Chromium: |██████████████████████████████| 1/1 test files | 3 passed, 1 failed
Firefox:  |██████████████████████████████| 1/1 test files | 4 passed
```

2) Show worse case
  => as soon as it failed on one browser it's a fail in the summary
```
Total:    |██████████████████████████████| 1/1 test files | 3 passed, 1 failed

Chromium: |██████████████████████████████| 1/1 test files | 3 passed, 1 failed
Firefox:  |██████████████████████████████| 1/1 test files | 4 passed
```

could lead to... still most accurate? as 2 tests failed in Chrome and the other 2 in Firefox... so non of them is without failure
```
Total:    |██████████████████████████████| 1/1 test files | 0 passed, 4 failed

Chromium: |██████████████████████████████| 1/1 test files | 2 passed, 2 failed
Firefox:  |██████████████████████████████| 1/1 test files | 2 passed, 2 failed
```

**Comment by manolakis** [comment]
Personally I like more the first one.

Another option could be omitting the total row and showing only the counts by browser. Wouldn't it be more intuitive?

**Comment by daKmoR** [comment]
I like the second one as it gives me the number of tests to look at in my code...

imagine having 5 tests failing in 3 browsers that's 15 failed... even though I only need to look at 5 tests in the code to fix it

**Comment by thepassle** [comment]
> Show worse case
> => as soon as it failed on one browser it's a fail in the summary
> ```
> Total:    |██████████████████████████████| 1/1 test files | 3 passed, 1 failed
> 
> Chromium: |██████████████████████████████| 1/1 test files | 3 passed, 1 failed
> Firefox:  |██████████████████████████████| 1/1 test files | 4 passed
> 
> ```

But what is the total if its more than chromium and firefox, and tests have failed on multiple browsers?

```
Chromium: |██████████████████████████████| 1/1 test files | 3 passed, 1 failed
Firefox:  |██████████████████████████████| 1/1 test files | 4 passed
Safari: |██████████████████████████████| 1/1 test files | 2 passed, 2 failed
```

```
Total:    |██████████████████████████████| 1/1 test files | 2 passed, 2 failed
```

or

```
Total:    |██████████████████████████████| 1/1 test files | 3 passed, 1 failed
```

?

For me the sum of all tests still is the most clear

**Comment by daKmoR** [comment]
> as soon as it failed on one browser it's a fail in the summary

so definitely `2 passed, 2 failed` if the same tests failed could be even `1 passed, 3 failed` if different tests failed on different browser.

Basically each test passes only it if it passes on all browser.
=> because that means you need to look at that test

**Comment by thepassle** [comment]
Okay so basically the most amount of failed tests would be logged? Maybe its just that the word `Total` doesnt make sense in this context then, since its not a total overview of tests; its a message that points out the most failed tests.

But having said that, I still think the sum is nicer and less confusing :p

**Comment by daKmoR** [comment]
another scenario.

while developing you only run tests on chrome and you have 100 tests and are 3 failing.
So now you then wanna check how it looks for firefox, webkit... so you run it on all and then you have 9 failing tests... even though no code changes and your code works actually quite good.

I think that is confusing 😅

**Comment by LarsDenBakker** [comment]
What if we don't show a total tests at all? Or only a total progress bar?

**Comment by thepassle** [comment]
Something like this?

```
Progress:    |██████████████████████████████| 1/1 test files | 300 tests executed

Chromium: |██████████████████████████████| 1/1 test files | 97 passed, 3 failed
Firefox:  |██████████████████████████████| 1/1 test files | 97 passed, 3 failed
Safari: |██████████████████████████████| 1/1 test files | 97 passed, 3 failed
```

**Comment by LarsDenBakker** [comment]
Yep, or maybe no progress at all. What does it even add ?

**Comment by thepassle** [comment]
> Yep, or maybe no overall progress at all. What does it even add ?

Seems like a good conclusion to me as well 👍
