### ISSUE TITLE
[web-test-runner] "Failed to fetch dynamically imported module" after silent dev-server-esbuild fail

### ISSUE THREAD

**Issue by mkczarkowski** [modernweb-dev/web#2042]
Currently when you use `dev-server-esbuild` to transpile files, `web-test-runner` doesn't display errors that occurs during the transpilation process. The only feedback that you get is:
```
test/specs/autocomplete.spec.ts:

 🚧 Browser logs:
      TypeError: Failed to fetch dynamically imported module: http://localhost:8000/test/specs/autocomplete.spec.ts?wtr-session-id=-NU7GvtfIlk4fdKWEvWWZ

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information. 
```

This makes finding root cause of the problem really hard. In my case it was: [#2041](https://github.com/modernweb-dev/web/issues/2041), but I only found about it after installing `esbuild` directly in my project to test if the transpilation process works fine.

**Comment by Westbrook** [comment]
In cases like this, leverage the debug option https://modern-web.dev/guides/test-runner/watch-and-debug/#debug to view this code in the browser and `debugger`/Network watch your tests to investigate loading issues. It will give you a full and interactive report of anything thing that might be going wrong with your test.
