### ISSUE TITLE
Throws error from @web/test-runner-visual-regression when we have noImplicitReturns set

### ISSUE THREAD

**Issue by msbasanth** [modernweb-dev/web#2049]
## Observation

Throws error from @web/test-runner-visual-regression when we have **noImplicitReturns** set to true. It is not actually from our own code but we have a direct import statement which causes this issue. 

`import { DiffArgs, DiffResult } from '@web/test-runner-visual-regression/src/config';`

This makes config.ts also part of compilation and identifies not returning in all code paths @config.ts as an issue.

### Error
`../../node_modules/@web/test-runner-visual-regression/src/config.ts:109:3 - error TS7030: Not all code paths return a value.`

### Code from _@web/test-runner-visual-regression/src/config.ts_
```
async function getImage({ filePath }: ImageArgs) {
  if (await fileExists(filePath)) {
    return readFile(filePath);
  }
  return undefined;
}
```
A fix from your side will be a perfect solution to this problem it would be great if you could take it up as part of your code cleanup.

**Comment by Westbrook** [comment]
`import { DiffArgs, DiffResult } from '@web/test-runner-visual-regression/src/config';` allows your compiler to decide what type of file it would be importing from our project. In many cases, it will start with TS, which in this case is incorrect. Please add `.js` to the end of the import. If after that the issue persists, feel free to reopen this issue.
