### ISSUE TITLE
Types are not working when using `moduleResolution: "NodeNext"`

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#2066]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@web/dev-server-core@0.3.19` for the project I'm working on.

TS using `"moduleResolution": "NodeNext"` will say it can't find types for `@web/dev-server-core`...

If I add it like so it works fine 🤗

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@web/dev-server-core/package.json b/node_modules/@web/dev-server-core/package.json
index c65693c..0e0bdc9 100644
--- a/node_modules/@web/dev-server-core/package.json
+++ b/node_modules/@web/dev-server-core/package.json
@@ -16,6 +16,7 @@
   "main": "dist/index.js",
   "exports": {
     ".": {
+      "types": "./index.d.ts",
       "import": "./index.mjs",
       "require": "./dist/index.js"
     },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by hungtcs** [comment]
+1 same issues for node16
