### ISSUE TITLE
Coverage: Error while generating code coverage for

### ISSUE THREAD

**Issue by p15martin** [modernweb-dev/web#2082]
Hello,

I am using Yarn workspaces. When I run my tests I get the following error for each file that is outside the current project (i.e. the files are in another project within my workspace).

I don't want to include them in my coverage report as each project has their own suite of tests, but I would like to ignore these files or suppress the errors. 

Thanks!

Error while generating code coverage for http://localhost:8000/__wds-outside-root__/2/packages/shell-core/dist/messaging/webview-messaging.js.
[Error: ENOENT: no such file or directory, open '/Users/pete/code/nxt-web-ui/apps/shell/__wds-outside-root__/2/packages/shell-core/src/messaging/webview-messaging.ts'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/pete/code/nxt-web-ui/apps/shell/__wds-outside-root__/2/packages/shell-core/src/messaging/webview-messaging.ts'
}

**Comment by Westbrook** [comment]
The `coverageConfig` outlined [here](https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#writing-tests-code-coverage) accepts an `exclude` array with which you can exclude files from coverage.
