### ISSUE TITLE
(lack of) CommonJS support

### ISSUE THREAD

**Issue by void-spark** [modernweb-dev/web#2086]
We currently are using web-dev-server next to Webpack (we once started with open-wc).
Webpack happily accepts and works with CommonJS modules (things that use require(..) and module.export,
I'm not a very experienced js developer, so I might use the wrong names).
web-dev-server just refuses to work with them though, meaning we are limited to a far smaller set of npm modules we can use.
Some examples, we use @bundled-es-modules/axios since regular axios won't work (and that has a old version),
and we would like to use qs, but again it won't work. A alternative query-string, again doesn't work.
According to the documentation the CommonJS Rollup plugin should help here, but it seems horribly broken, and has been like that for a long time.
Am I missing something here? Should I look at another dev server? I get the impression avoiding CommonJS at all cost is becoming less and less of an option, I've been banging my head against walls over this for the last two days or so :)

**Comment by Westbrook** [comment]
Learn more about leveraging Common JS, here: https://modern-web.dev/docs/dev-server/plugins/rollup/#compatibility-with-rollup-plugins

We're working with some Canary releases to expand this capability, and if you were interested in helping out, you could test these following package versions:

```
🦋  Creating git tags...
🦋  New tag:  @web/dev-server@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-core@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-esbuild@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-hmr@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-import-maps@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-legacy@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-rollup@0.0.0-canary-20230216020153
🦋  New tag:  @web/dev-server-storybook@0.0.0-canary-20230216020153
🦋  New tag:  @web/test-runner-core@0.0.0-canary-20230216020153
```

Will close for now, but if you happen to have specific packages you have issues with, especially in conjunction with these Canary releases, please feel free to open a new issue.
