### ISSUE TITLE
Mark `web-test-runner` as deprecated

### ISSUE THREAD

**Issue by lgarron** [modernweb-dev/web#2088]
I would like to suggest that https://www.npmjs.com/package/web-test-runner be marked as deprecated.

Since `web-test-runner` can be invoked as `npx web-test-runner`, it's easy to assume that the package is named `web-test-runner`. If you try to install that, you will get something close to what you're looking for, but with `npm audit` alerts.

If https://www.npmjs.com/package/web-test-runner is marked as deprecated, then `npm install web-test-runner` can helpfully point people to the new package.

**Comment by LarsDenBakker** [comment]
Good suggestion, it's done!
