### ISSUE TITLE
Add `excludeAssets: ['//www.youtube.com/iframe_api']` option to rollup-plugin-html

### ISSUE THREAD

**Issue by ProLoser** [modernweb-dev/web#2098]
I'm trying to use HTML files as a point of entry but some of the script tags I do NOT want to process as assets or modules (such as partner libraries hosted on both HTTP and HTTPS).

I cannot figure out how to get @web/rollup-html to ignore arbitrary scripts in my HTML to third party libraries.

**Comment by ProLoser** [comment]
Alternatively if `extractAssets` took a function instead of a boolean so I can just put my logic in there.

**Comment by ProLoser** [comment]
Or just don't throw if you can't download an asset and instead emit a warning and continue processing the HTML file

**Comment by ProLoser** [comment]
Now I'm realizing that the scripts extracted from the HTML are not being processed whatsoever. I'm surprised this plugin doesn't support processing the extracted javascript. Am I doing something wrong or is this normal behavior?

So far very disappointed in trying to use @web/rollup-plugin-html

**Comment by thepassle** [comment]
The extracted scripts get added to rollups input, so they definitely should get extracted.

> So far very disappointed in trying to use @web/rollup-plugin-html

Also, comments like these dont help anyone. As a maintainer it doesnt really make me want to support you, which means you dont get the help youre asking for, so in the future you should refrain from comments like these.

**Comment by ProLoser** [comment]
This is a patch I've applied to the code in my repo:
```
diff --git a/node_modules/@web/rollup-plugin-html/dist/assets/utils.js b/node_modules/@web/rollup-plugin-html/dist/assets/utils.js
index 491705a..1dbc0ec 100644
--- a/node_modules/@web/rollup-plugin-html/dist/assets/utils.js
+++ b/node_modules/@web/rollup-plugin-html/dist/assets/utils.js
@@ -56,6 +56,7 @@ function isAsset(node) {
         case 'script':
             if (parse5_utils_1.getAttribute(node, 'type') !== 'module' && parse5_utils_1.getAttribute(node, 'src')) {
                 path = (_g = parse5_utils_1.getAttribute(node, 'src')) !== null && _g !== void 0 ? _g : '';
+                if (path.startsWith('//') || path.startsWith('http://') || path.startsWith('https://')) return false;
             }
             break;
         default:

```

This avoids converting any scripts that are not hosted locally into assets. Rollup does not need to download and process scripts that are hosted on partner websites or hosted on other platforms, only scripts hosted on the local filesystem should be processed.

**Comment by ProLoser** [comment]
Should `script` really be added as an `asset`? I think that is different and is unprocessed vs adding script as a source.

**Comment by ProLoser** [comment]
This config does not transpile the javascript sourced from the HTML files:
```
export default {
  input: './*/index.html',
  // external: Object.keys(pkg.peerDependencies),
  output: [
    {
      dir: 'public',
      sourcemap: true,
    },
  ],
  plugins: [
    html({
      flattenOutput: false,
      rootDir: './src/providers',
    }),
    resolve(),
    babel({
      exclude: ['node_modules/**'],
      configFile: '../../babel.webview.config',
    }),
    // Compression rules
    terser({
      compress: {
        ecma: 6,
      },
      mangle: {
        reserved: ['SceUvp'],
      },
      parse: {
        ecma: 6,
      },
      toplevel: false,
    }),
  ]
}
```

**Comment by ProLoser** [comment]
Maybe you just don't handle feedback very well.

If using this library for convenience depends on the side of the bed a single maintainer woke up on, I'll abstain from it's usage, debugging, direct and informative feedback, or recommendation for usage in company projects.

I can go back to rollup-copy easily enough.

Have a nice day.
