### ISSUE TITLE
Questions: How to trigger event inside tests file

### ISSUE THREAD

**Issue by ositowang** [modernweb-dev/web#2115]
I would like to try some unit tests inside real browser environment without the complex config with Karma.js. I come across web-test-runner through vitest. I go through the starting guide, but I didn't find an example that shows how we could trigger events on the component .Is this supported by web-test-runner? Is there a recommended way to achieve that?

**Comment by Westbrook** [comment]
Events can be triggered via a number of paths...

With a reference to the element:
```
el.click();
```
You're in the JS context of the browser, so this covers most everything you'd need.

You can approach more of an integration test pattern via the [Send Mouse](https://modern-web.dev/docs/test-runner/commands/#send-mouse) commands that will work directly with your browser runner to leverage a "real" pointing device in your test.

Or, you could dispatch a constructed `click` event:

```
el.dispatchEvent(new Event('click', ...));
```

**Comment by ositowang** [comment]
Thanks @Westbrook . Sorry for the late reply and re-open the issue.. My tests are currently written with testing-library/preact. Is it possible to integrate the web-runner with testing-library?
