### ISSUE TITLE
Confirm compatibility between @rollup/plugin-typescript and @web/dev-server

### ISSUE THREAD

**Issue by ouweiya** [modernweb-dev/web#2168]
The documentation mentions that [@rollup/plugin-typescript](https://modern-web.dev/docs/dev-server/plugins/rollup/#compatibility-with-rollup-plugins) does not work properly. However, after trying to use @rollup/plugin-typescript in @web/dev-server, I found no errors and it seems to work as expected.

Here is the code:

```js
import typescript from '@rollup/plugin-typescript';
const ts = fromRollup(typescript);

export default {
  ...
  plugins: [ts()],
};
```
Is this due to an update in the packages, but the documentation has not been updated yet? 
Or is it because some features of TypeScript are not supported?

The problem encountered at the moment is that during the development process, TypeScript compilation is slower than page refresh, causing the page to display data from the previous iteration.

**Comment by koddsson** [comment]
> The problem encountered at the moment is that during the development process, TypeScript compilation is slower than page refresh, causing the page to display data from the previous iteration.

With `@rollup/plugin-typescript`? Have you considered using the [`esbuild`](https://modern-web.dev/docs/dev-server/plugins/esbuild/) plugin like the docs suggest? I think performance is the main reason that the `esbuild` plugin is recommended over the Rollup one.

**Comment by koddsson** [comment]
> The downside is that esbuild doesn't do any type checking,

I've just used the TypeScript compiler as part of an LSP in my editor and then as part of the CI/CD process by adding a `tsc --check` to the `test` script.

I'm curious to what else you'd like TypeScript to do in a development server.

**Comment by thepassle** [comment]
useDefineForClassFields should be supported, iirc you also have to set the esbuild target for it to work

**Comment by ouweiya** [comment]
I set "target": "esnext", and "useDefineForClassFields": false,, and all dependency versions are up to date, but I'm still out of luck.

**Comment by thepassle** [comment]
@jpzwarte dont you have a ts+wds/esbuild setup running? Could you share your setup?

**Comment by ouweiya** [comment]
My minimal demo library.

https://github.com/ouweiya/esbuild-dev-server

**Comment by ouweiya** [comment]
I know the reason why configure doesn't work.

https://modern-web.dev/docs/dev-server/plugins/esbuild/#examples

> Transform all .ts files to javascript using settings from tsconfig.json. (The tsconfig.json file is not read by default.)

`plugins: [esbuildPlugin({ ts: true, tsconfig: fileURLToPath(new URL('./tsconfig.json', import.meta.url)) })],`

**Comment by ouweiya** [comment]
In the end, I've decided to give up on using esbuild and continue with tsc instead, as it requires focusing on too many details for both, especially when using two different TypeScript compilers for the same codebase. The hidden development costs of this approach far outweigh the convenience brought by @web/dev-server.

Thank you to those who have helped me; you have all been very enthusiastic and friendly. I appreciate your assistance.
