### ISSUE TITLE
Fonts rendering changed after updating playwright version to 1.31.0 from 1.22.0

### ISSUE THREAD

**Issue by badigerpramod** [modernweb-dev/web#2175]
After updating to playwright 1.31.0 from 1.22.0, visual regression tests started failing due to fonts and icon rendering change

**Comment by Westbrook** [comment]
When moving from one version of playwright to the next you almost always changing versions of browser, and in Playwright that means you're also moving between versions of their custom API over those browsers, during which small changes to font rendering are not uncommon. If you feel that this is unacceptable, it's best that you bring it up with Playwright.
