### ISSUE TITLE
[rollup-plugin-html] posthtml

### ISSUE THREAD

**Issue by ecmel** [modernweb-dev/web#2178]
Thanks for the excellent plugins for rollup.

I want to transform my html sources before feeding into html plugin. transformHtml() function runs after transforming assets. Is it possible to add a function before?

I tried text input using html and name options but then the assets are not resolved.

**Comment by koddsson** [comment]
I think you want a plugin that runs before `rollup-plugin-html`? Have you considered [writing your own inline plugin](https://modern-web.dev/docs/dev-server/writing-plugins/overview/) and running it before `rollup-plugin-html`?
