### ISSUE TITLE
Error when execute test "Failed to fetch dynamically imported module"

### ISSUE THREAD

**Issue by RoXuS** [modernweb-dev/web#224]
I am trying to replace karma by wtr but I have the following errors when I launching tests:

````
test/dt-crm-export-contacts.test.js:

 ❌ TypeError: Failed to fetch dynamically imported module: http://localhost:9264/test/dt-crm-export-contacts.test.js 

test/dt-crm-export.test.js:

 ❌ TypeError: Failed to fetch dynamically imported module: http://localhost:9264/test/dt-crm-export.test.js 

test/dt-crm-export-item.test.js:

 ❌ TypeError: Failed to fetch dynamically imported module: http://localhost:9264/test/dt-crm-export-item.test.js 

test/dt-crm-export-validation.test.js:

 ❌ TypeError: Failed to fetch dynamically imported module: http://localhost:9264/test/dt-crm-export-validation.test.js 

Chrome: |██████████████████████████████| 4/4 test files | 0 passed, 0 failed

Test coverage: NaN %
View full coverage report at coverage/lcov-report/index.html

Error while running tests.
````

Versions:
````
    "@web/test-runner": "^0.6.36",
    "@web/test-runner-chrome": "^0.5.9",
````

conf:
````
// eslint-disable-next-line
const { chromeLauncher } = require('@web/test-runner-chrome');

module.exports = {
  files: ['test/**/*.test.js'],
  preserveSymlinks: true,
  nodeResolve: true,
  browsers: chromeLauncher({ args: ['--no-sandbox'] }),
  coverage: true,
  testRunnerHtml: (testRunnerImport) => `
    <html>
      <body>
        <script type="module">
          window.process = { env: { NODE_ENV: 'production' } };
        </script>

        <script type="module">
          import '${testRunnerImport}';
        </script>
      </body>
    </html>
  `,
};
````

**Comment by LarsDenBakker** [comment]
I'm not able to reproduce this locally with the same config. The browser isn't helping much with this type of error message.

If you run the tests in watch mode and press D to debug in the browser, you should be able to see some more logs. Can you try that?

**Comment by RoXuS** [comment]
I have tried but I had an obscur error:
![image](https://user-images.githubusercontent.com/3296671/87885707-c6683c80-ca17-11ea-9224-86cc150876ff.png)

**Comment by LarsDenBakker** [comment]
It looks like you sre imprting .ts files. You need to use something like https://github.com/modernweb-dev/web/tree/master/packages/dev-server-esbuild to compile those.

**Comment by RoXuS** [comment]
hum all my files are transpiled before execution, something like: `"test": "tsc && wtr"` in my package.json.

**Comment by RoXuS** [comment]
For example the path to the "export.ts" -> 
![image](https://user-images.githubusercontent.com/3296671/87886247-b05c7b00-ca1b-11ea-98db-62c6004d9186.png)

**Comment by LarsDenBakker** [comment]
I see... this might be an issue on our side because we resolve .ts files over .js files. I'll check what other tools do here.

**Comment by LarsDenBakker** [comment]
@RoXuS Could you try with 0.6.37?

**Comment by RoXuS** [comment]
context is `  const context = window.__mocha_context__;` from chai-dom-diff

**Comment by LarsDenBakker** [comment]
Yes indeed, the snapshot testing relies on some karma magic. We don't support that yet.

**Comment by RoXuS** [comment]
ohh ok, in general we don't use dom-diff, bad choice for testing, i'm wtr on other components, thx!

**Comment by RoXuS** [comment]
works as expected on typescript component without dom-diff, thx !

**Comment by LarsDenBakker** [comment]
Great to hear! We will support snapshots in the end, but indeed we also found it isn't the best testing tool.

**Comment by RoXuS** [comment]
Clearly! It is not the best tool for testing...

Le lun. 20 juil. 2020 à 19:57, Lars den Bakker <notifications@github.com> a
écrit :
