### ISSUE TITLE
Remove coverage cache and handle empty files

### ISSUE THREAD

**Issue by 43081j** [modernweb-dev/web#2258]
the coverage cache i recently added is unnecessary it turns out 😬 

i basically made these changes:

- move the sourcemap loading into the included files conditional (so we don't call it for all files)
- cache v8-to-istanbul converters since they load files from disk repeatedly

this sped up the test runs massively (several minutes).

however it turns out the latter is unnecessary and was covering up a different problem

### the coverage cache is redundant

if you call `v8ToIstanbul(code)`, it'll load the source file from disk if it can. 

you can preload the source once and pass it in like `v8ToIstanbul(code, 0, {source})`. **this is what we already do**, before my cache was added.

so the cache wasn't actually achieving anything here since the source files were already preloaded.

**we could however cache the files we load in `fetchSourceMap` to achieve what i actually meant to intend the first time around.**

### underlying problem

the reason i saw a huge amount of disk reads happening is actually because an empty sourcemap is treated as a missing sourcemap in v8-to-istanbul, so it falls back to reading the original file from disk here:

https://github.com/istanbuljs/v8-to-istanbul/blob/fca5e6a9e6ef38a9cdc3a178d5a6cf9ef82e6cab/lib/v8-to-istanbul.js#L81C3-L82

this happens a lot when you have type-only files in a typescript project. a file which only exports types will result in a sourcemap like this:

```ts
{
  "version": 3,
  "sources": [],
  "sourcesContent": [],
  "mappings": "",
  "names": []
}
```

and a source like this:

```ts
"use strict";
// sourceMapHere
```

~we already loaded the original source before calling v8-to-istanbul, so we could set `originalSource` in `fetchSourceMap` to solve this i think~ (actually we don't as far as i can see):

```ts
{
  source,
  sourceMap,
  originalSource: somehowGetHoldOfThis
}
```

cc @Westbrook 

bit of a chunky explanation but hopefully makes sense.

Actions:

- remove the coverage converter cache entirely
- set the `originalSource` when calling v8-to-istanbul
- cache sourcemaps and sources in test-runner-coverage-v8 eventually

**Comment by 43081j** [comment]
basically do this:

```ts
                  const browserUrl = `${url.pathname}${url.search}${url.hash}`;
                  let sources = cachedSources.get(browserUrl);
                  if (!sources) {
                    sources = await fetchSourceMap({
                        protocol: config.protocol,
                        host: config.hostname,
                        port: config.port,
                        browserUrl,
                        userAgent,
                    });
                    const originalSource = await readFile(filePath, 'utf8');
                    sources.originalSource = originalSource;
                    cachedSources.set(browserUrl, sources);
                  }
                    const converter = v8toIstanbul(filePath, 0, sources);
                    await converter.load();
```

**Comment by Westbrook** [comment]
Not doing work is definitely my favorite work!
