### ISSUE TITLE
[test-runner-commands] `reset-mouse` command is broken with newer versions of puppeteer

### ISSUE THREAD

**Issue by melink14** [modernweb-dev/web#2262]
This is broken since [v19.10.1](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v19.10.1) (due to https://github.com/puppeteer/puppeteer/pull/10021)  and unfortunately wasn't marked as a breaking change and so is in scope of the current version designation of the puppeteer package.

The breakage is caused by these lines:
https://github.com/modernweb-dev/web/blob/e0d362fcdbedf6a72a6c78ebc2e3a3cffa922dbc/packages/test-runner-commands/src/sendMousePlugin.ts#L170

In latest versions of puppeteer, it's an error to call `up` if the mouse button is not actually pressed.

Users can implement their own reset commands to compensate (based on actual use) but I think the only easy common reset implementation would be to use `try...catch` to prevent bubbling expected errors.

**Comment by dlockhart** [comment]
I'm seeing this as well. Another alternative solution perhaps: track whether the 3 mouse buttons are up or down and then `reset-mouse` would only call `mouse.up` for the ones that require it.

**Comment by web-padawan** [comment]
Update: the last working version is `19.9.0` and the change was introduced in [19.9.1](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v19.9.1).

**Comment by melink14** [comment]
The reset command was added in https://github.com/puppeteer/puppeteer/pull/10340 and it looks like it's been released since [puppeteer-core: v20.7.3](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v20.7.3) and [browsers: v1.4.2](https://github.com/puppeteer/puppeteer/releases/tag/browsers-v1.4.2) so I think this problem could be fixed with another update to those deps and then chaning the commands code to use `reset` instead of manually calling the mouse commands.

I guess since the deps are new major versions (some sort of breaking change) then it would mean the modernweb package would also need a new major version?

**Comment by web-padawan** [comment]
> it would mean the modernweb package would also need a new major version?

Yes, we probably should update to these versions and use `await page.mouse.reset()` directly.
This would mean releasing `@web/test-runner-commands` version `0.8.0` due to major bump.
