### ISSUE TITLE
Is it possible to, instead of having `@web/test-runner` build / compile anything, to point at a running vite server?

### ISSUE THREAD

**Issue by NullVoxPopuli** [modernweb-dev/web#2271]
For development, I think it'd be best to integrate with a running vite server, as vite is really good at what it does.

For ci, I think it'd be fine to load and run tests from dist-output.

_but_,

is this possible?
how is test-progress reported?
I already have a test-framework, and already know that I'd need to report success/failure for each test [via these docs](https://modern-web.dev/docs/test-runner/test-frameworks/write-your-own/)

**Comment by thepassle** [comment]
Web test runner doesnt build or compile anything by default. If you want to integrate with vite you can google “web test runner vite” and youll find multiple plugins
