### ISSUE TITLE
[dev-server-storybook 0.7.1] build-storybook Error: Cannot find module 'rollup-plugin-terser'

### ISSUE THREAD

**Issue by zanfirandra** [modernweb-dev/web#2279]
Hello, I am using the latest version of @web/dev-server-storybook and when running `build-storybook` I am facing this error : `Cannot find module 'rollup-plugin-terser'`. 

After checking the changelog I saw that you replaced `rollup-plugin-terser` with `@rollup/plugin-terser`  and after some digging I found out that the import here in this file [dev-server-storybook/src/build/rollup/createRollupConfig.ts](https://github.com/modernweb-dev/web/blob/ca87c9bc78670e8172e7dfff74c4f0909d59e5ca/packages/dev-server-storybook/src/build/rollup/createRollupConfig.ts) is using the `rollup-plugin-terser` not the new one `@rollup/plugin-terser` .

**Comment by jholt1** [comment]
Related issue: https://github.com/modernweb-dev/web/issues/2261

**Comment by thepassle** [comment]
this should be fixed in https://github.com/modernweb-dev/web/pull/2265
