### ISSUE TITLE
Update to pupeteer 20.x to resolve download behind proxy issues

### ISSUE THREAD

**Issue by wapophis** [modernweb-dev/web#2282]
We're having issues trying to download the chrome-browser with proper proxy configuration. Seems like pupeteer 19.x have issues working behind proxy which affect us, with download code error, because this bugs in pupeteer 19.x. After upgrading pupeteer to 20.x the bugs are gone, but our projects has dependency with @web/test-runner-puppeteer which resolve to 19.x.

**Comment by Westbrook** [comment]
We'd love to accept a PR in this area. Could we interest you in a contribution?
