### ISSUE TITLE
[test-runner] It isn't clear how to get TypeScript files working in test-runner

### ISSUE THREAD

**Issue by trusktr** [modernweb-dev/web#2286]
I followed the docs starting here:

https://modern-web.dev/docs/test-runner/plugins/

I proceded to click on "esbuild" in the list, which led me to this:

https://modern-web.dev/docs/dev-server/plugins/esbuild/

Based on that,

- I installed `@web/dev-server-esbuild`,
- converted my test file to a `.ts` file extension,
- added a file `web-dev-server.config.js` in my `type:module` project with the contents shown in that doc,
- and finally proceeded to run `web-test-runner tests/browser/*.ts --node-resolve`

This results in an error:

```
 🚧 Browser logs:
      TypeError: Failed to fetch dynamically imported module: http://localhost:8000/tests/browser/test.ts?wtr-session-id=ru_1vYXAaJpd6nAoONAft
```

There's something missing from the docs.

Several other people reported a similar error, possibly related:

https://github.com/FredKSchott/snowpack/issues/3796

**Comment by trusktr** [comment]
Ok, the issue is that the docs state to create a `web-dev-server.config.js` file, but actually we need to create a `web-test-runner.config.js` file.

This example,

https://github.com/modernweb-dev/example-projects/tree/master/preact-tsx

shows two files.

**Comment by pappnase99** [comment]
Ran into the same issue, I think in my case the problem came from me trying out the test runner in a CommonJS project, so the config probably had the wrong format. Error messages regarding the config file need improvement.

**Comment by trusktr** [comment]
Lately, I keep things simple:

- built typescript separately, f.e. from `src/` to `dist/` (including `src/**/*.test.ts` files, and list those in `.npmignore` to avoid publishing them, or don't exclude them in package.json's `files`)
  - You can run this in watch mode separately, etc. More control.
- run vanilla `@web/test-runner` without a build, as vanilla ES Modules, on `dist/**/*.test.js` files. 🎉 
  - You can run this in watch mode separately too, and it will re-run tests when the dist files change.

Nice and simple, not introducing build tools (no esbuild). 🎉

**Comment by luke-kanina** [comment]
Ran into the same error. Turned out to be that I had the web-test-runner.config.mjs file inside the src folder instead of the project's root folder.
