### ISSUE TITLE
[dev-server] Incorrect resolution for tslib: .js extension added to .mjs file

### ISSUE THREAD

**Issue by justinfagnani** [modernweb-dev/web#2291]
tslib 2.5.3 changed their package exports in a way that seems to be tripping up WDS, which is adding an extra `.js` extension to a `tslib.es6.mjs` file, causing it to be not found.

`'tslib'` is getting resolved to `'http://localhost:3400/__wds-outside-root__/2/node_modules/tslib/tslib.es6.mjs.js'` but there is no `tslib.es6.mjs.js`, just a `tslib.es6.mjs` - the `.js` is being added.

I tried to reproduce the issue with just `@rollup/plugin-node-resolve`, but it's resolving the file correctly with `tslib@2.5.3`, so it seems like this might be a problem with WDS: https://stackblitz.com/edit/rollup-repro-ddkfxf?file=rollup.config.js

**Comment by thepassle** [comment]
Im unable to reproduce

![image](https://github.com/modernweb-dev/web/assets/17054057/705eeabb-7939-4fe6-b368-ca65428e85af)

**Comment by justinfagnani** [comment]
I've been unable to reproduce this. Closing.
