### ISSUE TITLE
using @web/test-runner-chrome how to handle aliases (absolute imports)

### ISSUE THREAD

**Issue by niko-cxvedadze** [modernweb-dev/web#2293]
I am using @web/test-runner-chrome for lit project and, on the other hand for development processes and production bundle, I am using webpack which have aliases  
` resolve: {
            alias: {
                "@app" : path.resolve(__dirname,'./app')
            }
},`

when I am using component which is importing other components with webpack aliases its throws me import error 

My config file looks like 
`

const Config = {
    nodeResolve: true,
    files: ['./test/**/*.test.js'],

    testRunnerHtml: test => {
        // language=HTML
        return `
            <html>
            <body>
            <script type="module" src="${test}"></script>
            </body>
            </html>`;
    },
    watch: false,

};
`

**Comment by thepassle** [comment]
You can write a custom plugin for this, to resolve "from"/"to" a different source: https://modern-web.dev/docs/dev-server/writing-plugins/hooks/

Or find an existing koa plugin that already does this
