### ISSUE TITLE
[test-runner-chrome] code coverage broken

### ISSUE THREAD

**Issue by tmsns** [modernweb-dev/web#2302]
Hello,

It seems code coverage is broken since the release of @web/test-runner-chrome 0.13.1. It even doesn't fail when running tests. Code coverage seems to be aborted and not done anymore at all.

Expected result:
![image](https://github.com/modernweb-dev/web/assets/17364880/feb77e67-fcc0-44a5-8a6a-f301d6a64fe8)

Current result:
![image](https://github.com/modernweb-dev/web/assets/17364880/7e78c9f2-a143-4460-a834-b8aecf3565a9)

Notice the line numbers. We get the `TypeError` for every source file for which code coverage should be calculated.

**Comment by tmsns** [comment]
If I read the error, it seems that `LruCache` needs to have the `sizeCalculation` or `size` set, now that `maxSize` is being used in the `cachedSources`.
![image](https://github.com/modernweb-dev/web/assets/17364880/9213c346-6084-4a1d-9ebe-947f8f470304)

**Comment by tmsns** [comment]
Passing a `sizeCalculation()` function in the constructor of `LruCache` seems to solve the issue:
![image](https://github.com/modernweb-dev/web/assets/17364880/1894679f-1f2f-4f4e-8c83-d34d06e20c08)

**Comment by 43081j** [comment]
Very strange that this didn't get picked up in tests. We ran the coverage against some fairly big repos and got results. No idea how that's possible because I think you are indeed correct! 

If you can open a pr with the change that would be much appreciated. I'll try it locally too
