### ISSUE TITLE
Incorrect printing of file path that fails test

### ISSUE THREAD

**Issue by UpperCod** [modernweb-dev/web#236]
Hi, Thanks for this tool, I'm migrating from karma to @web/test-runner, I will use it as a test runner for [Atomico](https://github.com/atomicojs/atomico).

Incorrect printing of file path that fails test.

**Desktop** : window 10

**Node** : 14.5.0 

**console**

```bash
❌ vdom attribute class
      at: src\tests\D:\Cloud\Git\@atomico\core\src\tests\render.test.jsx     
      error: expected 'any' to equal 'any.'
      + expected - actual

      -any
      +any.
```

> expected path `at: D:\Cloud\Git\@atomico\core\src\tests\render.test.jsx    `

**web-test-runner.config.js**

```js
const { esbuildPlugin } = require("@web/dev-server-esbuild");

module.exports = {
    rootDir: "../../..",
    nodeResolve: true,
    plugins: [
        esbuildPlugin({ jsx: true, jsxFactory: "h", jsxFragment: "Fragment" }),
    ],
};
```

**pkg.scripts**
```json
{
    "test:w": "web-test-runner src/**/*.test.{js,jsx} --watch",
}
```

**Comment by LarsDenBakker** [comment]
Looks like a typical windows pathing issue :) How are you running the tests? Are you using WSL, powershell etc.?

**Comment by LarsDenBakker** [comment]
Looks like it was an issue on unix as well, related to inline source maps generated by esbuild.
