### ISSUE TITLE
Allow to override nodeResolve exportConditions development in the dev server

### ISSUE THREAD

**Issue by remcovaes** [modernweb-dev/web#2413]
I want to be able to override the `{ exportConditions: [ 'development' ] }` of the node resolve plugin.

Currently a deep merge is happening while constructing the node resolve config. See: https://github.com/modernweb-dev/web/blob/7bd56e11d593c446649f6261f2893fc5da7963d1/packages/dev-server/src/plugins/nodeResolvePlugin.ts#L11C45-L11C54

This deep merge also deep merges arrays. Which means that:
```
{ exportConditions: [ 'default' ] }
```
becomes
```
{ exportConditions: [ 'development',  'default' ] }
```
The only workaround to get rid of development in that array is to add a string (`{ exportConditions: 'no-deeomerge'] }`). In the end the node resolve plugin will then fall back to its default.

The reason I need this is that the project I am currently working on is not running properly with lit in development mode (which is a different issue that needs to be fixed).

**Comment by thepassle** [comment]
Yeah thats a fair point, would you be willing to create a PR for this?

**Comment by remcovaes** [comment]
I am not sure what the correct solution would be, because changing deep merge to override arrays instead of merging them also has impact on the other arrays. Which, I guess, would be a breaking change.
