### ISSUE TITLE
dev server as a module -- still possible?

### ISSUE THREAD

**Issue by mercmobily** [modernweb-dev/web#243]
Hi,

Is es-dev-server being replaced?
If it is, can I humbly ask to make sure whatever it is replaced with, it will still be possible to use it as a module?
I use es-dev-server as part of a bigger server, with defined routes etc.
I am actually using express, but luckily Koa has `callback()` which acts as a bridge to Express.
This is the current code I am using for this -- it took me a while to make it all work well, and I now live in fear of you moving on from es-dev-server :D

````
const fs = require('fs')
const vars = require('./vars')
const express = require('express')
const esDevServer = require('es-dev-server')

exports = module.exports = function (app) {
  function safeConfigOutput (o) {
    o = { ...o }
    delete o.db.dbPassword
    return o
  }

  const serveBuilt = process.env.SERVE_BUILT

  // Show what environment is running
  console.log('Running application as:', process.env.NODE_ENV || 'development')
  console.log('Config:\n', safeConfigOutput(vars.config))

  // Serve the built version EITHER if it's a non-dev environments OR if serveBuilt is set
  if (serveBuilt) {
    const root = 'server/dist'
    app.use(express.static(root))
    app.use((req, res, next) => {
      if ((req.method === 'GET' || req.method === 'HEAD') && req.accepts('html')) {
        res.sendFile('index.html', { root }, err => err && next())
      } else next()
    })

    // Serve the local unbuilt directory using esDevServer as a middleware
  } else {
    if (fs.existsSync('distributed')) {
      console.error('ERROR: cannot serve unbuilt directory from distributed environment')
      process.exit(99)
    }

    const Koa = require('koa')
    const config = esDevServer.createConfig({
      nodeResolve: true,
      appIndex: 'index.html',
      moduleDirs: ['node_modules'],
      preserveSymlinks: true
    })
    const middlewares = esDevServer.createMiddlewares(config)
    const koaApp = new Koa()
    middlewares.forEach(middleware => {
      koaApp.use(middleware)
    })

    app.use(koaApp.callback())
  }
}
````

**Comment by LarsDenBakker** [comment]
We're indeed working on `@web/dev-server`, the successor of es-dev-server. It will be more modular, and easier to plug into different parts. Let's close this issue for now, when it's released we can look into whether it works for your use case and otherwise discuss improvements.

**Comment by mercmobily** [comment]
OK perfect. Thanks for listening! The main -- and in fact only -- thing is
to make sure that it can be used as Express middleware.
If I can say anything, it would be nice for it to expose the Express
interface directly, rather than having to use Koa's `callback()`

Thank you for being awesome!
