### ISSUE TITLE
[dev-server] Types don't resolve with JS module imports

### ISSUE THREAD

**Issue by justinfagnani** [modernweb-dev/web#2444]
See the report from https://arethetypeswrong.github.io/?p=%40web%2Fdev-server%400.3.1

I think it's because there are exports, but no `types` condition.

edit: `@web/dev-server-core` has even more errors: https://arethetypeswrong.github.io/?p=%40web%2Fdev-server-core%400.5.2

**Comment by koddsson** [comment]
I messed around with the `"exports"` key locally and the `arethetypeswrong` CLI but couldn't figure out how to get it to run green. I thought at least for `dev-server` we just needed the `types` key but setting it explicitly didn't change anything for me 🤔

**Comment by tmsns** [comment]
I was able to make it work:
- for `@web/dev-server-core`: just added a `types` condition
- for `@web/dev-server-core`: added a `types` condition, but also renamed `index.d.mts` to `index.d.ts`

Want me to submit a PR for this?
