### ISSUE TITLE
[web-test-runner] Expose the DevTools protocol URL

### ISSUE THREAD

**Issue by jackfranklin** [modernweb-dev/web#245]
When you run Chrome with the `--remote-debugging-port=X` flag (as Puppeteer does), you get a line logged to stderr that says:

`DevTools listing on ...`

(You can see the code Puppeteer uses to pull this out: https://github.com/puppeteer/puppeteer/blob/main/src/node/BrowserRunner.ts#L246).

This is then stored in Puppeteer as `browser._connection.url()`. It would be really handy if wtr could expose this somehow to the test suites. We'd like to write unit tests for Puppeteer using wtr (so we can test our Puppeteer in the browser functionality) but without having access to this URL we can't instantiate Puppeteer and connect it to the right socket to enable us to send/receive CDP methods.

I recognise this request is maybe a bit bespoke for Puppeteer, but providing some utility method to expose the URL from the underlying `browser` instance that wtr has created would be super useful.  

Let me know what you think!

**Comment by LarsDenBakker** [comment]
I've been thinking about a way where a test could communicate with the browser launcher from the browser, something like:

```js
import { connection } from '@web/test-runner-runtime/puppeteer.js';

```

There we could expose specific functions and variables for each browser launcher. The connection variable I think is private though, and not exposed in the types. 

Another option I think could work right now is to pass the port command line flag:

```js
const { chromeLauncher } = require('@web/test-runner');

module.exports = {
  browsers: [chromeLauncher({ launchOptions: { args: ['--remote-debugging-port=1234'] } })],
};
```

Does puppeteer honor this flag? You could then share this port between the browser and the test runner. Test runner configs can also be written in native es modules, so you could share a constant for the port between the tests and the config.

**Comment by LarsDenBakker** [comment]
Looks like just the port isn't enough. After thinking about this a bit, I decided to add a `createPage` option which allows customizing the page which is created and allows interaction with the puppeteer `Browser` and `Page` instance. 

Adding this to the config should make it work for your case:

```js
const { chromeLauncher } = require('@web/test-runner-chrome');

module.exports = {
  browsers: [
    chromeLauncher({
      async createPage({ browser }) {
        const page = await browser.newPage();

        page.evaluateOnNewDocument(wsEndpoint => {
          window.__ENV__ = { wsEndpoint };
        }, browser.wsEndpoint());

        return page;
      },
    }),
  ],
};
```

**Comment by jackfranklin** [comment]
@LarsDenBakker thanks for this! I'll give this a go and let you know.
