### ISSUE TITLE
Only report browser logs for failed sessions

### ISSUE THREAD

**Issue by jasonmobley** [modernweb-dev/web#2450]
I'd like to be able to use the default reporter but have it only report the browser logs in the terminal output for failed sessions. We run a lot of test files at once, and we have test files that produce quite a few error and warning level log entries even for tests that pass. When the tests are passing fine, all that log content is just noise that I'd rather not see. It's kinda similar to how the default reporter doesn't print the name of each individual test that _passes_ ... only the failures are shown.

I could probably implement this myself via [filterBrowserLogs](https://github.com/modernweb-dev/web/blob/033b302c5f70edb1dc0b67e162c62b32c99db034/packages/test-runner-core/src/config/TestRunnerCoreConfig.ts#L49) if the result were passed into the filter function, e.g.

```
export default {
  ...
  filterBrowserLogs: ({ log: type, args: any[] }, session) => {
    return !session.passed;
  },
  ...
}
```

**Comment by koddsson** [comment]
> I could probably implement this myself via [filterBrowserLogs](https://github.com/modernweb-dev/web/blob/033b302c5f70edb1dc0b67e162c62b32c99db034/packages/test-runner-core/src/config/TestRunnerCoreConfig.ts#L49) if the result were passed into the filter function, e.g.

This sounds like the bst way to solve this I think.

**Comment by jasonmobley** [comment]
@koddsson see PR #2476

**Comment by koddsson** [comment]
Closing this as fixed!
