### ISSUE TITLE
WDS as Middleware with refresh on file change.

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#2471]
When WDS is a middleware, it will spin up an `app` but not a `server`. Without a `server` it cannot leverage web sockets in order to refresh the page when there are file changes:
```
Error: Cannot use watch mode when web sockets are disabled.
```
When leveraging `@web/storybook-builder` and `@web/storybook-framework-web-components`, WDS is started up as a middleware, which means it disallows `watch` and this update mechanism. Does that mean we need some added setting in Storybook in order to trigger refresh, or is there something else missing here?

@bashmish maybe you have thoughts?

**Comment by Westbrook** [comment]
Locally I can hack the configs to pass the `devServer` from Storybook to `new DevServer()` in `startDevServer.js`, and it _will_ allow for refreshing the page, but only up until some React error that that causes crashes the page. 🤔

**Comment by bashmish** [comment]
IIRC it required more logic and integration code for the Storybook, so I made a separate task in the future and focused on basic functionality. It's still planned.

Meanwhile I'm curious what exactly you expect to work?
Some sort of HMR? Or just page refresh?

**Comment by Westbrook** [comment]
The baseline would be auto page refresh much like WDS does in other cases with
```
webSockets.sendImport('data:text/javascript,window.location.reload()');
```
I'm not one for a lot of ceremony on this, but being we've received it in so many other contexts, it's hard to get away from this sort of a feature when suggesting tools like this to a team.

It would be interesting to see actual HMR included...but, I've never seen it _really_ work, so it wouldn't be me pushing for it by any means. I'm not even sure if the HMR tools that OpenWC was working with ever actually got updated to `lit@2.0` let alone the upcoming `lit@3.0` release.

Practically, the `vite` builder accepts the Storybook `devServer` into its config, so there is likely a path to make the baseline of what I was trying work, I just don't know how to debug the issue that it causes in Storybook's React UI. 😞

**Comment by bashmish** [comment]
@Westbrook thanks for your feedback. I agree we need to implement the baseline, I think the previous storybook-prebuilt setup had smth like that, and also not a real HMR. I hope to pick this up soon.

**Comment by Westbrook** [comment]
This seems like the laziest possible path: https://github.com/modernweb-dev/web/pull/2482
