### ISSUE TITLE
[rollup-plugin-import-meta-assets] Support bundling of JavaScript files

### ISSUE THREAD

**Issue by mmomtchev** [modernweb-dev/web#2504]
Currently `rollup-plugin-import-meta-assets` copies files without processing them (or by eventually applying a user-supplied transformation with `transform`).

One of the uses of this feature is to be able to bundle web workers - which contain JavaScript and should also be processed by `rollup` - bundling their own dependencies.

**Comment by RReverser** [comment]
Just to copy what I said in another issue, there is a separate plugin for Web Workers: https://github.com/surma/rollup-plugin-off-main-thread
