### ISSUE TITLE
How to run wtr programmatically?

### ISSUE THREAD

**Issue by robertsLando** [modernweb-dev/web#2517]
In order to test my package (MQTT.js) I firsty need to start an MQTT broker that exposes websockets on a port and then run the tests on the browser. I have successfully write a test but now I would like to know how I to create a `run-tests.js` script that uses wtr to spawn tests programmatically so in the same script I can firstly start the server and then spawn the test.

See: https://github.com/mqttjs/MQTT.js/pull/1722

I'm also wondering why here: 

https://github.com/mqttjs/MQTT.js/pull/1722/files#diff-c284c6172daa765407baf7c1d8cf0a2657b6d84fa9ae651627a3b8a394e7a431R1

The only way I found to import `expect` from `chai` is that, importing it like: 

```js
import { expect } from '../../node_modules/@esm-bundle/chai/esm/chai.js';
```

Doesn't works, it throws:

```
 🚧 Browser logs:
      TypeError: Failed to resolve module specifier "@esm-bundle/chai". Relative references must start with either "/", "./", or "../".
        at node_modules/@web/test-runner-mocha/dist/autorun.js:1:267424
```

 Notice that node resolve is true in [configuration](https://github.com/mqttjs/MQTT.js/pull/1722/files#diff-7bfdd444e5650854e7536869ef3973956e89fbfc8562197c7c13f99cfb3047bfR10)

**Comment by trusktr** [comment]
I'm not sure what's up in your particular case, but one solution/workaround can be to turn off nodeResolve, and just set up import maps, which eliminates some surface area for error (f.e. if there's a bug with `nodeResolve` or something).

Here's a sample from my project (with added comments in UPPPERCASE):

```js
	// We're using vanilla ES Modules, not automatic Node-based module
	// resolution, only import maps. Yeah baby! Embrace the platform!
	nodeResolve: false,
	plugins: [
		importMapsPlugin({
			inject: {
				// INSERT IMPORT MAP HERE
				importMap: {
					imports: {
						"@esm-bundle/chai": "/node_modules/@esm-bundle/chai/esm/chai.js"
						// ...elided...
					},
					scopes: {
						// ...elided...
					},
				},
			},
		}),
	],

	testRunnerHtml: testFramework => /*html*/ `
		<html>
			<body>
				<!-- OR INSERT IMPORT MAP HERE, f.e.
				<script type="importmap">...</script>
				-->
				
				<!-- ...elided... -->

				<script type="module" src="${testFramework}"></script>
			</body>
		</html>
	`,
```

And additionally if you provide `.html` files as test files, they can have their own import maps.

The `importMapsPlugin` will inject the given import map in _all_ `.html` files (including the `testRunnerHtml` HTML).

> [!Note]
> I haven't tested what happens if you have both an import map in a `.html` file and `importMapsPlugin` also injecting an import map into it. Browsers support only one import map at a time, so `importMapsPlugin` would have to be smart enough to merge into the pre-existing map, or else it just won't work. I'm guessing it'll need to be a choice between one or the other.

**Comment by robertsLando** [comment]
@trusktr Thanks for the proposed solution, anyway for now I think that importing chai in the way I'm doing right now it's much more easier. The open question remains how to programmatically call wtr from now

**Comment by bearfriend** [comment]
You could simply start an appropriate child process to run the command you need. This may be the better option, and certainly would be a better supported use. If you insist, though, it's just:
```javascript
import { startTestRunner } from '@web/test-runner';
startTestRunner(options);
```

You'll have to dig through the code to better understand the usage.

**Comment by robertsLando** [comment]
@bearfriend could this be considered a feature request? I mean like adding a "setup()" function on wtr config that is called right before test are runned? It can be async and/or accept a "done" callback. 

I think this will make it easier to work with wtr, it also could be nice to be able to access the server instance created by wtr.

Another question: I would like to test my module both with http and https, how can I spawn wtr tests in https? I cannot find docs about that

**Comment by bashmish** [comment]
Can you use Top-Level Await in the WRT config file to setup things before exporting the config? In MJS files it should be possible on latest Node.

**Comment by robertsLando** [comment]
@bashmish yeah this is what I ended up doing: https://github.com/mqttjs/MQTT.js/pull/1722/files#diff-7bfdd444e5650854e7536869ef3973956e89fbfc8562197c7c13f99cfb3047bfR5

What's still missing now is: 

> I would like to test my module both with http and https, how can I spawn wtr tests in https? I cannot find docs about that

Any hints for that?

**Comment by bashmish** [comment]
Then I think Top Level Await solves this in a pretty elegant way, so I'd rather rely on it instead of introducing some additional API in WTR.

As for HTTPS support, I'm not sure we support this.
Can you please raise another issue with such a request please?

This issue can be close then I think, right?

**Comment by bashmish** [comment]
@robertsLando actually, maybe no need to create another issue.

We do support HTTPS by using `http2` flag. Just add `http2: true` to your config, and `sslKey` and `sslCert` if needed. This is documented only in WDS though: 

```
export interface TestRunnerCoreConfig {
  // ...
  http2?: boolean;
  sslKey?: string;
  sslCert?: string;
  // ...
}
```

**Comment by bashmish** [comment]
> There is still this problem:
> 
> The only way I found to import `expect` from `chai` is that, importing it like:
> 
> ```js
> import { expect } from '../../node_modules/@esm-bundle/chai/esm/chai.js';
> ```
> 
> Doesn't works, it throws:
> 
> ```
>  🚧 Browser logs:
>       TypeError: Failed to resolve module specifier "@esm-bundle/chai". Relative references must start with either "/", "./", or "../".
>         at node_modules/@web/test-runner-mocha/dist/autorun.js:1:267424
> ```
> 
> The only way I fouund to make it work is: https://github.com/mqttjs/MQTT.js/pull/1722/files#diff-c284c6172daa765407baf7c1d8cf0a2657b6d84fa9ae651627a3b8a394e7a431R1
> 
> > Can you please raise another issue with such a request please?
> 
> Sure.

According to https://modern-web.dev/docs/test-runner/writing-tests/helper-libraries/#assertions you should be able to import like this

```js
import { expect } from '@esm-bundle/chai';
```

**Comment by robertsLando** [comment]
> We do support HTTPS by using http2 flag. Just add http2: true to your config, and sslKey and sslCert if needed. This is documented only in WDS though:

What about mixed content errors? I mean if I try to connect to wss from an http and/or viceversa? is there some playwright argument to pass to ignore those security errors?

Thanks for the support 🙏🏼

**Comment by bashmish** [comment]
> > We do support HTTPS by using http2 flag. Just add http2: true to your config, and sslKey and sslCert if needed. This is documented only in WDS though:
> 
> What about mixed content errors? I mean if I try to connect to wss from an http and/or viceversa? is there some playwright argument to pass to ignore those security errors?
> 
> Thanks for the support 🙏🏼

I suggest to discuss this in another issue which you have already opend. This issue becomes more of a chat :)
Ideally we'd like to see separate issues for individual problems you are facing.

**Comment by robertsLando** [comment]
Agree, sorry for that but I found the issues one after the other
