### ISSUE TITLE
[test-runner-cli] investigate globbing libraries

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#253]
I'm seeing some weird behavior with the globbing library, where a pattern like `test/**/*.test.js` will match only a single directory at once. We should investigate this and possible alternatives. All globbing patterns across the different libraries we use should be consistent.

**Comment by LarsDenBakker** [comment]
Also seeing different behavior between windows and unix, which is not ok.

**Comment by LarsDenBakker** [comment]
This turned out to be a problem with escaping the glob in the package.json

**Comment by SamSverko** [comment]
> This turned out to be a problem with escaping the glob in the package.json

Solution when using CLI arguments: Wrap the directory inside quotes (`''`): `wtr 'src/**/*.test.ts'`

Omitting the quotes will have only one directory run the tests.
