### ISSUE TITLE
bumping @web/dev-server-esbuild to 1.0.0 leads to "SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by Th3S4mur41** [modernweb-dev/web#2537]
Bumping @web/dev-server-esbuild from 0.4.0 to 1.0.0 lead to every single [web component using LitElement](https://lit.dev/docs/components/overview/) test to fail with the following error:

>  🚧 Browser logs:
>       SyntaxError: Invalid or unexpected token
> 
>  ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information.

Any idea what might be the root cause of the issue and how to fix it?

**Comment by bashmish** [comment]
Maybe you need to bump other `@web/*` dependencies too? We transitioned to Node ESM recently, so maybe other dependencies need to be updated too to make it work correctly.

**Comment by Th3S4mur41** [comment]
@bashmish that was my first thought as well, but all other `@web/*` dependencies are up to date.

```json
"@web/dev-server": "^0.4.0",
"@web/dev-server-esbuild": "^1.0.0",
"@web/test-runner": "^0.18.0",
"@web/test-runner-playwright": "^0.11.0",
```

**Comment by bashmish** [comment]
Ok.

I see we updated the esbuild version in 1.x.x https://github.com/modernweb-dev/web/pull/2531
Actual change made in this PR https://github.com/modernweb-dev/web/pull/2420

Maybe related to this? But I see we had tests checking if it works and they should pass, so smth in your setup in different that breaks it.

**Comment by Th3S4mur41** [comment]
It might take me some time to create a demo repo for this... In the meantime, here is an example of a simple component and its specs throwing the error.
Hopefully, that can already help identify the error.

```ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('my-icon')
export class IconComponent extends LitElement {
	constructor() {
		super();
		this.icon = '';
		this.title = 'title';
		this.path = 'sprite.svg';
		this.viewBox = '0 0 256 256';
	}

	// @property({ attribute: 'icon', type: String })
	declare icon: string;
	// @property({ attribute: 'title', type: String })
	declare title: string;
	// @property({ attribute: 'path', type: String })
	declare path: string;
	// @property({ attribute: 'view-box', type: String })
	declare viewBox: string;

	/**
	 * These styling will be applied to the svg element.
	 * If the '--icon-color' variable is set, the color of the icon will be changed,
	 * otherwise the container element color will be used by default.
	 */
	static override styles = css`
    svg {
      --_icon-color: var(--icon-color);
      fill: var(--_icon-color, currentcolor);
    }
  `;

	override render() {
		return html`<svg role="img" aria-labelledby="svgTitleId" viewBox="${this.viewBox}">
            			<title id="svgTitleId">${this.title}</title>
            			<use href="${this.path}#${this.icon}"></use>
          			</svg>`;
	}
}
```

```ts
import '../src/icon-component.ts';
import { fixture, fixtureCleanup, html, expect } from '@open-wc/testing';
// eslint-disable-next-line no-duplicate-imports
import { IconComponent } from '../src/icon-component';

describe('Icon Web Component ', () => {
	const spritePath = 'sprite.svg';

	afterEach(function () {
		fixtureCleanup();
	});

	it('Icon component should be properly rendered', async () => {
		const el: IconComponent = await fixture(
			html` <my-icon icon=${'activity'} title=${'Test label'} path=${spritePath}></my-icon>`
		);

		const svg = el.shadowRoot?.querySelector('svg');
		const title = el.shadowRoot?.querySelector('title');

		expect(svg)?.to.have.attribute('aria-labelledby');
		expect(svg)?.to.have.attribute('role').equal('img');
		expect(title).to.exist;
	});
});

```

**Comment by koddsson** [comment]
Yo! 

@Th3S4mur41 @tony @bashmish 

Check the ["Major Changes" (which should be breaking changes) in the release notes for the plugin](https://github.com/modernweb-dev/web/releases/tag/%40web%2Fdev-server-esbuild@1.0.0). It reads:

>ESBuild has changed how TypeScript decorators are enabled in preparation for JavaScript decorators to land in browsers. ESBuild now requires the experimentalDecorators key to be set to true in the tsconfig.json for TypeScript decorators to be enabled.
>
>If you are having issues with decorators after updating to this version, try setting the experimentalDecorators key in your tsconfig.json.

I tried chucking `"experimentalDecorators": true` to my `tsconfig.json` and it fixed the issue with the given reproduction code.

Read more about the options here: https://www.typescriptlang.org/tsconfig#experimentalDecorators.

**Comment by koddsson** [comment]
I also needed to make sure I passed a reference to the `tsconfig.json` file in the web-test-runner config file. See how to do that here: https://modern-web.dev/docs/dev-server/plugins/esbuild/

**Comment by koddsson** [comment]
Nice! It's a bit unwieldy right now but maybe we can make some changes to make it better in the future. Glad we got this solved, I'll close this for now but feel free to re-ping this if things are still broken.

**Comment by Th3S4mur41** [comment]
> I also needed to make sure I passed a reference to the `tsconfig.json` file in the web-test-runner config file. See how to do that here: https://modern-web.dev/docs/dev-server/plugins/esbuild/

Thanks @koddsson
tsconfig already had `"experimentalDecorators": true` set, but passing the tsconfig to esbuild solved the issue 👍
