### ISSUE TITLE
TypeError: Failed to resolve module specifier "@esm-bundle/chai"

### ISSUE THREAD

**Issue by robertsLando** [modernweb-dev/web#2539]
Importing it like shown on docs: 

```js
import { expect } from '@esm-bundle/chai';
```

Doesn't works, throws:

```
 🚧 Browser logs:
      TypeError: Failed to resolve module specifier "@esm-bundle/chai". Relative references must start with either "/", "./", or "../".
        at node_modules/@web/test-runner-mocha/dist/autorun.js:1:267424
```

The only way I found to import `expect` from `chai` is that, importing it like: 

```js
import { expect } from '../../node_modules/@esm-bundle/chai/esm/chai.js';
```

**Comment by bashmish** [comment]
Did you install `@esm-bundle/chai`?

I use this myself in e.g. https://github.com/bashmish/carehtml/blob/main/src/wrap.spec.js, never had such an issue.

**Comment by robertsLando** [comment]
It's there: https://github.com/mqttjs/MQTT.js/pull/1722/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R122

**Comment by bashmish** [comment]
Weird. I'm afraid I have to ask you to provide a minimum reproduction code here too since this is pretty trivial code and should just work, and the error log doesn't really help. Might be smth related yo your specific setup, so an excercise of removing different code/dependencies one by one might help to find what breaks it.

**Comment by robertsLando** [comment]
Here is the smallest possible repro: https://github.com/robertsLando/wtr-bug-test

**Comment by bashmish** [comment]
looks like `nodeResolve: true` is not working

**Comment by bashmish** [comment]
you have a typo
`nodeResove`
`nodeResolve` - this is correct

**Comment by robertsLando** [comment]
ooooohh sh** that's embarrassing... sorry for wasting your time with this, can't say how much I love typescript for this reasons...
