### ISSUE TITLE
Used Puppeteer version is deprecated

### ISSUE THREAD

**Issue by Sanderovich** [modernweb-dev/web#2646]
I am running into the issue that @web/test-runner-puppeteer only supports Puppeteer version 20.x, which means it is running Chrome version 115. Therefore, I am not able to automatically test my package on the latest version of Chrome (version 121 at the time of writing). Additionally, Puppeteer deprecated all versions lower than 21.5.0.
```bash
npm WARN deprecated puppeteer@20.0.0: < 21.5.0 is no longer supported
```

For now, I force web-test-runner to use the newest Puppeteer by adding `overrides` to my `package.json`.
```json
"overrides": {
    "puppeteer": "22.1.0"
  }
```

To continue, I could not find upcoming plans to start updating Puppeteer or a reason for why Puppeteer is not updated yet, so I made a pull request to update Puppeteer to its latest major (See #2647).

**Comment by web-padawan** [comment]
Fixed by #2647 and released in `@web/test-runner-puppeteer` 0.16.0 (for some reason this issue wasn't closed).
