### ISSUE TITLE
[test-runner] Unexpected 'exclude' usage

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#265]
In `karma` I'd use
```
                coverageExclude: [
                    'packages/*/stories/*',
                    'packages/icons-ui/*',
                    'packages/icons-workflow/*',
                ],
```
And, I figured that I could just copy that over...not so much. I need to use
```
exclude: [
    '**/stories/**',
    '**/icons-ui/**',
    '**/icons-workflow/**
]
```
And, it seems to be because the tooling is only comparing the actual request path of the files at test, not the resolution of that file to its source. This wouldn't be an issue, but the test coverage reporting lists the source URL, which could be confusing. That is to say, a file would be listed as `packages/icons-ui/src/index.ts` in the output, but is actually tested as (likely) `node_modules/@spectrum-web-components/icons-ui/lib/index.js`.

I'm not sure whether this counts as a divergence enough to address functionally or not, but it certainly should be documented if we choose not to.

**Comment by LarsDenBakker** [comment]
I compared some different matching libraries across windows and unix, and looked into how other libraries are handling it. We will can karma and rollup's behaviour here, and prefix the current working directory if the pattern does not start with a *. 

However, I'm not 100% sure about the single `*` you're using. Do you intend to match files a single directory deep? With the changed I made, do you still see a difference in behavior?

**Comment by Westbrook** [comment]
With some of our conversations and my own deeper investment in understanding blobs for this, I'm not 100% sure why that worked previously. I wonder if Karma was also adding a `*` to the end of the string?

With the most recent version, `0.6.50`, I am now getting expected coverage results with:
```
exclude: [
            'packages/*/stories/*', // there are only direct children of this dir
            'packages/icons-ui/**',
            'packages/icons-workflow/**',
            'test/**',
],
```
