### ISSUE TITLE
[test-runner-core / dev-server-core] plugin command API

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#266]
I want to add a plugin command API for communicating between the browser and the nodejs/server side. This enables many extensions of the test runner without having to add extra logic to the core.

We already have a plugin system for the dev server, I think it makes sense to extend that. The command system could be useful for people using the dev server as well.

Some very rough examples:

<details>
<summary>Setting viewport</summary>

```js
export default {
  plugins: [
    {
      name: 'viewport',

      executeCommand({ testSession, command, body }) {
        if (command !== 'set-viewport') {
          return;
        }

        const { viewport } = body;

        switch (testSession.browserLauncher.type) {
          case 'puppeteer':
            return testSession.browserLauncher.getPage(testSession.id).setViewport(viewport);
          case 'playwright':
            return testSession.browserLauncher.getPage(testSession.id).setViewportSize(viewport);
          case 'selenium':
            throw new Error('Selenium launcher does not support setting viewport');
        }
      },
    },
  ],
};
```

</details>

<details>

<summary>Reading/setting snapshots</summary>

```js
import fs from 'fs';

export default {
  plugins: [
    {
      name: 'snapshot',

      executeCommand({ testSession, command, body }) {
        if (command === 'get-snapshot') {
          return fs.readFileSync(body.path, 'utf-8');
        } else if (command === 'save-snapshot') {
          fs.writeFileSync(body.path, body.snapshot);
          return;
        }
      },
    },
  ],
};
```

</details>

<details>

<summary>Visual diffing</summary>

```js
import visualDiff from 'visual-diff';

function takeScreenshot(browserLauncher, elementSelector, path) {
  switch (testSession.browserLauncher.type) {
    case 'puppeteer':
      return testSession.browserLauncher
        .getPage(testSession.id)
        .querySelector(elementSelector)
        .takeScreenshot(viewport, path);
    case 'playwright':
      return testSession.browserLauncher
        .getPage(testSession.id)
        .querySelector(elementSelector)
        .takeScreenshot(viewport, path);
    case 'selenium':
      throw new Error('Selenium launcher does not support taking screenshots');
  }
}

export default {
  plugins: [
    {
      name: 'visual-diff',

      executeCommand({ testSession, command, body }) {
        if (command !== 'visual-diff') {
          return;
        }

        await takeScreenshot(testSession.browserLauncher, body.elementSector, body.path);
        const result = await visualDiff(body.path);

        return result.diff;
      },
    },
  ],
};
```

</details>

I'm not sure what to call the option yet, `browserCommand`, `command` or maybe something else. These serverside callbacks can be called from the browser using `fetch`:

```js
fetch('/__web-dev-server__/commands/set-viewport', { 
   method: 'POST', 
    body: JSON.stringify({ viewport: { height: 200, width: 300 } 
  }) 
})
```

This returns a promise which awaits the server's response. You can send back data from the server this way, and signal when a command finished executing.

We can hide the URL behind a common interface:

```js
import { executeServerCommand } from '@web/test-runner-commands';

await executeServerCommand('set-viewport',  { viewport: { height: 200, width: 300 } });
```

And most commands will probably be shipped through some library:

```js
import { setViewport } from '@web/test-runner-commands';

await setViewport({ height: 200, width: 300 });
```

I'm looking for feedback and thoughts on this topic!

**Comment by bennypowers** [comment]
We had tossed around the idea of a custom scheme, so instead of `/__web-dev-server__/commands/set-viewport` we might have `wtr:commands/set-viewport`

I'm not sure how feasible that is, but it would be a fine API if we could pull it off

**Comment by LarsDenBakker** [comment]
What would be the benefit of a custom URL scheme?

**Comment by bennypowers** [comment]
avoid possible collisions
but more importantly (imho), separate concerns - the server only serves your _content_ over http

**Comment by LarsDenBakker** [comment]
Do you think people are less likely to call their folder `wtr:commands` over `__web-dev-server__` ?

**Comment by bennypowers** [comment]
`wrt:` is a scheme
you can call your folder `about:chrome` if you want, but it won't help

**Comment by LarsDenBakker** [comment]
Ah I didn't get that part. Something to look into indeed.

**Comment by LarsDenBakker** [comment]
Implemented by https://github.com/modernweb-dev/web/pull/312
