### ISSUE TITLE
msw dependency throws error

### ISSUE THREAD

**Issue by zglimbeld** [modernweb-dev/web#2694]
When running unit tests using @web/mocks latest version 1.1.1, which has msw as a dependency at version 2.0.11, the package sometime throws an error of "Cannot read properties of undefined (reading 'url')". This has been fixed in version 2.2.6, as per [this](https://github.com/mswjs/msw/issues/2053#issuecomment-2002454274) comment.

I was wondering if any update to this dependency (as well as a script update, as per [this](https://github.com/mswjs/msw/issues/2053#issuecomment-2041169637) comment) that would fix this bug is planned.

**Comment by thepassle** [comment]
this should be fixed, make sure you run `npm update msw` to get the latest version of msw. Feel free to reopen if this is still an issue
