### ISSUE TITLE
[@web/dev-server-rollup] Higher version of whatwg-url

### ISSUE THREAD

**Issue by valadzhov** [modernweb-dev/web#2755]
Latest version of @web/dev-server-rollup uses "whatwg-url": "^11.0.0" which in turn uses tr46 3.0.0 in which there's a punycode issue which results in this error: 
![image](https://github.com/modernweb-dev/web/assets/9549439/10e78e1e-1d24-429b-9196-b438aa943f4d)
Can we get the used version of whatwg-url bumped (to at least v12.0.1) so that it uses a higher version of tr46?

**Comment by bashmish** [comment]
I think we can. Can you make a PR for that please?
