### ISSUE TITLE
[test-runner-chrome] remove find installations workaround 

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#281]
We no longer need our workaround here: https://github.com/modernweb-dev/web/blob/master/packages/test-runner-chrome/src/findExecutablePath.ts, since it's fixed upstream: https://github.com/GoogleChrome/chrome-launcher/pull/209

**Comment by deebloo** [comment]
is the whole fineExecutablePath.ts file the workaround?

**Comment by LarsDenBakker** [comment]
This if statement is the workaround: https://github.com/modernweb-dev/web/blob/master/packages/test-runner-chrome/src/findExecutablePath.ts#L21
