### ISSUE TITLE
[test-runner-*] support reporting skipped tests

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#288]
We support skipped tests, but we don't report any information about it. We should add support for skipped tests in the `TestSession` data structure, and pass on this information from Mocha.

**Comment by bennypowers** [comment]
Perhaps  either of these
```ts
interface TestResult {
  skipped: Boolean; //either
  result 'pass'|'fail'|'skipped'|'error''; // or
}

**Comment by LarsDenBakker** [comment]
This was added in https://github.com/modernweb-dev/web/pull/295
