### ISSUE TITLE
[test-runner] document running in a CI

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#326]
We should document different strategies for running the test runner in a CI.

**Comment by Westbrook** [comment]
In CircleCI, if you use the `circleci/node:*-buster-browsers` line of docker images it seems that you will have better luck running tests in Firefox. I've run it on `circleci/node:12.18.3-buster-browsers` specifically to success. I'll follow up with some other versions to ensure the 12.* series is understood as well as we can in that context.

**Comment by Niznikr** [comment]
Using Jenkins pipelines, the Playwright [docker image](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) (without the added user steps) has been working well for our project.

**Comment by LarsDenBakker** [comment]
@Niznikr which browsers are you running in your pipeline?

**Comment by Niznikr** [comment]
@LarsDenBakker Chromium, Firefox, and WebKit with concurrency set to 2.
