### ISSUE TITLE
Error: Cannot find module '@web/test-runner-commands/plugins'

### ISSUE THREAD

**Issue by davemooreuws** [modernweb-dev/web#362]
I have the following dependencies:

 "@web/dev-server-esbuild": "^0.2.1",
 "@web/test-runner": "^0.7.2",
 "@web/test-runner-commands": "^0.1.1",
 "@web/test-runner-playwright": "^0.5.1",

and I am getting this error when running wtr in the command line:
Error: Cannot find module '@web/test-runner-commands/plugins'

Looks like the **plugins** directory doesn't even exist in the published @web/test-runner-commands package.
Also the @web/test-runner-commands isn't a dependency of test-runner even though the code requires this module.

**Comment by LarsDenBakker** [comment]
@davemooreuws we added conditional exports which maps this import, but this is only supported by node v12 and up. We are supporting node v10 for now, ill create a fix for this.
