### ISSUE TITLE
[test-runner-core] config groups

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#369]
I moved the content to https://github.com/modernweb-dev/web/discussions/428

**Comment by Westbrook** [comment]
I really like everything here, except for `sequential: true,` in that we already have the `concurrency` property available, why would we add a second property that does almost the same thing with less advanced capabilities? Particularly, seeing that at one level is prime or getting it requested at another level and might be the beginning of API bloat.

**Comment by LarsDenBakker** [comment]
Good question! The thing is that to fix the firefox issue we need to control not only the concurrency of that test group, but also an indication that this should be the only test running and the window should have complete focus. Sequentially isn't the best name for that perhaps, but I'm not sure `concurrency: 1` fits that description either.

**Comment by Niznikr** [comment]
Yeah naming is tough. Thanks for digging into the firefox issue @LarsDenBakker!

**Comment by Westbrook** [comment]
I see, it's _actually_ two values, which makes sense about the added property. Would we want to enforce the use of two properties for the possibility that there are tests in the future that need to be run browser at a time, but not tab at a time? So keep the `concurrency` property for each group and then use something like `groupPriority: parallel | sequential`?

**Comment by LarsDenBakker** [comment]
I think we can also support a string value for groups:

```js
export default {
  files: 'test/**/*.test.js',
  groups: 'test/**/*.config.js'
}
```

This will resolve the glob pattern, and real all these files as groups. This way you can create per-folder or per-file configs. This would be similar to things like `.mocharc` and `.babelrc`, except that you'd need to define the test files still inside the config.

**Comment by LarsDenBakker** [comment]
Moved the content to the discussions board https://github.com/modernweb-dev/web/discussions/428
