### ISSUE TITLE
--coverage does not collect code coverage

### ISSUE THREAD

**Issue by motss** [modernweb-dev/web#431]
## Description

Run some of the `lit-element` examples provided in the repo and run tests with `--coverage` but no code coverage was collected after all the test passed.

Steps to reproduce:

1. Run `git clone https://github.com/modernweb-dev/example-projects.git`
1. Run `cd example-projects/lit-element`
1. Run `npm i` to install all dependencies
1. Run `npm t`

## Expected behavior

Code coverage result should display in the terminal and lcov.info should contain the outcome after each test.

## Actual behavior

Running tests with `--coverage` does not produce any code coverage result.

**Comment by LarsDenBakker** [comment]
Thanks for reporting, fixed in https://github.com/modernweb-dev/web/pull/433

**Comment by motss** [comment]
Thanks for the quick fix.
