### ISSUE TITLE
[dev-server] support range requests

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#465]
We should use the koa-range middleware to support videos.

**Comment by davidmaxwaterman** [comment]
I hit this same problem, and solved it with, after `npm install -save-dev koa-range`:
```
import range from 'koa-range';
...
  middlewares: [
    range
  ]
```

**Comment by davidmaxwaterman** [comment]
https://github.com/modernweb-dev/web/pull/1540

**Comment by web-padawan** [comment]
The solution is documented by #1540. Closing as fixed.
