### ISSUE TITLE
Missing "get-stream" dependency

### ISSUE THREAD

**Issue by marvinhagemeister** [modernweb-dev/web#474]
The recent version of `@web/dev-server-core` is missing the `get-stream` dependency.

```bash
$ wtr src/*.test.{js,jsx}
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module 'get-stream'
Require stack:
- /home/marvinh/dev/github/preact-custom-element/node_modules/@web/dev-server-core/dist/utils.js
- /home/marvinh/dev/github/preact-custom-element/node_modules/@web/dev-server-core/dist/middleware/historyApiFallbackMiddleware.js
- /home/marvinh/dev/github/preact-custom-element/node_modules/@web/dev-server-core/dist/server/createMiddleware.js
- /home/marvinh/dev/github/preact-custom-element/node_modules/@web/dev-server-core/dist/server/createServer.js
- /home/marvinh/dev/github/preact-custom-element/node_modules/@web/dev-server-core/dist/server/DevServer.js
```

**Comment by LarsDenBakker** [comment]
Looks like we were missing hte dependency since the start, I noticed it when working on https://github.com/modernweb-dev/web/pull/445 but it never caused a problem. Looks like it does now suddenly, I'll add the package in a separate PR.

Also... interesting project you're working on there 👀

**Comment by marvinhagemeister** [comment]
Yeah, the error only popped up once I was using the playwright adapter. Not sure why it didn't show up earlier.

Yup, there is renewed interest to transform Preact components to web components :tada:
