### ISSUE TITLE
[dev-server] allow to compose

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#510]
when you want to compose the dev server into another cli then different argv might be used.

For that reason, we would need to at least expose
- readCommandLineArgs / readCliArgsConfig
- createConfig / readConfig / validateConfig?

**Comment by LarsDenBakker** [comment]
Do you want the default terminal logging of the dev server? In watch mode it clears the terminal now on change.

**Comment by daKmoR** [comment]
I have no idea yet what the cli should display 😅
So the dev server can do whatever... might need to hook into this at some point... but there is certainly no rush
