### ISSUE TITLE
[test-runner-framework] object serialization

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#52]
When logging objects to the console we just do a `JSON.stringify` which loses a lot of information. We should look into a better way of serialization things like DOM elements, because right now they just turn into `{}`.

Preferably using an existing library. We may be able to take some inspiration from how storybook does this to send data between iframes.

**Comment by LarsDenBakker** [comment]
The location in the code is here: https://github.com/modernweb-dev/web/blob/master/packages/test-runner-framework/src/index.ts#L31

**Comment by daKmoR** [comment]
just experience this - some more details... 

I use this a lot to just see if I got the right element 😅  and it's faster then opening it in the browser - which I do if there is something tough to debug... but for small things or when creating new functionality the terminal output should be good enough...

iirc that worked with karma 🙈

## IN

```js
  it('finds current page', async () => {
    const el = await fixture('<h1>hey</h1>');
    console.log(el);
    expect(el.textContent).to.equal('hey');
  });
```

## current
```
 🚧 Browser logs:
    > {}
```

## expected
```
 🚧 Browser logs:
    > <h1>hey</h1>
```
