### ISSUE TITLE
Stack traces swallowed in error output

### ISSUE THREAD

**Issue by marvinhagemeister** [modernweb-dev/web#557]
When there is an error in the test, only the first line of a stack trace will be printed. In most of the cases the whole stack trace provides a lot of useful information to debug where an error was coming from.

Example of a cut off stack trace:

```bash
test/browser/hydrate.test.js:

 ❌ hydrate() > should not remove values
      at: node_modules/expectus/dist/esm/index.js:477:19
      error: Expected "<select><option value="0">Zero</option><option selected="" value="2">Two</option></select>" to strictly equal "<select><option value="0">Zero</option><option selected=""foo="" value="2">Two</option></select>"
      + expected - actual
```

Whereas the full stack traces is much more informative:

```bash
  at Assertion.assert (node_modules/expectus/dist/esm/index.js:477:19)
  at Assertion.equal (node_modules/expectus/dist/esm/index.js:172:18)
  at n.<anonymous> (test/browser/hydrate.test.js:312:32) // <-- This line shows where it happened in the test file
```

EDIT: Shameless plug, we had to write our own stack trace parser for the Preact devtools extensions, as the existing solutions where way to large or had troubles parsing firefox stack traces. It might be useful here for printing a formatted version: https://github.com/marvinhagemeister/errorstacks/

**Comment by LarsDenBakker** [comment]
We have special handling for chai errors with "actual" and "expected", where we print only the difference and take the first line of the stack trace. In chai that's always the line in the test file.

It seems that `expectus` throws chai-style errors, but there are some differences. I expect something to be printed below `+ expected and - actual`.

I will see how we can improve this. I'll create a separate issue to look into errorstacks, looks interesting.

**Comment by marvinhagemeister** [comment]
Regarding the cutoff: I didn't paste the full output as it's a bit longer. It's not actually cut off, so no worries!

Yeah, it's a chai-like assertion library I've been dabbling with on-and-off. But even with the real chai.js library I find myself missing access to the full stack trace as the first line is only where the error was thrown, not where everything started to go wrong.

**Comment by LarsDenBakker** [comment]
I added the full stack trace in https://github.com/modernweb-dev/web/pull/705

With chai the error in the test code is always the first line in the stack for me. Maybe they're pulling some trick to do that.
