### ISSUE TITLE
[dev-server] esbuild throws warning on source map urls

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#582]
When transforming with esbuild, it throws a warning on some source map urls:

[@web/test-runner-esbuild] Warning while transforming node_modules/lit-element/lit-element.js: Unsupported source map comment

**Comment by evanw** [comment]
Do you happen to know what the URL looked like? I'm wonder if it could make sense to add support for these URLs in esbuild.

**Comment by LarsDenBakker** [comment]
@evanw they look like this: https://unpkg.com/browse/lit-element@2.4.0/lit-element.js#L274 I think that's how TSC generates them
