### ISSUE TITLE
[dev-server] don't randomize port

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#590]
We randomize the port of the test runner because it's common to run many instances of the test runner in parallel. For the dev server it's not needed, it would be better if the port is reliable and only changed if the port is already taken.

**Comment by aomarks** [comment]
Also +1 for adding `--port` flag to control directly.

**Comment by abdonrd** [comment]
+1 about this!

It gets a bit annoying if you restart the server often or are working with multiple applications at the same time.
