### ISSUE TITLE
[test-runner] Add a CLI flag for manual debug + open

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#592]
The manual debug feature is really cool 👍   But every time I use it, there are two clicks needed: `M` and then click a link.

It would be really convenient to have a flag `--debug` which would choose manual debug option.
And maybe `--debug --open` to also open the default browser. WDYT ?

**Comment by LarsDenBakker** [comment]
I think this is a good suggestion. We can combine this with not making the browsers array required so that you could use WTR with manual testing only.

**Comment by LarsDenBakker** [comment]
I added these as `--manual` and `--open`.
