### ISSUE TITLE
[test-runner] Monorepo support - shared launchers, customized configs

### ISSUE THREAD

**Issue by justinfagnani** [modernweb-dev/web#596]
We're using WTR in the new lit monorepo, and have a pull request to hoist the WTR config to speed up tests by sharing browser launches: https://github.com/Polymer/lit-html/pull/1283

The downside is that each package has to have the exact same configuration - same launchers, same test framework and options (tdd vs bdd, timeout, etc.) This is fine for a new monorepo with such few sub-packages, but it might be really nice to be able to have shared launchers, but variants of the config for sub-packages.

**Comment by LarsDenBakker** [comment]
I think we can support this with https://github.com/modernweb-dev/web/issues/369

It won't be possible to support this for every config option, but we can cover a lot of them.

**Comment by LarsDenBakker** [comment]
I will close this one in favor of the tracking issue.

**Comment by LarsDenBakker** [comment]
Basic support for test groups are now in: https://modern-web.dev/docs/test-runner/cli-and-configuration/#examples

Each option will require some rework to add support, I have an open issue for support plugins here https://github.com/modernweb-dev/web/issues/645 let me know if you need other options as well.
