### ISSUE TITLE
[test-runner] Is it possible to use Page's methods in test files when running with Playwright

### ISSUE THREAD

**Issue by motss** [modernweb-dev/web#618]
## Description

There are a handful of [methods](https://playwright.dev/#version=v1.4.1&path=docs%2Fapi.md&q=class-page) provided by Playwright such as `page.click()`. Is that possible to use any of the methods in test file?

**Comment by LarsDenBakker** [comment]
Keep in mind that your tests themselves run in the browser. It's possible to communicate with the server side using commands, check the docs here: https://modern-web.dev/docs/test-runner/commands/#custom-commands

Please open new issues if you find any issues.

**Comment by daKmoR** [comment]
I think having more server command for example `click` and `keyboard interaction` out of the box would be awesome 👍

**Comment by motss** [comment]
This could the resources I've been looking for. Thanks for pointing me to the right place.
