### ISSUE TITLE
[dev-server] Changes in index file are not propagated

### ISSUE THREAD

**Issue by blikblum** [modernweb-dev/web#626]
When using web-dev-server with --watch flag and a change is done in the index file (html), the change is nor propagated to the browser. 

Even if i manually refresh the browser, the change does not show (inspecting Page Source shows the original content).

If i change something in a js file, the browser is refreshed accordingly to the js changes, but the changes in the index file still does not show.

The actual project is https://github.com/blikblum/wc-fontawesome (script start:watch)

**Comment by blikblum** [comment]
For the record, if i use the fully qualified URL, the content is reloaded, i.e.:

http://localhost:9368/example/ -> do not work
http://localhost:9368/example/index.html -> works

**Comment by LarsDenBakker** [comment]
Thanks for reporting, fix at https://github.com/modernweb-dev/web/pull/640
