### ISSUE TITLE
[dev-server-legacy] Ability to control whether polyfills are injected

### ISSUE THREAD

**Issue by aomarks** [modernweb-dev/web#659]
We're using `wtr` to test specific interactions with our own polyfills, which intersect with the polyfills automatically injected by `legacyPlugin`. Therefore we'd like to be able to switch off automated polyfill injection, while keeping the SystemJS and transpilation transformations.

**Comment by LarsDenBakker** [comment]
Definitely makes sense. 

For the polyfill injection we use https://www.npmjs.com/package/polyfills-loader which also allows specifying custom polyfills. Would this be useful to you, or do you prefer to inject the polyfills using one of the existing options?

**Comment by LarsDenBakker** [comment]
This was mostly a matter of forwarding the polyfills config. We do use fetch and promises inside the test runner runtime code itself. So you could disable just the polyfills you don't want, or if you disable all you need to make sure those are polyfilled. Docs at: https://modern-web.dev/docs/dev-server/plugins/legacy/#configuration

**Comment by aomarks** [comment]
So fast, thank you!
