### ISSUE TITLE
[dev-server] Changes on several files are not propagated

### ISSUE THREAD

**Issue by RoXuS** [modernweb-dev/web#661]
Hey!

We are in monorepo and several packages are not watched for obscur reason, someway to track this?
Some packages are completely covered by watch and some other not (all time the same packages).

```
/* eslint @typescript-eslint/no-var-requires: off */
import proxy from 'koa-proxies';
// eslint-disable-next-line
import server from './packages/excel-addin/httpsProxy/httpsProxy.js';

const proxyUrl = {
// Some proxies
};

let env = process.argv[3];
if (!Object.keys(proxyUrl).includes(env)) {
  env = 'dev';
}

const front = process.argv[2];

if (!front) {
  // eslint-disable-next-line
  console.error('missing frontend name');
  process.exit();
}

let port;

switch (front) {
  case 'admin':
    port = 5020;
    break;
  case 'customer-service':
    port = 5030;
    break;
  case 'content-production':
    port = 5040;
    break;
  case 'login':
    port = 5050;
    break;
  case 'excel-addin':
    port = 5088;
    break;
  default:
    port = 5010;
    break;
}

export default {
  port,
  watch: true,
  nodeResolve: true,
  preserveSymlinks: true,
  dedupe: true,
  appIndex: `packages/${front}/index.html`,
  rootDir: './',
  middleware: [
    function rewriteIndex(context, next) {
      // Rewrite url to fix static path
      if (/^\/(src|styles|manifest|images|locales)/.test(context.url)) {
        context.url = `packages/${front}${context.url}`;
      }
      // Rewrite url to route all flux to index.html
      if (/^\/(?!node_modules|packages|__|api|private-api)/.test(context.url)) {
        context.url = `/packages/${front}/index.html`;
      }
      return next();
    },
    proxy('/api', {
      target: proxyUrl[env].api,
      changeOrigin: true,
      rewrite: (path) => path.replace(/\/api/, ''),
    }),
    proxy('/private-api', {
      target: proxyUrl[env]['private-api'],
      changeOrigin: true,
      rewrite: (path) => path.replace(/\/private-api/, ''),
    }),
  ],
};

if (server && front === 'excel-addin') {
  server.listen(5080, () => {
    console.log('--- Listen on port 5080 over HTTPS ---');
  });
}
```

**Comment by LarsDenBakker** [comment]
Are you seeing that files don't trigger a reload, or that when reloading you don't see the updates file contents? Even when reloading manually?

**Comment by RoXuS** [comment]
The two! We don't see updates file contents and the browser is not reloaded.

**Comment by LarsDenBakker** [comment]
Do you have any info on which files you are seeing this for? Are those the files you are rewriting the URLs for?

**Comment by RoXuS** [comment]
Hard to say, I think all files load by my main file (my app shell) is ok but all other (loaded dynamically) are KO.

**Comment by RoXuS** [comment]
Yeah I confirm, if I dynamically import a page, the watcher is KO on it, if I import it directly in my main file it is ok without reloading.

**Comment by LarsDenBakker** [comment]
Would you be able to try to find a pattern? The logic for us is that we look for a file corresponding to the root dir + request/response path. If it exists on disk, we cache files and watch it for reloads.

**Comment by RoXuS** [comment]
Ok I try to create a mini project with the bug.

**Comment by RoXuS** [comment]
I get it on this project https://github.com/RoXuS/test-web-dev-server.
Updates main-tools or main-app involved refresh but update on main-page do nothing and I have to kill and restart web-dev-serve.

**Comment by RoXuS** [comment]
Ok sorry for my last try, now I "really" get it haha.

https://github.com/RoXuS/test-web-dev-server

On mono repo with this config: https://github.com/RoXuS/test-web-dev-server/blob/master/web-dev-server.config.js

The changes on main-page isn't appear even if I reload the page manually.

**Comment by RoXuS** [comment]
It seems that if the component is not loaded by the app, it doesn't trigger reload.

If I click on "Click Me!" div the component is loaded then all change on it are correctly triggered but if I kill and relaunch `wds` the changes doesn't trigger reload again.

**Comment by RoXuS** [comment]
I add a log, potentially link to the issue:
![image](https://user-images.githubusercontent.com/3296671/94855196-6b4ac100-042e-11eb-9267-a8224da8437a.png)

**Comment by LarsDenBakker** [comment]
@RoXuS Thanks for making the reproduction. The dev server only watches files actually served by the dev server. It wouldn't make sense to reload on changes to other files, since the browser won't request those.

I cloned your repository and made changes to some different files, and the behavior is as expected.

**Comment by RoXuS** [comment]
@LarsDenBakker, you are right, I don't be able to reproduce the bug inside the projet.. Maybe it due to number of files present inside the project?

For example on a component I have the following imports:

![image](https://user-images.githubusercontent.com/3296671/94896800-a4b31900-048e-11eb-9ab5-8423d1aa4abb.png)

Change on this two files involve reload:
```
import { getStats } from '@doubletrade/dt-api/statistics/statistics';
import StatisticsReducerFactory from '@doubletrade/redux-data/statistics/statistics-reducer-factory';
```
But not on:
```
import '@doubletrade/dt-statistics/dt-statistics-date';
```
Sometimes it's other files...

I know it is hard to you to fix a bug without reproduce the case...
Happens on my OSX and with my colleague on linux.

**Comment by LarsDenBakker** [comment]
Did you also run this project using es-dev-server? did it work correctly there?

**Comment by RoXuS** [comment]
I wanted test but this project is a module and es-dev-serve don't like this.

I try to change that.

**Comment by RoXuS** [comment]
Same on es-dev-server and before we didn't have so it's probably link to monorepo and the max open files or other... I check that...

**Comment by LarsDenBakker** [comment]
How many files are loaded when you look in the network panel?

**Comment by RoXuS** [comment]
About 400, not that much...

**Comment by RoXuS** [comment]
Other info: our colleagues on WSL2 doesn't have this issue...

**Comment by RoXuS** [comment]
@LarsDenBakker can we add some logs inside dev-server to try to fix that?

**Comment by RoXuS** [comment]
https://github.com/paulmillr/chokidar/issues/1040

For info.

**Comment by LarsDenBakker** [comment]
@RoXuS if I understand it correctly, the issue is with symlinked files? Also which OS does it fail on for you? Since you mentioned it works on WSL2.

**Comment by RoXuS** [comment]
Correct, it happens only on macos on symlink and when 10 folders or more with the same path are listened.

To avoid issue on `fsevent` (128 max listeners), Chokidar regroup all path when the same parent folder is used.
Example:
````
/Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade/xx/file1.js
...
/Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade/xx/file10.js
Then for all others listener will be:
/Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade
````
In my case, `/Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade` contains only symlinks (my workspace) and `fsevents` does not seems to be able to watch a change on a file inside a subfolder in a symlink. It work correctly on the full path with symlink, that's why the behavior was completely random.

My PR consist to use the "realPath" instead of the symlink path to watch changes (https://github.com/paulmillr/chokidar/pull/1041/files). With that all it's ok.


On WSL2 it works, but one of my mate have the same issue on Ubuntu, I didn't have time to study the problem but It is not the same issue because Chokidar doesn't use `fsevents` on Ubuntu.

**Comment by RoXuS** [comment]
My PR has been released -> https://github.com/paulmillr/chokidar/issues/1040

Now all is ok ^^.
