### ISSUE TITLE
[test-runner] Cannot read property 'decl' of undefined in coverage UI

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#689]
Two files in the [PR for `vaadin-date-picker`](https://github.com/vaadin/vaadin-date-picker/pull/733) have this problem:

```
Cannot read property 'decl' of undefined
TypeError: Cannot read property 'decl' of undefined
    at /Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/annotator.js:89:31
    at Array.forEach ()
    at annotateFunctions (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/annotator.js:86:29)
    at annotateSourceCode (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/annotator.js:234:9)
    at HtmlReport.onDetail (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/index.js:409:33)
    at LcovReport. [as onDetail] (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/lcov/index.js:28:23)
    at Visitor.value (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportNode.visit (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-lib-report/lib/tree.js:88:21)
    at /Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-lib-report/lib/tree.js:92:19
    at Array.forEach ()
```

As you can see the numbers are there:

![Screenshot 2020-10-05 at 13 30 19](https://user-images.githubusercontent.com/10589913/95069169-fb2e8a80-070e-11eb-898d-68beb86a8c18.png)

But when opening the files, I get this:

![Screenshot 2020-10-05 at 13 30 26](https://user-images.githubusercontent.com/10589913/95069172-fc5fb780-070e-11eb-88f7-40d004b4aa56.png)

![Screenshot 2020-10-05 at 13 30 33](https://user-images.githubusercontent.com/10589913/95069180-fd90e480-070e-11eb-976d-81bdce50574e.png)

**Comment by LarsDenBakker** [comment]
Seems related to https://github.com/istanbuljs/v8-to-istanbul/issues/121

**Comment by mario-aleo** [comment]
This is an awkward error, when I run the test  for all the components in the project, I get this error on some of them, but when I run the test for only one of those components that have the error it generates the coverage report properly.

Running for each component in the project:
![Print 1](https://user-images.githubusercontent.com/13382278/98733830-e2ee0300-237f-11eb-9190-b20fa4c33bb1.png)
![Print 2](https://user-images.githubusercontent.com/13382278/98733840-e6818a00-237f-11eb-94de-93428f9b2198.png)
![Print 3](https://user-images.githubusercontent.com/13382278/98733842-e8e3e400-237f-11eb-8c81-134bfc737f85.png)

Running only for golfleet-filter-calendar:
![Print 4](https://user-images.githubusercontent.com/13382278/98734029-2e081600-2380-11eb-9ae8-1e6530add34b.png)
![Print 5](https://user-images.githubusercontent.com/13382278/98734045-319b9d00-2380-11eb-93d9-32b11f0d2e0b.png)

Probably not related but the` /* istanbul ignore next */` on this component has been ignored and the code was included in the coverage.

**Comment by LarsDenBakker** [comment]
It seems to happen when using typescript (or perhaps generally source maps). You can opt into doing coverage instrumentation with babel: https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#coverage-browser-support though this is slower.

**Comment by mario-aleo** [comment]
Thank you @LarsDenBakker, it did work, but it's kinda strange since I'm not using typescript in this project and it was running just fine with open-wc's testing-karma (I'm just upgrading my project dependencies to the new  open-wc recommendations).

Also if anyone is going to try [the babel aproach ](https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#coverage-browser-support) you'll need to write it a little bit different as stated here #840.

**Comment by LarsDenBakker** [comment]
The karma config used babel for instrumenting code as well. We switched to using chromium for speed.

**Comment by LarsDenBakker** [comment]
@mario-aleo @web-padawan looks like we were not on the latest version of the library. Can you try updating to the versions listd here: https://github.com/modernweb-dev/web/pull/935 and see if the problem is still there? And if so report a reproduction to https://github.com/istanbuljs/v8-to-istanbul/issues/121 ?

**Comment by mario-aleo** [comment]
@LarsDenBakker, sorry for the late response.
I've just tried and didn't work, as I've reported at [istanbuljs/v8-to-istanbul#121](https://github.com/istanbuljs/v8-to-istanbul/issues/121), I'll create a repository with this error so you can easily reproduce it :)

**Comment by dwilson6** [comment]
We just ran into this on a project set up with snowpack, typescript, svelte and web test runner. We have svelte component A that imports svelte component B which in turn imports typescript module C. We had 100% code coverage and then component B and module C were moved to a subdirectory inside the dir where component A is. After that module C's code coverage is 71% for functions despite no changes in the file or the test suite. 

When we look at the test report, we see the `Cannot read property 'decl' of undefined` error.  After some investigation I noticed that if I ran the test suite for component A before module C, the error happens but if I run module C's tests first and then the ones for component A, there is no error.

I tried to create a simpler setup to reproduce the error but was unable to reproduce it. It is also worth mentioning that there are some issues with snowpack and svelte sourcemaps which cause the html report to not work for svelte components but this is a typescript file seeing the issue so I am not sure if the svelte issue is to blame.

**Comment by stephenwade** [comment]
@web-padawan @mario-aleo @LarsDenBakker I ran into this issue today with @web/test-runner. I was able to narrow it down to one class file and two test files.

If any of these characteristics are changed, the coverage report works properly:

- The class function assigns an anonymous function to an instance property.
```js
export class MyClass {
  fn() {
    this._ = function () {};
  }
}
```
- There are two test files, both of which import the same class file.
- Only one of the test files calls the class function.

https://github.com/stephenwade/coverage-issue-repro

To reproduce, run `npm test` and open `coverage/lcov-report/my-class.js.html`.

<img width="1000" alt="Screen shot of coverage error" src="https://user-images.githubusercontent.com/4148577/112772312-0b5c5e00-8ffe-11eb-95d2-7f8828c4ec9b.png">

**Comment by Stuk** [comment]
I have a minimal repro repository here: https://github.com/Stuk/wtr-coverage-repro. The details of what I believe causes this issue are listed in the readme.

To summarize, metadata for functions in a file is only collected the first time that file is loaded, however some methods might only be defined when more code executed. Hence the above error when trying to access metadata for a covered function that doesn't always exist.
