### ISSUE TITLE
[Test Runner] Firefox Error Report shows wrong file at location

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#714]
When there is an error it shows the wrong file **at** location on Firefox/Safari (via playwright)

## Actual Behavior

```
packages/calendar/test/lion-calendar.test.js:

 ❌ <lion-calendar> > Public API > has property "centralDate" that determines currently visible month
      at: node_modules/chai/chai.js:9449:13
```

## Expected Behavior

e.g. same as on chrome

```
packages/calendar/test/lion-calendar.test.js:

 ❌ <lion-calendar> > Public API > has property "centralDate" that determines currently visible month
      at: packages/calendar/test/lion-calendar.test.js:106:36
```

**Comment by LarsDenBakker** [comment]
This is correct, since that's where firefox reports that the error occured. In chrome chai isn't included in the stack trace, but on firefox it is. Not sure why...

**Comment by daKmoR** [comment]
Safari has the same behavior as Firefox 😅

**Comment by LarsDenBakker** [comment]
We could walk the stack trace and try to find the test file and use that. This is potentially easier with https://github.com/modernweb-dev/web/issues/562

**Comment by LarsDenBakker** [comment]
Fixed in https://github.com/modernweb-dev/web/pull/1182
