### ISSUE TITLE
Mocha dashboard output breaks tests

### ISSUE THREAD

**Issue by FredKSchott** [modernweb-dev/web#720]
We're so close to getting @web/test-runner working in Snowpack! Unfortunately, I was doing some extra testing and came across this issue using React & @testing-library:

```
// Passes!
it('run #1', async () => {
  const {getByText} = render(<App />);
  const linkElement = getByText(/Learn React/);
  expect(document.body.contains(linkElement));
});

// Fails: getByText() matches both the "Learn React" string in dom 
// PLUS the `<code>` display on the page from the previous test run, 
// showing the exact lines of the test above, which includes the string "Learn React".
it('run #2', () => {
  const { getByText } = render(<App />);
  const linkElement = getByText(/Learn React/);
  expect(document.body.contains(linkElement));
});
```

I was surprised that this extra output from Mocha would exist on the page, and assumed that each test would be run in a clean environment / iframe. @testing-library packages automatically run cleanup of anything that they create, so we're fine there, but is there a way to disable any mocha output from the page that is actually running the tests?

**Comment by FredKSchott** [comment]
Not sure if this is the reporter that you use, but it's coming from something just like this on the page: https://github.com/blond/mocha-simple-html-reporter/blob/master/lib/index.js

Seen here: 
<img width="1410" alt="Screen Shot 2020-10-09 at 9 53 35 PM" src="https://user-images.githubusercontent.com/622227/95646099-e4bf6080-0a79-11eb-8772-6fdc6f8c9251.png">

**Comment by LarsDenBakker** [comment]
Interesting... each test does in in a separate browser tab with just that test file does contain the HTML reporting as well. I will check if there is a way to isolate, and possible restrict it to debug only.

**Comment by FredKSchott** [comment]
Not sure I totally follow your comment, but the behavior that I was seeing implied that each test was running on the main page, and not separate browser tabs. When only 1 test existed on the page, it passed. When 2 tests existed, the first one passed but the second failed (due to mocha output from the first test).

I've worked around this for now by injecting a basic `beforeEach` to each test file that removes all `.test` elements that Mocha creates from the page. It's brittle, but for now it's better than the risk of mocha HTML polluting the test environment.

**Comment by LarsDenBakker** [comment]
Sorry I mean each test *file* runs in a separate environment, where it loads mocha and the default reporter is the HTML reporter. The HTML reporter pollutes the DOM of that page. 

We will turn off any reporter when testing headless, since there is no need to do any reporting in the browser. I actually saw a nice performance improvement from that. When debugging headful, we will switch to a reporter which logs to the browser console instead. Users can still switch back to the old behavior by configuring a different reporter.

**Comment by FredKSchott** [comment]
Awesome! That solves our use-case. Thanks for the quick fix!
