### ISSUE TITLE
[test-runner] Test framework could not be loaded

### ISSUE THREAD

**Issue by basham** [modernweb-dev/web#754]
I'm using the latest version of Snowpack and the `@snowpack/web-test-runner-plugin` to get web-test-runner working. I've been trying to get it to run all day, but I keep running into this error:

```
Error: The test framework at /Volumes/Basham%20HD/GitHub/rx-ui-patterns/node_modules/@web/test-runner-mocha/dist/autorun.js could not be loaded. Are your dependencies installed correctly? Is there a server plugin or middleware that interferes?
```

The `autorun.js` file tries to be imported like this:

```html
<script type="module" src="/__web-test-runner__/test-framework/Volumes/Basham HD/GitHub/rx-ui-patterns/node_modules/@web/test-runner-mocha/dist/autorun.js"></script>
```

Then the [`serveTestFrameworkPlugin`](https://github.com/modernweb-dev/web/blob/master/packages/test-runner-core/src/server/plugins/serveTestFrameworkPlugin.ts) grabs that path and resolves it.

I suspect the issue is the space in the path. It gets rendered correctly in HTML, but somewhere it encodes the space into `%20` by the time it tries to use the path in the `readFile()` function. This causes `fs.existsSync()` to return false.

Maybe there needs to be some decoding process for the path in the plugin? Maybe something else is amiss?

**Comment by basham** [comment]
I think all that is needed is to add a [`decodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) transformation for the path before passing it to the `readFile()` function.

**Comment by LarsDenBakker** [comment]
Indeed you're right! Fixed in https://github.com/modernweb-dev/web/pull/755

**Comment by basham** [comment]
The change worked. Thanks for the quick fix! Great start to the day.
