### ISSUE TITLE
[rollup-plugin-html] Absolute URL should stay absolute

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#781]
Consider the following input

```html
<link rel="stylesheet" href="/styles.css">
<link rel="stylesheet" href="./page-styles.css">
```

## Current behavior

```html
<link rel="stylesheet" href="685bb460.css">
<link rel="stylesheet" href="38153186.css">
```

this will now load stylesheets on `index.html` but will fail to load those files on `subfolder/index.html`

## Expected behavior

Either always use absolute Urls (works for `index.html` & `subfolder/index.html`)

```html
<link rel="stylesheet" href="/685bb460.css">
<link rel="stylesheet" href="/38153186.css">
```

or construct a valid path to the assets/root folders
- `index.html`
  ```html
  <link rel="stylesheet" href="685bb460.css">
  <link rel="stylesheet" href="38153186.css">
  ```

- `subfolder/index.html`
  ```html
  <link rel="stylesheet" href="../685bb460.css">
  <link rel="stylesheet" href="../38153186.css">
  ```

**Comment by LarsDenBakker** [comment]
You can set a `publicPath` to specify where the assets should be loaded from. It seems like you'd want this configured for all assets or none of them, why should we check the source paths?

**Comment by daKmoR** [comment]
I updated the issue description with more info - it's about how to get to the hashed assets... relative URLs won't "work" unless they are specially generated.

I tried with `publicPath: '/'` but does not seem to change the URLs in subfolders

**Comment by LarsDenBakker** [comment]
Ah I see. That indeed looks like a bug it should resolve the paths relative to the HTML file.
