### ISSUE TITLE
[rollup-plugin-html] full Urls should be ignored (for now)

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#782]
Consider the following input

```html
<link
  href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap"
  rel="stylesheet"
/>
```

## Results in the following error
```
(node:2219) UnhandledPromiseRejectionWarning: Error: Could not find /path/to/web/rocket/docs/https:/fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap referenced from HTML file docs/index.html from element .
```

## Expected behavior

Leave external full URLs as is and don't touch them.

**Possible later feature**: Enable an option/regex/domainlist/... for resources to download and include into the local build

**Comment by Westbrook** [comment]
So in both of these we should be extracting the URL and testing for locallity?

https://github.com/modernweb-dev/web/blob/3776aff3ee975507007052b540566ecb8b307127/packages/rollup-plugin-html/src/assets/utils.ts#L9-L18

Is this something one of our tools would have a helper for, or is it more like `const local = url.search('://') === -1`?

**Comment by LarsDenBakker** [comment]
No helper as far as I know. I usually do a `new URL(path)` in a try catch, and then check the protocol.

**Comment by LarsDenBakker** [comment]
Fixed in https://github.com/modernweb-dev/web/pull/798
