### ISSUE TITLE
External does not seem to work with @web/rollup-plugin-html

### ISSUE THREAD

**Issue by peschee** [modernweb-dev/web#811]
I'd like to be able to reference assets (scripts) with absolute paths that should be ignored in the rollup + html build. 

As an example, I have the following HTML code:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <script type="module" src="/path/module.js"></script>
  </head>
  <body>
  </body>
</html>
```

The ES module (a webcomponent) `/path/module.js` should not be touched / bundled by rollup. Defining `external: ['/path/module.js']` in my `rollup.config.js` gives this error:

```
index.html → dist...
[!] Error: Could not resolve entry module (path/module.js).
Error: Could not resolve entry module (path/module.js).
```

A simple test case can be found at https://github.com/peschee/rollup-external-html-test

**Comment by LarsDenBakker** [comment]
As it turns out you can't mark an entrypoint module as external in rollup. We will need to add some options to the plugin config to handle these cases.
