### ISSUE TITLE
[dev-server-esbuild] Upgrade esbuild to version 0.8.5

### ISSUE THREAD

**Issue by kamil0414** [modernweb-dev/web#839]
esbuild was released a while ago. I would be nice to include the latest features and update the package used in the @web\dev-server-esbuild module.

**Comment by verydanny** [comment]
I agree with this. I use ebuild internally to bundle the non-CJS things, like `@testing-library/preact` then importing it. ESBuild 0.8.6 fixes some CJS/ES import issues so I can do:

```ts
import { render } from 'bundled-testing-lib'
```

Instead of

```ts
import TestingLibrary from  'bundled-testing-lib'

const { render } = TestingLibrary
```

Basically, it supports better tree-shaking.

**Comment by LarsDenBakker** [comment]
I don't think updating the dev server plugin is going to help you here, it only uses the single file transform API.

**Comment by verydanny** [comment]
Correct, but it uses an outdated ESBuild, preventing me from updating ESBuild that I use in the same project.

**Comment by LarsDenBakker** [comment]
We're now on the latest esbuild.
