### ISSUE TITLE
[test-runner] "Debug in the browser" command does not work on Windows

### ISSUE THREAD

**Issue by blikblum** [modernweb-dev/web#844]
Running web-test-runner in watch mode, shows "Press D to debug in the browser." among other options

Pressing "D" does nothing

If i press "M" than "D", it opens the system default browser, in my case Firefox

Some notes:
 - The tests are run just fine
 - The system is windows 10, fully patched, with Node 14, Firefox, Chrome freshly installed (system was restored one week ago)
 - Firefox is the default browser, not Chrome
 - The [project](https://github.com/blikblum/wc-fontawesome) i'm testing has only one test file (no focus option)

PS: Is there an "verbose" option to help track what is going on?

**Comment by LarsDenBakker** [comment]
Are you using WSL? It's likely that the browser is opened but only visible in the headless WSL instance.

**Comment by blikblum** [comment]
> Are you using WSL?

No. Native windows only. WSL is not installed at all.

**Comment by LarsDenBakker** [comment]
Looks like some path inconsistency on windows crept into the code. Thanks for reporting!

**Comment by blikblum** [comment]
Thanks for looking into this but still not working.

I managed to debug it:

- In [startDebugBrowser](https://github.com/modernweb-dev/web/blob/cd8928b83ad8db18a4a3ce6634aa76f6e343b80b/packages/test-runner-core/src/runner/TestRunner.ts#L175), testFile is not normalized ("D:\\repositories\\nefrolog\\mobile\\src\\common\\stores\\HospitalPatientsStore.test.js")
- In [forTestFile](https://github.com/modernweb-dev/web/blob/88cc7ac87a0a369c5d79e4ef15a55f8ed386854e/packages/test-runner-core/src/test-session/TestSessionManager.ts#L80), the passed testFiles is compared with each instance of TestSession.testFile which are normalized, e.g, "D:/repositories/nefrolog/mobile/src/common/stores/HospitalPatientsStore.test.js"

**Comment by blikblum** [comment]
BTW: should not display an error when session not found?

**Comment by LarsDenBakker** [comment]
A better error message would help debug this case indeed, although you could argue that a test file must have an associated test session. Is it possible you're still using an older version of test runner core? Perhaps try reinstalling without a lockfile?

**Comment by blikblum** [comment]
>  Is it possible you're still using an older version of test runner core? 

The main package seems correct:     "@web/test-runner": "^0.9.8",

But the @web/test-runner-core was not updated

> Perhaps try reinstalling without a lockfile? 

This did the trick. With the new version works

> A better error message would help debug this case indeed, although you could argue that a test file must have an associated test session

It should be an assert / invariant
