### ISSUE TITLE
[test-runner-cli] Path error since 0.5.2

### ISSUE THREAD

**Issue by RoXuS** [modernweb-dev/web#87]
Since the 0.5.2 I have this error:
![image](https://user-images.githubusercontent.com/3296671/84579287-da8f9d00-adcc-11ea-96d7-d1607c0849a9.png)

(without specific conf, it's ok on 0.5.1)

And thx for this tool.

**Comment by LarsDenBakker** [comment]
Thanks for reporting! I moved around the rootDir property, and forget to set a default  value :)
