### ISSUE TITLE
Everything depending on @web/parse5-utils is broken for Node < 12.17

### ISSUE THREAD

**Issue by ChristianUlbrich** [modernweb-dev/web#870]
[@web/parse5-utils](https://unpkg.com/browse/@web/parse5-utils/) is broken, because its `package.json` `main` points to  non-existing `dist/index.js`. Thus basically everything using CommonJS depending on this is more or less broken.

This seems to be at least:
* @web-dev-server-core
* @polyfills-loader
* rollup-plugin-html

I see, that the fix is already in place, so publishing a new version of `@web/parse5-utils` and _also_ new versions of the stuff depending on it using the new version should fix everything.

**Comment by LarsDenBakker** [comment]
We already published this fix for `@web/parse5-utils`: https://unpkg.com/browse/@web/parse5-utils@1.1.2/package.json 

I just tried a clean install of these packages, and I get the latest of parse5-utils.

**Comment by ChristianUlbrich** [comment]
You are right. I think I was a little bit too aggressive in my wording. _But_ the referenced issue has still the problem, because you commited a `package-lock.json` and thus won't get the new version...
