### ISSUE TITLE
[dev-server] does not work with TypeScript with pnpm workspaces; or likely has problems with symlinked packages

### ISSUE THREAD

**Issue by ChristianUlbrich** [modernweb-dev/web#871]
Hi,

sadly `web-dev-server` does not seem to work with symlinked node packages and TypeScript. :(

# Repro-Cases
## Environment:
* macOS, Node: 14.14, pnpm version: 5.10.2

## Steps
1. `git clone git@github.com:ChristianUlbrich/web-dev-server-examples-repro.git wds-repro`
2. `cd wds-repro``
3. `pnpm i -r`
1. `cd cd packages/lit-element-ts-tsc`
1. `pnpm run start`
1. **BOOM**:
> Error while transforming tsc-out/src/MyElement.js: 
> 
> Resolved tslib to web-dev-server-examples/node_modules/.pnpm/tslib@2.0.3/node_modules/tslib/tslib.es6.js.
> 
> This path is not reachable from the browser because it is outside root directory z_Testing/web-dev-server-examples/packages/lit-element-ts-tsc

Setting `preserverSymlinks` in `tsconfig.json` does not help. It seems to be a TypeScript-related problem, but digging through the code, I did not find anything resourceful at the first glance.

I know, that [pnpm](https://github.com/pnpm/pnpm)s approach of symlinking from a global store into individual projects has issues with other projects as well, but `web-dev-server` would really make my life a lot easier :) Maybe you have an idea, where there are potential problems concerning symlinks in the code...

I did not test [lerna](https://github.com/lerna/lerna) but its linking strategy is basically the same as pnpm's and thus likely to fail as well.

**Comment by LarsDenBakker** [comment]
You can configure whether symlinks are followed from the config or CLI: https://modern-web.dev/docs/test-runner/cli-and-configuration/

What can also help here is setting the root directory to the root of your monopo (for example `../../` in a typical monorepo).

**Comment by javier-garcia-meteologica** [comment]
I confirm that setting `preserveSymlinks: true` in `web-test-runner.config.mjs` solved this issue for me
