### ISSUE TITLE
[dev-server-hmr] - Seems to register wrong modules

### ISSUE THREAD

**Issue by JoviDeCroock** [modernweb-dev/web#883]
Hey 👋 

I was developing the plugin to integrate [`Prefresh`](https://github.com/JoviDeCroock/prefresh/pull/215) with the dev-server now that the hmr spec is there. I was running into some issues when developing on my Windows machine, I noticed that reloads just wouldn't happen, this made me dive into the internals and found the following to happen:

Dependency tree entry:

```
  '/src/app.jsx' => {
    hmrAccepted: true,
    hmrEnabled: true,
    dependencies: Set(0) {},
    dependents: Set(0) {}
  },
```

Update request route:

```
/../C:\Users\jovid\Desktop\prefresh\test\fixture\web-dev-server\src\app.jsx
```

This meant that the hmr-module wouldn't find an update for what i requested and it seemed stuck (nothing was happnening on my screen).

At first I thought this was just a Windows problem but when running the tests inside of the CI, a similar issue seems to be happening.

In case you want to use the fixture from that branch to test with do note that the dependencies are pointing wrong, this is because the puppeteer tests move these to the root of the project. To use it do:

- run `yarn && yarn build` at the root
- Change deps [here](https://github.com/JoviDeCroock/prefresh/pull/215/files#diff-7ab1a45fec1e13b0ef0536cc6707e6b667ed27cb8d56cc090af349325e07971bR12) and add a `../`
- run `yarn && yarn dev` in the fixture dir

Feel free to give pointers where I should look in case you want me to debug somewhere.

**Comment by 43081j** [comment]
I tried it locally on windows with WSL and the `accept()` callback does get called, but the flush of updates has no updates, so nothing happens.

presumably you're not using WSL (given the path you saw) so ill try it outside that too if i can.

**Comment by JoviDeCroock** [comment]
Given that it also errors out on CI I wouldn't exclusively tie it to native windows, hmm maybe the error is located somewhere differently. I'll debug further.

**Comment by 43081j** [comment]
do you have a link to an example failed CI build?

also, its a bit of a pain right now as there's no way to turn debug logging on. but you can manually alter the server to force it that way... if you edit `node_modules/@web/dev-server/dist/startDevServer.js` and change `debugLogging: false` to `true`, you'll see more useful output.

i can see `app.jsx` does get registered, has `hmrEnabled=true` and ultimately calls the `accept()` callback when it changes. 

in your case, does it never call the callback?

**Comment by JoviDeCroock** [comment]
For instance: https://github.com/JoviDeCroock/prefresh/pull/215/checks?check_run_id=1402853441#step:6:4346

**Comment by LarsDenBakker** [comment]
@43081j I added a `--debug` flag now in the latest WDS. Hopefully that helps with debugging

**Comment by JoviDeCroock** [comment]
On Linux this issue was related to `context.url` & `context.originalUrl` containing the`?mtime=x` which when stripping out makes HMR work correctly.

**Comment by LarsDenBakker** [comment]
It looks indeed like the bubbling is not working the same way it does in vite and snowpack. Any idea why @43081j ?

**Comment by JoviDeCroock** [comment]
My last pr solves it normally, we reset deps too eagerly

**Comment by 43081j** [comment]
I'll have a read through in the morning 👍

From a glance i see what your solution is. But will review it properly tomorrow

**Comment by JoviDeCroock** [comment]
@43081j I might still have goofed up somewhere, on UNIX it still does a full reload for bubbled updates. Will try and get to that this weekend.
