### ISSUE TITLE
[rollup-plugin-html] Package.json issue with 'main' field

### ISSUE THREAD

**Issue by gqio** [modernweb-dev/web#892]
Hi,

Apparently there is an issue with the package.json

inside the package.json we can see 
![image](https://user-images.githubusercontent.com/1063530/99240169-62eeef80-27fc-11eb-912b-924c9d02dd54.png)

But inside the bundle there is no such file
![image](https://user-images.githubusercontent.com/1063530/99240227-7bf7a080-27fc-11eb-8a33-363c23bc8f7b.png)

I think it should be either 'src/index.mjs' (because of the reexport of dist/index.js) or 'dist/index.js'

Best,

**Comment by LarsDenBakker** [comment]
Indeed this should be `dist/index.js`. However it's only an issue on node v10, node v12 and higher will use the exports map that's defined.

**Comment by gqio** [comment]
Hi @LarsDenBakker 
Yes fully agree with you,

I'm pointing this mostly because it does not work with unpkg : https://unpkg.com/@web/rollup-plugin-html
Additionaly it can be tricky with webpack, I managed to white list this as external (because webpack4 does not support esm) the exact path as a workaround.

Food for thought ;)

**Comment by LarsDenBakker** [comment]
You're bundling the HTML plugin with webpack?

**Comment by gqio** [comment]
You can yes, in case you want to use it as a container for serverless for instance.

**Comment by LarsDenBakker** [comment]
Fixed in https://github.com/modernweb-dev/web/commit/05dd36f6fbf1f1b566d57eba067d83659362ce66
