### ISSUE TITLE
[test-runner-cli] Strange behavior with fetchMock ?

### ISSUE THREAD

**Issue by RoXuS** [modernweb-dev/web#90]
Hey,

I have a timeout on one of my test files (1/5) (whereas on karma they are all goods):

![image](https://user-images.githubusercontent.com/3296671/84595184-ddcf6b00-ae56-11ea-9fe8-c34b79d1132a.png)

The first issue that in the debug mode, my map files are ignored:
![image](https://user-images.githubusercontent.com/3296671/84595277-428ac580-ae57-11ea-8462-e4c9e2321640.png)
(on karma I have the line of the typescript file and not the javascript file).

The second issue, I have strange log about fetchMock:
![image](https://user-images.githubusercontent.com/3296671/84595314-87166100-ae57-11ea-8efe-dc3766b44616.png)
Then the test timeout.

Do you do a POST call during test ?

**Comment by LarsDenBakker** [comment]
Yes we use fetch to communicate with the test runner. 

I think we can cover this by storing a reference to the native fetch before it's mocked, so that it bypasses the mocking system.

**Comment by LarsDenBakker** [comment]
Regarding the source mapping, is the mapping incorrect only in the HTML reporter in debug mode or also in the terminal?

**Comment by RoXuS** [comment]
Same behavior in the terminal:
![image](https://user-images.githubusercontent.com/3296671/84628724-79112080-aee9-11ea-9870-1b33b07ebc96.png)

**Comment by LarsDenBakker** [comment]
Can you update to 0.5.6 and see if fetch mock works now?

The source maps are tracked in https://github.com/modernweb-dev/web/issues/26

**Comment by RoXuS** [comment]
Great all is ok for fetch. I still have one failed I don't know why, on karma it is ok, I am studying.

Thx for your reactivity.

**Comment by RoXuS** [comment]
Ok it is ok on all my component, thx!
