### ISSUE TITLE
[test-runner-cli] Open debug mode on the current opened Chrome?

### ISSUE THREAD

**Issue by RoXuS** [modernweb-dev/web#91]
Can you open debug mode on the current opened Chrome ?

**Comment by LarsDenBakker** [comment]
This isn't possible because Chrome is launcher will special arguments which may be different from the ones you used to run your own installation. We close the browser when you close the test runner, so the extra window isn't very intrusive

**Comment by LarsDenBakker** [comment]
When we implement https://github.com/modernweb-dev/web/issues/56 you can just copy a URL and visit it in your current browser.

**Comment by RoXuS** [comment]
oh ok, I see, thx!
