### ISSUE TITLE
Images not served correctly in tests

### ISSUE THREAD

**Issue by crisward** [modernweb-dev/web#980]
Not sure if this is the right place to raise this. I'm experimenting with this library and snowpack to speed up our front end tests. So far its been very promising taking the current test suite down from 40 seconds to 6. 🎉 

However a batch of tests are failing, due to no images being served correctly. This only appear to be happening on the test server, (the one that  appears to run on port 9785 when you press `d` in the console). The snowpack server shows them fine.

I've included a basic png source, and the content thats served. I did a diff on these and it looks like some of the data is being changed. I suspect its some kind of encoding issue.

![served](https://user-images.githubusercontent.com/3109157/99875449-b3dd5a00-2be7-11eb-9d7c-076633f8e30b.png)

![original](https://user-images.githubusercontent.com/3109157/99875452-b8a20e00-2be7-11eb-809b-29ed29d4ed08.png)

**Comment by LarsDenBakker** [comment]
What's the request URL of the image? It might be the snowpack plugin not setting the mime type correctly. I added a `--debug` flag recently, that might give some more info as well.

Is it possible to create a minimal reproduction?

**Comment by crisward** [comment]
A snippet of the debug output is below. I also tried changing the filename to something other than 'test' and it still comes back malformed.

```
Receiving request: /downloads/test.png
/downloads/test.png
Plugin snowpack-plugin served /downloads/test.png.
Responding to request: /downloads/test.png with status 200
Receiving request: /downloads/test.png
```

**Comment by crisward** [comment]
Could be this - 
https://github.com/snowpackjs/snowpack/blob/main/plugins/web-test-runner-plugin/plugin.js#L40

Seems to set uft8 encoding, not sure, but that may break images. Will hack my local version and let you know.

**Comment by crisward** [comment]
I can confirm, deleting the 'utf8' parameter fixes it. I'll do a quick and dirty pull request on the snowpack plugin.

Thanks for the help.

**Comment by crisward** [comment]
That's done, many thanks for your quick response.

**Comment by LarsDenBakker** [comment]
Great to hear!
