### ISSUE TITLE
[dev-server-rollup] Only activates rollup plugins if file is JS or HTML

### ISSUE THREAD

**Issue by balloob** [modernweb-dev/web#991]
The Rollup adapter only activates the rollup plugin if the response is JS or HTML.

This means that it is currently impossible to process TypeScript/CSS with babel via Rollup.

https://github.com/modernweb-dev/web/blob/120f3d110a012b80877b6f9a5b020ee005127067/packages/dev-server-rollup/src/rollupAdapter.ts#L257

It is possible to change the above line to 

```js
if (context.response.is('js') || context.response.is("json") || context.response.is("ts") || context.response.is("css")) {
```

but that seems hacky. Should we allow passing in the types we expect to load?

**Comment by LarsDenBakker** [comment]
Rollup acts on files you intend to serve as JS to the browser. There is a section in the docs on setting the mime type: https://modern-web.dev/docs/dev-server/plugins/rollup/#non-standard-file-types

**Comment by balloob** [comment]
I should read the docs more carefully 🤦
