### ISSUE TITLE
[dev-server] Mimetype of TS files is incorrect when not using ESBuild

### ISSUE THREAD

**Issue by balloob** [modernweb-dev/web#992]
When not using ESBuild, the mime-type of TS files is set to `video/mp2t`, causing browsers to not execute it as JavaScript, even if it became valid JS after a transformation.

It can be solved with the following middleware, but that seems more like a hack than an actual fix. 

```ts
    async (ctx, next) => {
      await next();
      if (ctx.type === "video/mp2t") {
        ctx.type = "application/javascript";
      }
    },
```

**Comment by LarsDenBakker** [comment]
This is a correct solution, if you want to serve a different mime type you need to set it in the server. The server doesn't know that you intend to execute it as JS. 

There is also a plugin hook for this: https://modern-web.dev/docs/dev-server/writing-plugins/hooks/#hook-resolvemimetype

**Comment by balloob** [comment]
Oops, you're right that setting mimetypes makes everything work.
